### ISSUE TITLE
how to integrate pytorch-tabnet into skorch framework?

### ISSUE THREAD

**Issue by pangjac** [skorch-dev/skorch#1029]
Hello, I'm new to the Skorch community. I'm currently experimenting with [pytorch-tabnet](https://github.com/dreamquark-ai/tabnet), which is reputed to be a potent solution for tabular data in deep learning, **built on PyTorch**. 

My query pertains to integrating pytorch-tabnet within the scikit-learn framework. I attempted to search for `tabnet` within current `skorch` repository but couldn't find any relevant keywords, leading me to believe that tabnet hasn't been implemented here yet. 

With this in mind, if I wish to explore how to incorporate pytorch-tabnet into our framework, c**ould you recommend where I should start**? Is there any preliminary guidance or direction you could provide?

Thank you so much for this wonderful framework!

**Comment by ottonemo** [comment]
@pangjac there's this PR https://github.com/dreamquark-ai/tabnet/pull/279 where I added an example notebook showing how to integrate tabnet with skorch. The PR never got merged but it should still be able to serve you as an example I hope!
