### ISSUE TITLE
Add slides for Pydata Amsterdam

### ISSUE THREAD

**Issue by joshdunnlime** [skorch-dev/skorch#1035]
Might be worth adding a link in the README and in the comments here: https://www.youtube.com/watch?v=y_n7BjDCS-M

Thanks. Great talk as well!!

**Comment by BenjaminBossan** [comment]
> Great talk as well!!

Thanks.

> Might be worth adding a link in the README and in the comments here

We added a link to the README in #1033, if that's what you mean.

**Comment by joshdunnlime** [comment]
A link for the slides. You mentioned that there was extra info in some of the slides and that you'd share them, if I remember correctly!
