### ISSUE TITLE
Some confusing messages when components are re-initialized

### ISSUE THREAD

**Issue by benjamin-work** [skorch-dev/skorch#407]
The user-facing messages when the optimizer or module are re-initialized could be better.

* When the user calls `initialize_optimizer` directly, there could be a message like `"Re-initializing optimizer because the following parameters were re-set: lr."`. This is confusing (following up on discussion in #369).
* With `initialize_module`, a message like `"Re-initializing module because the following parameters were re-set: ."` can be triggered.
* When a module re-initialization is triggered through `set_params`, the optimizer is also re-set, but it could be clarified why that is. Currently, the message is `"Re-initializing optimizer."` but it would be better to have `"Re-initializing optimizer because another component triggered it."` or something.

**Comment by ottonemo** [comment]
Is this still relevant? There were a number of improvements in this area.

**Comment by BenjaminBossan** [comment]
I think it's good for now. If we encounter more confusing messages, we should open a new issue.
