### ISSUE TITLE
Clarify initialization behavior in FAQ when passing model instances

### ISSUE THREAD

**Issue by ottonemo** [skorch-dev/skorch#409]
The FAQ entry regarding initialization behavior when passing already instantiated models to `NeuralNet` and friends seems to be confusing (see #376). The explanation should be more detailed.

**Comment by thomasjpfan** [comment]
I think we should encourage using the non-instantiated model by passing a `nn.Module` subclass to `NeuralNet`.

**Comment by BenjaminBossan** [comment]
Solved via #417
