### ISSUE TITLE
NeuralNetClassifier's _default_callbacks. My hope is 'f1_score' .

### ISSUE THREAD

**Issue by ghost** [skorch-dev/skorch#424]
def _default_callbacks(self):
        return [
            ('epoch_timer', EpochTimer()),
            ('train_loss', BatchScoring(
                train_loss_score,
                name='train_loss',
                on_train=True,
                target_extractor=noop,
            )),
            ('valid_loss', BatchScoring(
                valid_loss_score,
                name='valid_loss',
                target_extractor=noop,
            )),
            ('valid_acc', EpochScoring(     # ??????????????Can it be a F1????????
                'accuracy',
                name='valid_acc',
                lower_is_better=False,
            )),
            ('print_log', PrintLog()),
        ]

**Comment by BenjaminBossan** [comment]
F1 score should work just fine. Here is an example of using sklearn metrics in skorch callbacks: https://nbviewer.jupyter.org/github/dnouri/skorch/blob/master/notebooks/Basic_Usage.ipynb#Callbacks
