### ISSUE TITLE
Misleading message if fit triggers re-initialization

### ISSUE THREAD

**Issue by BenjaminBossan** [skorch-dev/skorch#436]
Take the example from the README.md. If you call `net.initialize()` before calling `net.fit(X, y)`, the following message pops up:

```
Re-initializing module because the following parameters were re-set: .
Re-initializing optimizer because the following parameters were re-set: .
```

This isn't helpful at all. The message should be something like:

`The module and optimizer are reset because `fit` was called. To prevent that, use partial_fit`

**Comment by thomasjpfan** [comment]
> `The module and optimizer are reset because `fit` was called. To prevent that, use partial_fit`

This may be confusing in the context of the `Pipeline` example in the readme. That message makes calling `pipe.fit(X, y)` a mistake. For context here is the code outputting the message:

https://github.com/dnouri/skorch/blob/00eaaf10e135c6d69bf3b36d339b5a3a9df3fcc2/skorch/net.py#L466-L474

I propose a simpler message when `kwargs` is empty:

```
Re-initializing module because the module was already initialized.
```

**Comment by BenjaminBossan** [comment]
I agree that proposing to use `partial_fit` may be bad in case of a pipeline (although few people use pipelines *and* pre-initialize the net).

> Re-initializing module because the module was already initialized.

As a user with little skorch experience, I would find this confusing. If the module is already initialized, why re-initialize it?

How about this message instead:

`fit call has triggered re-initialization of the module and optimizer. To prevent that, either use warm_start=True or call partial_fit`

**Comment by thomasjpfan** [comment]
The only issue I have with referencing `fit` is how the message can trigger in when calling other methods, such as call `initialize`.

**Comment by BenjaminBossan** [comment]
The idea was to display the message specifically iff `fit` was called. I haven't investigated yet how feasible that is. If it isn't, then yes, the message would need to be different.

**Comment by thomasjpfan** [comment]
It is possible. We would need to change the `initialize_module` and `initialize` methods to accept a "caller" `keyword. This way the `initialize_*` methods know what function is calling it.

**Comment by BenjaminBossan** [comment]
My hope is to achieve the goal without the need to have a different signature on `initialize`. It is a method that at least a couple of users call directly. But having esoteric parameters like `triggered_by_fit` is somewhat exposing skorch internals. I would need to investigate more to see if that change would be necessary.

**Comment by thomasjpfan** [comment]
I was thinking of adding a `caller=None` option in `initialize`. 

Another option would to not have a message when `kwargs` is empty. Those coming from scikit-learn are familiar with how `fit` will re-initialize the model. We have this special logging because there is a chance `set_params` will re-initialize the model.
