### ISSUE TITLE
Github Organization for skorch

### ISSUE THREAD

**Issue by thomasjpfan** [skorch-dev/skorch#438]
Similar to what https://github.com/Lasagne/Lasagne/issues/38 did a few years ago, what is everyone thoughts on forming a github organization for skorch?

**Comment by BenjaminBossan** [comment]
I am open for discussion on this issue.

What would be the pro's and con's of moving skorch to its own orga. Who would be the owner, and is it possible to have more than one?

**Comment by thomasjpfan** [comment]
https://github.com/Lasagne/Lasagne/issues/38#issuecomment-56498712 summarizes it well:

> It's mainly a question of how you want to present it to the outside: as a project of yours with a couple of contributions from others (= personal account), or as a joint project with you being one of the core maintainers (= organization account)?

1. I see it as a way to give ownership of the project to a group, which would mitigate some risk of a single account. (What if something happens to @dnouri's account?)
2. skorch is already being run as a group endeavor. Creating an organization will formalize this structure.

**Comment by taketwo** [comment]
When I discover several open-source projects that maybe solve my problem, I often decide which ones to try (and in which order) based on multiple factors. Availability of documentation and green CI badge are perhaps the most important. But then there are also purely GitHub-related indicators like the number of stars, latest commit, and... whether the project is under a private or organizational account. The latter typically means more maturity, makes it less likely that the project just dies because the owner lost interest, and generally gives more credibility.

skorch is indeed a group effort and I believe is ripe enough to qualify for an organizational account and all the PR benefits it brings.

**Comment by BenjaminBossan** [comment]
I personally have no qualms with using libraries that are hosted on a personal account. Many great libraries are. But if that is a problem for some people, we should get rid of it.

What I couldn't find is whether there can be multiple owners for an orga. If not, is the bus factor really better?

I would also like to wait for @ottonemo's and @dnouri's opinion on this.

**Comment by dnouri** [comment]
I have no preference or opinion really.  :-)

**Comment by thomasjpfan** [comment]
There can be multiple owners: 

> In addition, organization members with owner permissions have extensive permissions across all repositories in an organization.

The reference is here: https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Comment by ottonemo** [comment]
I agree with the sentiment that @taketwo shared, that it is indeed a positive indicator for some people if the repo resides in an independent organization. It also makes shared ownership easier.

I'm fairly sure that moving the project to a organization is seamless, at least according to [the documentation](https://help.github.com/en/articles/transferring-a-repository).

The only downside I see is that we would need a name for that organization... I don't like compromise names such as 'skorch-o', 'skorchorg' etc. and sadly 'skorch' is already taken. Any suggestions?

**Comment by thomasjpfan** [comment]
We can follow [pandas](https://github.com/pandas-dev/pandas)  lead and use `skorch-dev`.

**Comment by BenjaminBossan** [comment]
skorch-dev would be acceptable to me.

**Comment by ottonemo** [comment]
The repo was just transferred and is now available under https://github.com/skorch-dev/skorch/.
