### ISSUE TITLE
How to pass parameters to forward function of my torch nn.module from skorch.NeuralNetClassifier.fit()

### ISSUE THREAD

**Issue by senbihan** [skorch-dev/skorch#444]
I have extended nn.Module to implement my network whose forward function is like this ...

    def forward(self, X, **kwargs):

        batch_size, seq_len = X.size()

        length = kwargs['length']
        embedded = self.embedding(X) # [batch_size, seq_len, embedding_dim]
        if self.use_padding:
            if length is None:
                raise AttributeError("Length must be a tensor when using padding")
            embedded = nn.utils.rnn.pack_padded_sequence(embedded, length, batch_first=True)
            #print("Size of Embedded packed", embedded[0].size())

        hidden, cell = self.init_hidden(batch_size)
        if self.rnn_unit == 'rnn':
            out, _ = self.rnn(embedded, hidden)
        elif self.rnn_unit == 'lstm':
            out, (hidden, cell) = self.rnn(embedded, (hidden, cell))

        # unpack if padding was used
        if self.use_padding:
            out, _ = nn.utils.rnn.pad_packed_sequence(out, batch_first = True)
        ...
        ...
        return out

I initialized a skorch NeuralNetClassifier like this,

`net = NeuralNetClassifier(model,criterion=nn.CrossEntropyLoss,optimizer=Adam, max_epochs=8, lr=0.01, batch_size=32)`

Now if I call `net.fit(X, y, length=X_len)` it throws an error

`TypeError: __call__() got an unexpected keyword argument 'length'`

According to the documentation fit function expects a fit_params dictionary,

`**fit_params : dict
         Additional parameters passed to the ``forward`` method of
         the module and to the ``self.train_split`` call.`

and according to the source code it sends my parameters to `train_split` where obviously my keyword argument would not be recognized.

Is there any way around to pass the arguments to my forward function?

**Comment by BenjaminBossan** [comment]
The best way for your case is to use a dictionary as input data. The code could look like this:

```python
X_dict = {'X': X, 'length': X_len}
net.fit(X_dict, y)
```

skorch will then call your `forward` method with the keys from the dictionary as keyword arguments. I assume that `X_len` has the same length as `X`.

More information can be found here:

https://skorch.readthedocs.io/en/stable/user/dataset.html#id1

**Comment by senbihan** [comment]
Thanks gotcha! :)
:+1:

**Comment by BenjaminBossan** [comment]
@senbihan I assume this is fixed. If not, please re-open.

**Comment by biaohanli** [comment]
I want to use GridSearchCV to search parameters and I want to use other paramters in forword(),but I cannot use GridSearchCV.fit() to transform parameters,how could I solve this problem?
thx.

**Comment by BenjaminBossan** [comment]
@biaohanli In general, the easiest way is to pack your data into a dictionary, as discussed above. When you want to pass a dict as `X` to the fit of grid search, you have to wrap it inside a `SliceDict` as mentioned [here](https://skorch.readthedocs.io/en/stable/user/FAQ.html#how-do-i-use-sklearn-gridseachcv-when-my-data-is-in-a-dictionary).
