### ISSUE TITLE
Early stopping best iteration

### ISSUE THREAD

**Issue by psinger** [skorch-dev/skorch#449]
I am trying to use early stopping callback but don't see an option to return only the best iteration after stopping. Is there any straight-forward way of doing that?

**Comment by githubnemo** [comment]
You can use the [`Checkpoint`](https://skorch.readthedocs.io/en/latest/callbacks.html#skorch.callbacks.Checkpoint) callback to save the best epoch. 

You can then use `net.load_params(checkpoint=dict(net.callbacks_['Checkpoint'])` to load the state from the last checkpoint. You can read more about this [here](https://skorch.readthedocs.io/en/latest/user/save_load.html#using-callbacks).

**Comment by ottonemo** [comment]
@psinger does this answer your question? :)

**Comment by BenjaminBossan** [comment]
@psinger Any update on this? If not, I will assume it worked and close this issue in a couple of days.
