### ISSUE TITLE
Error in documentation regarding make_regressor

### ISSUE THREAD

**Issue by benjamin-ny** [skorch-dev/skorch#450]
Default output units is 1, not 2:

https://github.com/skorch-dev/skorch/blob/fb9f723cfe89719a37922c3bd4882d898164e9b8/skorch/toy.py#L159

**Comment by ottonemo** [comment]
Do you want to make a PR for that? :)

**Comment by benjamin-ny** [comment]
Yeah, it's more of a reminder ;)

**Comment by ottonemo** [comment]
addressed in https://github.com/skorch-dev/skorch/pull/452
