### ISSUE TITLE
How to access to the latent space of an autoencoder?

### ISSUE THREAD

**Issue by ssoulhi** [skorch-dev/skorch#451]
I have defined the autoencoder below:

```
<class 'skorch.net.NeuralNet'>[initialized](
  module_=Autoencoder(
    (encoder): Sequential(
      (0): Linear(in_features=163, out_features=200, bias=False)
      (1): Tanh()
      (2): Linear(in_features=200, out_features=100, bias=False)
      (3): Tanh()
      (4): Linear(in_features=100, out_features=40, bias=False)
      (5): Tanh()
      (6): Linear(in_features=40, out_features=20, bias=False)
      (7): Tanh()
      (8): Linear(in_features=20, out_features=10, bias=False)
      (9): Tanh()
    )
    (decoder): Sequential(
      (0): Linear(in_features=10, out_features=20, bias=False)
      (1): Tanh()
      (2): Linear(in_features=20, out_features=40, bias=False)
      (3): Tanh()
      (4): Linear(in_features=40, out_features=100, bias=False)
      (5): Tanh()
      (6): Linear(in_features=100, out_features=200, bias=False)
      (7): Tanh()
      (8): Linear(in_features=200, out_features=163, bias=False)
    )
  ),
)
```

`net.predict(new_data)` works fine for the reconstructed space.
how to get the latent space?
I have tried:
```
with torch.no_grad():
    encoded_in = net.module_.encoder(new_data)
```
and I got the following error: `AttributeError: 'numpy.ndarray' object has no attribute 'dim'`

**Comment by BenjaminBossan** [comment]
You were almost there, the origin of the error is that you are passing a numpy array where you need a torch tensor. To convert the data, you could e.g. use `torch.from_numpy`.

However, this is not necessarily the recommended way of doing things. E.g. if your input data is very large, this approach could take too much memory because you are circumventing batching. For this reason, skorch has another facility. Your module's forward method should return both the reconstruction and the encoded data:

```python
    def forward(self, X):
        encoded = self.encoder(X)
        decoded = self.decode(encoded)
        return encoded, decoded
```

Then, to get back both outputs, call `net.forward(X)` (more can be found in the [docs](https://skorch.readthedocs.io/en/stable/user/neuralnet.html#predict-x-and-predict-proba-x)).

**Comment by ssoulhi** [comment]
Thanks Benjamin,

I made the change you suggested to return both the reconstruction and the encoded data but I got the following error when calling the fit:

TypeError                                 Traceback (most recent call last)
<ipython-input-49-2f3daddc67a5> in <module>
----> 1 net.fit(df_n, df_n);

/conda/envs/rapids/lib/python3.5/site-packages/torch/nn/modules/loss.py in forward(self, input, target)
    419 
    420     def forward(self, input, target):
--> 421         return F.mse_loss(input, target, reduction=self.reduction)
    422 
    423 

/conda/envs/rapids/lib/python3.5/site-packages/torch/nn/functional.py in mse_loss(input, target, size_average, reduce, reduction)
   1714     else:
   1715         reduction = _Reduction.get_enum(reduction)
-> 1716     return _pointwise_loss(lambda a, b: (a - b) ** 2, torch._C._nn.mse_loss, input, target, reduction)
   1717 
   1718 

/conda/envs/rapids/lib/python3.5/site-packages/torch/nn/functional.py in _pointwise_loss(lambd, lambd_optimized, input, target, reduction)
   1672         return torch.mean(d) if reduction == 'elementwise_mean' else torch.sum(d)
   1673     else:
-> 1674         return lambd_optimized(input, target, reduction)
   1675 
   1676 

TypeError: mse_loss(): argument 'input' (position 1) must be Tensor, not tuple

**Comment by BenjaminBossan** [comment]
Ah yes, now both of your outputs are passed to the criterion, which doesn't know what to do with them. Probably the easiest solution is to call the criterion with only the decoded images by creating a subclass of the net that does this:

```python
class MyNet(NeuralNet):  # assuming that you use the NeuralNet class
    def get_loss(self, y_pred, y_true, *args, **kwargs):
        decoded, encoded = y_pred
        return super().get_loss(decoded, y_true, *args, **kwargs)
```

I also made a small mistake above, you should return the decoded images first and the encoded second in your module:

```python
    def forward(self, X):
        encoded = self.encoder(X)
        decoded = self.decode(encoded)
        return decoded, encoded
```

This is assuming that you want `net.predict` to return the decoded images by default (skorch will by default return the first value returned by the forward method).

**Comment by ssoulhi** [comment]
Thanks Benjamin !!!!!
The subclass of the net solved the problem
