### ISSUE TITLE
get_len() issue with inconsistent lengths

### ISSUE THREAD

**Issue by mshuaibii** [skorch-dev/skorch#456]
In scenarios when a model expects to read in a dataset with inconsistent lengths and manipulate the data accordingly, the get_len() function causes issues as the following lines raise an error:
`if len(len_set) != 1:
      raise ValueError("Dataset does not have consistent lengths."`

A flag should be possible such that the lines can be ignored and the minimum # data is taken from the set for those who are aware they are feeding inconsistent data lengths.

Another work around was to modify 
`self.history.record_batch('train_batch_size',get_len(Xi))`
to 
`self.history.record_batch('train_batch_size',get_len(yi))`

As the target length is a definite measure of the batch_size.

**Comment by githubnemo** [comment]
> A flag should be possible such that the lines can be ignored and the minimum # data is taken from the set for those who are aware they are feeding inconsistent data lengths.

But if you discard the excess data anyway, why don't you do it beforehand? I'm not sure I understand the scenario correctly.

> As the target length is a definite measure of the `batch_size`.

I don't think we can use `get_len(yi)` as a definite measure since in unsupervised learning `y` is not defined (at least not the way we handle it now, with `y=None`. We could think about always providing `y` and setting `y=X` but I remember that we had this discussion already and decided `y=None` was the better way to go).

**Comment by mshuaibii** [comment]
>

**Comment by mshuaibii** [comment]
> But if you discard the excess data anyway, why don't you do it beforehand? I'm not sure I understand the scenario correctly.

The data isn't discarded within the model. As an example, our input data is a dictionary of values {A:[data1],B:[data2,data3]}. The model in use feeds A through one NN, and B through another NN. The output from each individual NN is then summed to arrive at the final output which is then compared to the target. The issue with get_len() in this case is it notices A has length 1 and B has length 2 and assumes the inconsistency is an issue when in reality, after being fed through the model we arrive at 1 output value that can then be fed to our loss function. Hope this clarifies it. I see your point with get_len(yi).

**Comment by BenjaminBossan** [comment]
Not sure if you can use it for your case, but skorch's `Dataset` class allows to pass a `length` parameter, which will be returned if `len(dataset)` is called.
