### ISSUE TITLE
fit function not working within pipeline

### ISSUE THREAD

**Issue by ssoulhi** [skorch-dev/skorch#458]
Hi,
pipe = Pipeline([
    ('scale', preprocessing.MinMaxScaler()),
    ('debug1', Debug()),
    ('torch', ToTorch()),
    ('debug2', Debug()),
    ('net', net),
])

class Debug(BaseEstimator, TransformerMixin):

    def transform(self, X):
        #print(pd.DataFrame(X).head())
        #print(X.shape)
        print('ok')
        return X

    def fit(self, X, y=None, **fit_params):
        return self

class ToTorch(TransformerMixin):
  def transform(self,X):
    Y = torch.from_numpy(X).to(device);
    return Y
    
  def fit(self,X, y=None):
    return self

Below the trace:

TypeError                                 Traceback (most recent call last)
<ipython-input-53-ba290decf74f> in <module>
      9 ])
     10 
---> 11 pipe.fit(df_indexed,df_indexed)

/conda/envs/rapids/lib/python3.5/site-packages/sklearn/pipeline.py in fit(self, X, y, **fit_params)
    265         Xt, fit_params = self._fit(X, y, **fit_params)
    266         if self._final_estimator is not None:
--> 267             self._final_estimator.fit(Xt, y, **fit_params)
    268         return self
    269 

/conda/envs/rapids/lib/python3.5/site-packages/skorch/net.py in fit(self, X, y, **fit_params)
    840             self.initialize()
    841 
--> 842         self.partial_fit(X, y, **fit_params)
    843         return self
    844 

/conda/envs/rapids/lib/python3.5/site-packages/skorch/net.py in partial_fit(self, X, y, classes, **fit_params)
    799         self.notify('on_train_begin', X=X, y=y)
    800         try:
--> 801             self.fit_loop(X, y, **fit_params)
    802         except KeyboardInterrupt:
    803             pass

/conda/envs/rapids/lib/python3.5/site-packages/skorch/net.py in fit_loop(self, X, y, epochs, **fit_params)
    734             self.notify('on_epoch_begin', **on_epoch_kwargs)
    735 
--> 736             for Xi, yi in self.get_iterator(dataset_train, training=True):
    737                 yi_res = yi if not y_train_is_ph else None
    738                 self.notify('on_batch_begin', X=Xi, y=yi_res, training=True)

/conda/envs/rapids/lib/python3.5/site-packages/torch/utils/data/dataloader.py in __next__(self)
    312         if self.num_workers == 0:  # same-process loading
    313             indices = next(self.sample_iter)  # may raise StopIteration
--> 314             batch = self.collate_fn([self.dataset[i] for i in indices])
    315             if self.pin_memory:
    316                 batch = pin_memory_batch(batch)

/conda/envs/rapids/lib/python3.5/site-packages/torch/utils/data/dataloader.py in default_collate(batch)
    185     elif isinstance(batch[0], collections.Sequence):
    186         transposed = zip(*batch)
--> 187         return [default_collate(samples) for samples in transposed]
    188 
    189     raise TypeError((error_msg.format(type(batch[0]))))

/conda/envs/rapids/lib/python3.5/site-packages/torch/utils/data/dataloader.py in <listcomp>(.0)
    185     elif isinstance(batch[0], collections.Sequence):
    186         transposed = zip(*batch)
--> 187         return [default_collate(samples) for samples in transposed]
    188 
    189     raise TypeError((error_msg.format(type(batch[0]))))

/conda/envs/rapids/lib/python3.5/site-packages/torch/utils/data/dataloader.py in default_collate(batch)
    187         return [default_collate(samples) for samples in transposed]
    188 
--> 189     raise TypeError((error_msg.format(type(batch[0]))))
    190 
    191 

TypeError: batch must contain tensors, numbers, dicts or lists; found <class 'pandas.core.series.Series'>

**Comment by BenjaminBossan** [comment]
Hi, could you please try to format the code correctly, it is a little bit hard to see what's going on.

Regarding the error itself: Could you try to remove the net from the pipeline and call `fit_transform`, then report back what comes out of the pipeline? My impression is that inspite of `ToTorch`, it is a pandas `Series` object.

**Comment by ssoulhi** [comment]
Hi Benjamin,
After removing the net from the pipeline and call fit_tranform  I got:

`from sklearn.base import TransformerMixin

class ToTorch(TransformerMixin):
  def transform(self,X):
    Y = torch.from_numpy(X).to(device);
    return Y
    
  def fit(self,X, y=None):
    return self`

 `pipe = Pipeline([
    ('scale', preprocessing.MinMaxScaler()),
    ('debug1', Debug()),
    ('torch', ToTorch()),
    ('debug2', Debug()),
    ])

pipe.fit_transform(df_indexed,df_indexed)`

output:
/conda/envs/rapids/lib/python3.5/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)
ok
ok
tensor([[0.0000, 0.0003, 0.8824,  ..., 0.6347, 0.2368, 0.0000],
        [0.0000, 0.0002, 0.7759,  ..., 0.6280, 0.5752, 0.0000],
        [0.0000, 0.0011, 0.7381,  ..., 0.7307, 0.5487, 0.0000],
        ...,
        [1.0000, 0.0004, 0.6667,  ..., 0.7400, 0.6585, 0.0000],
        [1.0000, 0.0007, 0.7200,  ..., 0.7047, 0.7767, 0.0000],
        [1.0000, 0.0001, 0.8000,  ..., 0.6180, 0.7290, 0.0000]],
       device='cuda:0', dtype=torch.float64)

Thanks for your help!

**Comment by BenjaminBossan** [comment]
I see two potential issues here. First is that your `X` data is converted to float64, whereas you probably want float32. Maybe you could convert inside your `ToTorch` class.

Second, from your first post, it seems that a pandas `Series` object is passed. Since it's not `X`, it must be `y`. However, I cannot reproduce your error when passing a `Series` as `y`. Anyway, I wonder if it needs to be a `Series`? Can you convert it to, say, a numpy array?

**Comment by ssoulhi** [comment]
In my case the y is similar to x since it's an autoencoder. Below all functions:

`from sklearn.base import TransformerMixin

class ToTorch(TransformerMixin):
  def transform(self,X):
    Y = torch.from_numpy(X).float().to(device)
    return Y
    
  def fit(self,X, y=None):
    return self`

`class Autoencoder(nn.Module):
    def __init__(self):
        super(Autoencoder,self).__init__() # This should apply Uniform random values to weights and biases. 
        
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, 20 * encoding_dim,bias=False),
            nn.Tanh(),
            nn.Linear(20 * encoding_dim, 10 * encoding_dim,bias=False),
            nn.Tanh(),
            nn.Linear(10 * encoding_dim, 4 * encoding_dim,bias=False),
            nn.Tanh(),
            nn.Linear(4 * encoding_dim, 2 * encoding_dim,bias=False),
            nn.Tanh(),
            nn.Linear(2 * encoding_dim, encoding_dim,bias=False),
            nn.Tanh())
        
        self.decoder = nn.Sequential(             
            nn.Linear(encoding_dim, 2 * encoding_dim,bias=False),
            nn.Tanh(),
            nn.Linear(2 * encoding_dim, 4 * encoding_dim,bias=False),
            nn.Tanh(),
            nn.Linear(4 * encoding_dim, 10 * encoding_dim,bias=False),
            nn.Tanh(),
            nn.Linear(10 * encoding_dim, 20 * encoding_dim,bias=False),
            nn.Tanh(),
            nn.Linear(20 * encoding_dim,input_dim,bias=False))
    
    def forward(self,x):
        encoded = self.encoder(x)
        decoded = self.decoder(encoded)
        return decoded, encoded`

`class MyNet(NeuralNet):  # assuming that you use the NeuralNet class
    def get_loss(self, y_pred, y_true, *args, **kwargs):
        decoded, encoded = y_pred
        return super().get_loss(decoded, y_true, *args, **kwargs)`

`net = MyNet(
    module=Autoencoder,
    max_epochs=500,
    batch_size=100,
    lr=learning_rate,
    criterion=torch.nn.MSELoss,
    optimizer=torch.optim.Adam,
    iterator_train__shuffle=True,
    callbacks = [skorch.callbacks.EarlyStopping(monitor='valid_loss', patience=10, threshold=0.0001)],
    device=device,
)

`from sklearn.pipeline import Pipeline
pipe = Pipeline([
    ('scale', preprocessing.MinMaxScaler()),
    ('debug1', Debug()),
    ('torch', ToTorch()),
    ('debug2', Debug()),
    ('net', net),
])
'
pipe.fit(df_indexed,df_indexed)`

**Comment by BenjaminBossan** [comment]
Without the data, it is hard to tell what is going on. Again, do you really need your data to be a pandas `Series` or `DataFrame`? Could you convert it to a numpy array (`df_indexed.values`) and see what happens?

**Comment by ssoulhi** [comment]
Hi Benjamin,
I got another error when converting to Numpy. How to ensure that the second argument is also transformed in the pipeline?

error is:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-66-19cbd60d3d47> in <module>
      9 ])
     10 
---> 11 pipe.fit(df_indexed.values,df_indexed.values)

/conda/envs/rapids/lib/python3.5/site-packages/sklearn/pipeline.py in fit(self, X, y, **fit_params)
    265         Xt, fit_params = self._fit(X, y, **fit_params)
    266         if self._final_estimator is not None:
--> 267             self._final_estimator.fit(Xt, y, **fit_params)
    268         return self
    269 

/conda/envs/rapids/lib/python3.5/site-packages/skorch/net.py in fit(self, X, y, **fit_params)
    840             self.initialize()
    841 
--> 842         self.partial_fit(X, y, **fit_params)
    843         return self
    844 

/conda/envs/rapids/lib/python3.5/site-packages/skorch/net.py in partial_fit(self, X, y, classes, **fit_params)
    799         self.notify('on_train_begin', X=X, y=y)
    800         try:
--> 801             self.fit_loop(X, y, **fit_params)
    802         except KeyboardInterrupt:
    803             pass

/conda/envs/rapids/lib/python3.5/site-packages/skorch/net.py in fit_loop(self, X, y, epochs, **fit_params)
    737                 yi_res = yi if not y_train_is_ph else None
    738                 self.notify('on_batch_begin', X=Xi, y=yi_res, training=True)
--> 739                 step = self.train_step(Xi, yi, **fit_params)
    740                 self.history.record_batch('train_loss', step['loss'].item())
    741                 self.history.record_batch('train_batch_size', get_len(Xi))

/conda/envs/rapids/lib/python3.5/site-packages/skorch/net.py in train_step(self, Xi, yi, **fit_params)
    666             step_accumulator.store_step(step)
    667             return step['loss']
--> 668         self.optimizer_.step(step_fn)
    669         return step_accumulator.get_step()
    670 

/conda/envs/rapids/lib/python3.5/site-packages/torch/optim/adam.py in step(self, closure)
     55         loss = None
     56         if closure is not None:
---> 57             loss = closure()
     58 
     59         for group in self.param_groups:

/conda/envs/rapids/lib/python3.5/site-packages/skorch/net.py in step_fn()
    663         step_accumulator = self.get_train_step_accumulator()
    664         def step_fn():
--> 665             step = self.train_step_single(Xi, yi, **fit_params)
    666             step_accumulator.store_step(step)
    667             return step['loss']

/conda/envs/rapids/lib/python3.5/site-packages/skorch/net.py in train_step_single(self, Xi, yi, **fit_params)
    605         self.module_.train()
    606         self.optimizer_.zero_grad()
--> 607         y_pred = self.infer(Xi, **fit_params)
    608         loss = self.get_loss(y_pred, yi, X=Xi, training=True)
    609         loss.backward()

/conda/envs/rapids/lib/python3.5/site-packages/skorch/net.py in infer(self, x, **fit_params)
    966             x_dict = self._merge_x_and_fit_params(x, fit_params)
    967             return self.module_(**x_dict)
--> 968         return self.module_(x, **fit_params)
    969 
    970     def predict_proba(self, X):

/conda/envs/rapids/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

<ipython-input-33-e873496146da> in forward(self, x)
     27 
     28     def forward(self,x):
---> 29         encoded = self.encoder(x)
     30         decoded = self.decoder(encoded)
     31         return decoded, encoded

/conda/envs/rapids/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

/conda/envs/rapids/lib/python3.5/site-packages/torch/nn/modules/container.py in forward(self, input)
     89     def forward(self, input):
     90         for module in self._modules.values():
---> 91             input = module(input)
     92         return input
     93 

/conda/envs/rapids/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

/conda/envs/rapids/lib/python3.5/site-packages/torch/nn/modules/linear.py in forward(self, input)
     53 
     54     def forward(self, input):
---> 55         return F.linear(input, self.weight, self.bias)
     56 
     57     def extra_repr(self):

/conda/envs/rapids/lib/python3.5/site-packages/torch/nn/functional.py in linear(input, weight, bias)
   1024         return torch.addmm(bias, input, weight.t())
   1025 
-> 1026     output = input.matmul(weight.t())
   1027     if bias is not None:
   1028         output += bias

RuntimeError: Expected object of type torch.cuda.DoubleTensor but found type torch.cuda.FloatTensor for argument #2 'mat2'

`pipe = Pipeline([
    ('scale', preprocessing.MinMaxScaler()),
    ('debug1', Debug()),
    ('torch', ToTorch()),
    ('debug2', Debug()),
    ('net', net),
])

pipe.fit(df_indexed.values,df_indexed.values)`

`from sklearn.base import TransformerMixin

class ToTorch(TransformerMixin):
  def transform(self,X):
    Y = torch.from_numpy(X).to(device)
    Y = Y.type(torch.DoubleTensor)
    return Y
    
  def fit(self,X, y=None):
    return self`

`class Autoencoder(nn.Module):
    def __init__(self):
        super(Autoencoder,self).__init__() # This should apply Uniform random values to weights and biases. 
        
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, 20 * encoding_dim,bias=False),
            nn.Tanh(),
            nn.Linear(20 * encoding_dim, 10 * encoding_dim,bias=False),
            nn.Tanh(),
            nn.Linear(10 * encoding_dim, 4 * encoding_dim,bias=False),
            nn.Tanh(),
            nn.Linear(4 * encoding_dim, 2 * encoding_dim,bias=False),
            nn.Tanh(),
            nn.Linear(2 * encoding_dim, encoding_dim,bias=False),
            nn.Tanh())
        
        self.decoder = nn.Sequential(             
            nn.Linear(encoding_dim, 2 * encoding_dim,bias=False),
            nn.Tanh(),
            nn.Linear(2 * encoding_dim, 4 * encoding_dim,bias=False),
            nn.Tanh(),
            nn.Linear(4 * encoding_dim, 10 * encoding_dim,bias=False),
            nn.Tanh(),
            nn.Linear(10 * encoding_dim, 20 * encoding_dim,bias=False),
            nn.Tanh(),
            nn.Linear(20 * encoding_dim,input_dim,bias=False))
    
    def forward(self,x):
        encoded = self.encoder(x)
        decoded = self.decoder(encoded)
        return decoded, encoded`
Thanks

**Comment by BenjaminBossan** [comment]
The error message says that you have a double (float64) tensor, my guess is that you need to set the dtype explicitly to float32 (e.g. `x.astype(np.float32)`).

**Comment by ssoulhi** [comment]
It works now.
Thanks Benjamin !!!!!

**Comment by smith558** [comment]
This is horrible. The code snippets are not readable at all and, thus, not helpful to others. @ssoulhi
