### ISSUE TITLE
Use new URL for skorch repo

### ISSUE THREAD

**Issue by BenjaminBossan** [skorch-dev/skorch#479]
The skorch repo moved to its own organization. There are still URLs referring to its old place. Those should be corrected.

**Comment by joshy** [comment]
I can create a pull request if nobody is working on that.

**Comment by BenjaminBossan** [comment]
@joshy That would be very welcome

**Comment by joshy** [comment]
https://github.com/skorch-dev/skorch/pull/520

**Comment by BenjaminBossan** [comment]
Solved by #520
