### ISSUE TITLE
parameter groupings and learning rates in grid/random search

### ISSUE THREAD

**Issue by bbrighttaer** [skorch-dev/skorch#485]
Hi,
I'm starting out with Skorch and would like to know how grouped parameters could be submitted to the optimizer. Also, how could the learning rates and other grouped parameter-specific attributes be searched using a grid or a random search? 
I could not locate such a use case in the [Skorch notebooks](https://github.com/skorch-dev/skorch/tree/master/notebooks) or the [FAQ](https://skorch.readthedocs.io/en/stable/user/FAQ.html).
Thanks!

**Comment by BenjaminBossan** [comment]
Do you mean like this: https://skorch.readthedocs.io/en/stable/user/neuralnet.html#optimizer

**Comment by bbrighttaer** [comment]
Thanks very much, @BenjaminBossan for your pointer. Could you elaborate further on my second question, please? It is unclear to me how, say, scipy distributions like stats.uniform could be used in a random search for the learning rates of the parameter groups.

**Comment by BenjaminBossan** [comment]
Regarding how to perform hyper-parameter search: Here skorch uses the same interface as any sklearn model. You can look at the [documentation](https://skorch.readthedocs.io/en/stable/user/quickstart.html#grid-search), the [examples](https://nbviewer.jupyter.org/github/dnouri/skorch/blob/master/notebooks/Basic_Usage.ipynb#Usage-with-sklearn-GridSearchCV), or at this [sklearn example](https://scikit-learn.org/stable/auto_examples/model_selection/plot_randomized_search.html#sphx-glr-auto-examples-model-selection-plot-randomized-search-py). The latter shows how to use `scipy.stats`.

You can use the param groups as you would any other hyper-parameter.

**Comment by BenjaminBossan** [comment]
@bbrighttaer Do you have any further questions?

**Comment by bbrighttaer** [comment]
Thanks very much, @BenjaminBossan. I will try out your suggestions.
