### ISSUE TITLE
Using Pandas' DataFrames

### ISSUE THREAD

**Issue by lorenzoFabbri** [skorch-dev/skorch#494]
I have set up a pipeline using Scikit-learn. It works well with Scikit-learn's models. I'd like to try using DNNs now. My pipeline makes heavy use of Pandas' DataFrames and modifying it to use NumPy's arrays would mean wasting a lot of time.

I tried to fit a simple NN to learn how to use Skorch. If to the `fit` method I pass `X.astype(np.float32).values`, with `X` being my matrix of descriptors, it seems to be working properly. If I pass `X.astype(np.float32)`, so a DataFrame, and I rename all the columns to, for instance, `feature`, it seems to just hang (it does not print the training progress). If, on the other hand, I just pass the DataFrame without renaming the columns, it raises the following error:

`TypeError: forward() got an unexpected keyword argument 'feature_0'`.

I did not find any example using DataFrames. Is there a way to simply pass one?

**Comment by BenjaminBossan** [comment]
So the problem with DataFrames is that they often hold all different kinds of data, whereas a neural net typically only accepts float32 (or float16). Therefore, there is no straightforward way to go from DataFrame to torch array.

> I tried to fit a simple NN to learn how to use Skorch. If to the `fit` method I pass `X.astype(np.float32).values`, with `X` being my matrix of descriptors, it seems to be working properly.

This is basically the way to go. You can add a `FunctionTransformer` to your pipeline, directly before the net, that does the conversion.

> and I rename all the columns to, for instance, `feature`, it seems to just hang

I don't think it's a good idea to rename all columns to the same name.

> If, on the other hand, I just pass the DataFrame without renaming the columns, it raises the following error:

Yes, the reason for this is that it will pass the column name as keyword arguments, so when you have a DataFrame with columns 'feat_0' and 'feat_1', it will call `module(feat_0=X['feat_0'], feat_1=X['feat_1'])`. Therefore, you need to write your `module`'s `forward` method to accept these argument names.

**Comment by lorenzoFabbri** [comment]
Thanks for answering.
So, do you think that if I add a step to my Scikit-learn pipeline (i.e., a `Pipeline` Object), that simply extracts a NumPy array, it will do the trick?

**Comment by BenjaminBossan** [comment]
This is what I usually do:


```python
def toarray(X, dtype=np.float32):
    return X.values.astype(dtype)

model = Pipeline([
    ...
    ('toarray', FunctionTransformer(toarray, validate=False)),  # don't complain when a df comes
    ('net', NeuralNet(...)),
])
```

However, if your DataFrame has some more complex data like categorical features, you need to do some additional work like one-hot encoding or embedding layers, which you wouldn't need with other estimators like XGBoost.

**Comment by lorenzoFabbri** [comment]
I’ll try changing the pipeline then. Again, thank you.
I’ll close the issue once tested.

**Comment by BenjaminBossan** [comment]
Good luck. Open again if it doesn't work.
