### ISSUE TITLE
Should `load_params(cp=Checkpoint)` always initialize when needed?

### ISSUE THREAD

**Issue by thomasjpfan** [skorch-dev/skorch#497]
Should `load_params(cp=Checkpoint)` always initialize when `initialized_` is False?

**Comment by BenjaminBossan** [comment]
I haven't thought of this, is there any harm in doing so?

**Comment by thomasjpfan** [comment]
I don’t see any harm in doing this. One can only load from a checkpoint when the module is initialized.

**Comment by BenjaminBossan** [comment]
Sounds good. Perhaps there are even other spots where we could initialize out of convenience.
