### ISSUE TITLE
Error in Binary Classification in NeuralNetBinaryClassifier.

### ISSUE THREAD

**Issue by hekind** [skorch-dev/skorch#502]
When I use BinaryClassifer, and there is always an error `ValueError: The target data should be 1-dimensional.`. 

I change my target data into 1-dimensional with `array.ravel()`, it show  `ValueError: Target size (torch.Size([128])) must be the same as input size (torch.Size([128, 1]))`.

When I use set criterion=nn.BCEWithLogitsLoss, it run successfully.

I thinks there is wrong in classifier.check_data().

**Comment by BenjaminBossan** [comment]
Can you tell us what criterion you are using if not `BCEWithLogitsLoss`?

As a workaround, you could override `check_data` and see if that works.

**Comment by hekind** [comment]
Yes I use BCEWithLogitsLoss. I use BCELoss and it works. I wish you could fix that problem about BCEWithLogitsLoss.

**Comment by BenjaminBossan** [comment]
I cannot reproduce the error. Can you please post what kind of data you use, i.e.

* type
* dtype
* shape

of X and y? Also, the code for the module would help.

**Comment by hekind** [comment]
I write a case for the error.

    import numpy as np
    import torch as torch
    import torch.nn as nn
    import torch.nn.functional as F
    from skorch import NeuralNetBinaryClassifier
    torch.set_default_dtype(torch.float64)
    
    
    class MyNet(nn.Module):
        def __init__(self):
            super(MyNet, self).__init__()
            self.linear = nn.Linear(100, 50)
            self.output = nn.Linear(50, 1)
    
        def forward(self, input):
            out = input
            out = self.linear(out)
            out = F.relu(out)
            out = self.output(out)
            out = torch.sigmoid(out)
            return out
    
    
    X = np.random.normal(size=(200, 100))
    y = np.zeros((200,1))
    y[100:] = 1
    net = NeuralNetBinaryClassifier(MyNet)
    net.fit(X, y) # ValueError: The target data should be 1-dimensional.
    net.fit(X, y.ravel()) # ValueError: X and y have inconsistent lengths.

I change the loss into BCELoss and add sigmoid function in MyNet. It works.

    net = NeuralNetBinaryClassifier(MyNet, criterion=nn.BCELoss)
    net.fit(X, y.ravel())

**Comment by thomasjpfan** [comment]
The output of the Module needs to be 1-D:

```py
import torch.nn as nn
import numpy as np
from skorch import NeuralNetBinaryClassifier
from torch.nn.functional import relu

class MyNet(nn.Module):
    def __init__(self):
        super(MyNet, self).__init__()
        self.linear = nn.Linear(100, 50)
        self.output = nn.Linear(50, 1)

    def forward(self, input):
        out = input
        out = self.linear(out)
        out = relu(out)
        out = self.output(out)
        return out.squeeze(-1)


X = np.random.normal(size=(200, 100)).astype('float32')
y = np.zeros(200).astype('float32')
y[:100] = 1
net = NeuralNetBinaryClassifier(MyNet)
```

**Comment by hekind** [comment]
Ok, thank you.
