### ISSUE TITLE
Simple way for variable size inputs?

### ISSUE THREAD

**Issue by jGsch** [skorch-dev/skorch#504]
Hi everybody !

I am trying to train a MaskRCNN with Skorch but I have some issues variable input size. 

To avoid this in Pytorch, I add a `collate_fn` to the dataloader constructor like this:
```
def collate_fn(batch):
    return tuple(zip(*batch))
```

Is there an elegant way to do the same in Skorch ?

**Comment by BenjaminBossan** [comment]
Not quite sure what your exact error is but you can pass your collate function to the DataLoader like this:

```python
net = NeuralNet(
    ...
    iterator_train__collate_fn=collate_fn,
    iterator_valid__collate_fn=collate_fn,
)
```

**Comment by jGsch** [comment]
I need to read better the doc.... Thank you! :)
