### ISSUE TITLE
Skorch GridSearch CV list index out of range

### ISSUE THREAD

**Issue by BayuSasongko** [skorch-dev/skorch#513]
Im using SlideDataset But list index out of range. This is my code :

data_dir = b_cancer_data2
train_transforms = transforms.Compose([
     transforms.RandomRotation(30),
        transforms.RandomResizedCrop(224),
        #transforms.ColorJitter(brightness=0.4, contrast=0.4, saturation=0.4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
val_transforms = transforms.Compose([
    transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

train_ds = datasets.ImageFolder(
    os.path.join(data_dir, 'train'), train_transforms)
val_ds = datasets.ImageFolder(
    os.path.join(data_dir, 'valid'), val_transforms)

class MyDataset(Dataset):
    def __init__(self, train_ds, val_ds):
        self.train_ds = train_ds
        self.val_ds = val_ds
    def __len__(self):
        return len(self.train_ds)
    def __getitem__(self, i):
        Xi = self.train_ds[i]
        yi = self.val_ds[i]
        return self.transform(Xi, yi)
ds = MyDataset(train_ds, val_ds)

class SliceDatasetX(Dataset):
    def __init__(self, dataset, collate_fn=default_collate):
        self.dataset = dataset
        self.collate_fn = collate_fn
        self._indices = list(range(len(self.dataset)))
    def __len__(self):
        return len(self.dataset)
    @property
    def shape(self):
        return len(self),
    def __getitem__(self, i):
        if isinstance(i, (int, np.integer)):
            Xb = self.transform(*self.dataset[i])[0]
            return Xb
        if isinstance(i, slice):
            i = self._indices[i]
        Xb = self.collate_fn([self.transform(*self.dataset[j])[0] for j in i])
        return Xb

class PretrainedModel(nn.Module):
    def __init__(self, output_features):
        super().__init__()
        model = models.resnet152(pretrained=True)
        num_ftrs = model.fc.in_features
        model.fc = nn.Linear(num_ftrs, output_features)
        self.model = model
    def forward(self, x):
        return self.model(x)

from skorch.callbacks import Checkpoint
net = NeuralNetClassifier(
    PretrainedModel, 
    max_epochs=10,
    lr=0.1,
    iterator_train__shuffle=True,
    verbose=False,
    train_split=None,
    callbacks=[checkpoint, freezer],
    device='cuda'
)
from sklearn.model_selection import GridSearchCV
params = {
    'lr': [0.01, 0.02],
    'max_epochs': [10, 20]
}
gs = GridSearchCV(net, params, refit=False, cv=5, scoring='accuracy')
y_from_ds = np.asarray([ds[i][1] for i in range(len(ds))])
ds_sliceable = SliceDatasetX(ds)

But Index Error IndexError: list index out of range
**Help me please ???**

**Comment by BenjaminBossan** [comment]
A couple of things:

* Could you please edit your comment to have the correct code formatting, as it is, it is really hard to understand.
* Could you paste the whole backtrace of the error, not just the last line?

The first thing I see is that your `MyDataset` class does something wrong:

```python
class MyDataset(Dataset):
    def __init__(self, train_ds, val_ds):
        self.train_ds = train_ds
        self.val_ds = val_ds

    def __len__(self):
        return len(self.train_ds)

    def __getitem__(self, i):
        Xi = self.train_ds[i]
        yi = self.val_ds[i]
        return self.transform(Xi, yi)
```

So `Xi` should be your features and `yi` should be your target. Instead, your `Xi` is data from your train dataset and your `yi` is data from your validation dataset. Please create two different Datasets, one for train and one for val instead.

With the current code, if your train dataset is larger than your val dataset, the line `yi = self.val_ds[i]` will raise an `IndexError`. That might be your error.

**Comment by BayuSasongko** [comment]
cannot success. same error. my xi (train dataset) more large from yi (validation dataset). help me please
![error](https://user-images.githubusercontent.com/17606892/63662151-9a344380-c7e7-11e9-9722-dcc4114bc142.png)

**Comment by BenjaminBossan** [comment]
You are giving too little context to really judge this.

First of all, if you want to do `GridSeachCV`, you don't need a separate validation dataset because `GridSearchCV` will take the job of splitting train from valid.

Second, as mentioned above, you are using the dataset wrong. The two returned values should be X and y (features and targets), not train and validation.

Please try to wrap your `train_ds` in a `SliceDatasetX` and pass that to `GridSearchCV`.

**Comment by BayuSasongko** [comment]
```
data_dir = 'b_cancer_data2'
nThreads = 4
use_gpu = torch.cuda.is_available()
train_transforms = transforms.Compose([
     transforms.RandomRotation(30),
        transforms.RandomResizedCrop(224),
        #transforms.ColorJitter(brightness=0.4, contrast=0.4, saturation=0.4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
val_transforms = transforms.Compose([
    transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

train_ds = datasets.ImageFolder(
    os.path.join(data_dir, 'train'), train_transforms)
val_ds = datasets.ImageFolder(
    os.path.join(data_dir, 'valid'), val_transforms)
class MyDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
        
    def __len__(self):
        return len(self.X)
        
    def __getitem__(self, i):
        Xi = self.X[i]
        yi = self.y[i]
        return self.transform(Xi, yi)

ds = MyDataset(train_ds, val_ds)

class SliceDatasetX(Dataset):

    def __init__(self, dataset, collate_fn=default_collate):
        self.dataset = dataset
        self.collate_fn = collate_fn

        self._indices = list(range(len(self.dataset)))
        
    def __len__(self):
        return len(self.dataset)
     
    def shape(self):
        return len(self),
    
    def __getitem__(self, i):
        if isinstance(i, (int, np.integer)):
            Xb = self.transform(*self.dataset[i])[0]
            return Xb
        if isinstance(i, slice):
            i = self._indices[i]
        Xb = self.collate_fn([self.transform(*self.dataset[j])[0] for j in i])
        return Xb
net = NeuralNetClassifier(
    PretrainedModel, 
    criterion=nn.CrossEntropyLoss,
    batch_size=4,
    max_epochs=10,
    lr=0.1,
    iterator_train__shuffle=True,
    verbose=False,
    train_split=None,
    callbacks=[lrscheduler, checkpoint, freezer],
    device='cuda' # comment to train on cpu
)
from sklearn.model_selection import GridSearchCV

params = {
    'lr': [0.01, 0.02],
    'max_epochs': [10, 20]
}
y_slice_ds = SliceDatasetX(train_ds)
gs = GridSearchCV(net, params, refit=False, cv=3, scoring='accuracy')
y_from_ds = np.asarray([y_slice_ds[i][1] for i in range(len(ds))])
ds_sliceable = SliceDatasetX(y_from_ds)
gs.fit(ds_sliceable, y_from_ds)
```
![Untitled](https://user-images.githubusercontent.com/17606892/63734913-4e959e80-c8a8-11e9-948b-527621b25488.png)

Im Newbie in Python. Stuck in this. help me find the way with more example sir

**Comment by BayuSasongko** [comment]
In other way im using RandomSampling for normalize my data :
But this is error, different error.
![error1](https://user-images.githubusercontent.com/17606892/63750323-75b79480-c8d7-11e9-8c33-2e40ad273e7e.png)

**Comment by BenjaminBossan** [comment]
can you try:

```python
from skorch.helper import SliceDataset
X_ds = SliceDataset(train_ds)
y_ds = SliceDataset(train_ds, idx=1)
gs.fit(X_ds, y_ds)
```

**Comment by BayuSasongko** [comment]
my code i changed to :
```
from skorch.helper import SliceDataset
X_ds = SliceDataset(train_ds)
y_ds = SliceDataset(train_ds, idx=1)
params = {
    'lr': [0.01, 0.02],
    'max_epochs': [10, 20]
}
gs = GridSearchCV(net, params, refit=False, cv=3, scoring='accuracy')
gs.fit(X_ds, y_ds)
```
But Cannot Success.
![4](https://user-images.githubusercontent.com/17606892/63989354-3329ce00-cb0a-11e9-92f7-74a22c173faf.png)

**Comment by BenjaminBossan** [comment]
Your module needs some input parameters. You need to pass them like this:

```
net = NeuralNetClassifier(
    PretrainedModel,
    module__output_features=...,
    ...
)
```

**Comment by BayuSasongko** [comment]
Ok thx u , but appear this error
![Untitled1](https://user-images.githubusercontent.com/17606892/64059050-6342a100-cbde-11e9-935f-39db54adb1ee.png)

**Comment by BenjaminBossan** [comment]
Can you remove the `checkpoint` from the callbacks and see if this solves it? I don't think checkpointing makes a lot of sense in a grid search.

**Comment by BayuSasongko** [comment]
can you give me tutorial for save and load model by GridSearchCV.fit ?

**Comment by BenjaminBossan** [comment]
You can get the best model from `gs.best_estimator`, but first you need to fit with `refit=True`.

**Comment by BayuSasongko** [comment]
how to i get the model and save to .pth / pkl file type sir ?

**Comment by BenjaminBossan** [comment]
Refer to the [docs](https://skorch.readthedocs.io/en/stable/user/save_load.html#saving-and-loading).

**Comment by BenjaminBossan** [comment]
If your issue was solved, feel free to close this.

**Comment by BayuSasongko** [comment]
please wait sir

**Comment by BayuSasongko** [comment]
Im using pickle for save model but this is error.

```
# summarize results
print("Best: %f using %s" % (gs.best_score_, gs.best_params_))

# save the model to disk
filename = 'resnet-152_breastcancer.pkl'
pickle.dump(gs, open(filename, 'wb'))
```
![pickle](https://user-images.githubusercontent.com/17606892/64506348-80bfeb00-d301-11e9-8d7c-b9d0cb787908.jpg)

**Comment by BayuSasongko** [comment]
Hi sir.. im using the code :

from skorch.helper import SliceDataset
X_ds = SliceDataset(train_ds)
y_ds = SliceDataset(train_ds, idx=1)
gs.fit(X_ds, y_ds)

Bit this process is very slow. 
maybe how i can use my Dataloader for this is ?

**Comment by BenjaminBossan** [comment]
Pass your dataloader like this:

```python
net = NeuralNetClassifier(
    ...
    iterator_train=MyDataLoader,
    iterator_train__shuffle=True,
    iterator_train__num_workers=8,  # this is how to pass arguments to DataLoader
    iterator_valid=MyDataLoader,
    ...
)
```

**Comment by BenjaminBossan** [comment]
Look at my [comment](https://github.com/skorch-dev/skorch/issues/513#issuecomment-530460726) above. You should pass your `DataLoader` in an uninitialized state. The parameters can be passed using the double-underscore notation.

**Comment by BenjaminBossan** [comment]
@BayuSasongko If your problem was resolved, please feel free to close this issue.
