### ISSUE TITLE
fail to pass test in 0.6.0 release

### ISSUE THREAD

**Issue by hubutui** [skorch-dev/skorch#514]
I'm creating package for ArchLinux, and the build log shows that `skorch/tests/test_classifier.py::TestNeuralNetBinaryClassifier::test_net_learns FAILED`.
To reproduce, you need:
1. ArchLinux environment, such as docker container, with `devtools` installed.
2. download this [PKGBUILD](https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/python-skorch/PKGBUILD), and update the `pkgver` to 0.6.0
3. run `updpkgsums` to update source tarball checksum
4. run `extra-x86_64` to compile and build skorch in a clean chroot environment

The full log is in attachment file.
[log.txt](https://github.com/skorch-dev/skorch/files/3537169/log.txt)

**Comment by BenjaminBossan** [comment]
Hi, I think you attached the wrong log.

Regarding the error, the test is unfortunately stochastic. If you run the tests a couple of times, does it fail every time? If so, can you try to increase the number of flaky runs (e.g. set `@flaky(max_runs=5)` [here](https://github.com/skorch-dev/skorch/blob/8f9f166ace92d1195abd1ba2ec330e9f85da984b/skorch/tests/test_classifier.py#L169)).

**Comment by hubutui** [comment]
@BenjaminBossan Thx, after increasing the number of flaky runs to 5, all tests pass. I need to create and build the package for ArchLinux automatically. Manual change this is not a good choice. Could I somehow pass an arg when compiling? Or would you like to increase it in next release?

**Comment by BenjaminBossan** [comment]
When you leave the number of runs at 3, does it consistently fail? If so, we might need to increase the number of runs or improve the tests.

**Comment by hubutui** [comment]
Yes, I compiled at least 5 times at different machine, with or without GPU, all failed at this test.

**Comment by BenjaminBossan** [comment]
I checked whether the test is too strict but at least on my system, it passes easily:

```python
>>> net.history[:, 'valid_acc']
[0.65, 0.65, 0.685, 0.68, 0.685, 0.715, 0.72, 0.72, 0.75, 0.74, 0.755]
```

Lowering the threshold is probably not a good idea, so increasing the max runs it is. Do you want to make a PR?

**Comment by hubutui** [comment]
@BenjaminBossan Thank you. But it's a minor modification, I think you could fix it in a minute.

**Comment by BenjaminBossan** [comment]
Sure, I just can't test it easily. But I will do it, no problem.

**Comment by thomasjpfan** [comment]
This would be a little better if we can get pytorch to run deterministically: https://github.com/pytorch/pytorch/issues/7068

**Comment by BenjaminBossan** [comment]
AFAICT, we set the corresponding seeds (pytorch and sklearn for the data), not sure what else we can do. Do you know if the seeds should be stable across OSs?

**Comment by thomasjpfan** [comment]
At the end of the discussion https://github.com/pytorch/pytorch/issues/7068#issuecomment-487907668

```py
def seed_torch(seed=1029):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed) # if you are using multi-GPU.
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True
```

this was how they set the random seeds.

**Comment by BenjaminBossan** [comment]
What would be the idea? Having this as a autouse fixture for every test? We could set it only once; however, then tests may still fail if the order changes or only a subset of tests are run.

**Comment by thomasjpfan** [comment]
We have it as a testing util and set it only for the flaky tests?

**Comment by BenjaminBossan** [comment]
@hubutui I made the changes in #515 

@thomasjpfan This is a good idea. For now, I increased the number of runs, since we don't know if your idea would fix the problem. However, we might still want to do this in the future for all flaky tests.
