### ISSUE TITLE
Memory allocation fails when the amount of validation data  is large

### ISSUE THREAD

**Issue by blakeliu** [skorch-dev/skorch#517]
when program run score function

def my_scoring(net, ds, y):
&ensp; &ensp; predicted_logit_masks = net.predict(ds)

**Comment by BenjaminBossan** [comment]
Is this a problem that is specific with skorch or would it also happen in pure pytorch?

You can try decreasing the batch size. Using `predict`, there should only ever be one batch on GPU at a time.

Also, during training, you might have to [turn off caching](https://github.com/skorch-dev/skorch/blob/8cf8f45d91ba3ef0364b8d1ff41e4d695762fcac/skorch/callbacks/scoring.py#L291) for your scoring callbacks if your validation data is too large.

Apart from that, I can hardly help you with this little information.

**Comment by blakeliu** [comment]
@BenjaminBossan Thanks！

**Comment by BenjaminBossan** [comment]
If your problem was solved, please close the issue, otherwise report back.
