### ISSUE TITLE
Expectation when cloning a net

### ISSUE THREAD

**Issue by BenjaminBossan** [skorch-dev/skorch#521]
At the moment, when we use `sklearn.base.clone` on a fitted net, we receive a fitted net. In sklearn, however, we get back an unfitted estimator. The main reason is that out `net.get_params()` also returns learned attributes (ending on `_`, like `module_`).

For sklearn compliance, we might want to change this behavior. However, I wonder if this can have some unintended side-effects are might break backwards-compatibility for too many people (say, making it so that old pickle files no longer work?).

**Comment by BenjaminBossan** [comment]
One possibility I could imagine: We don't change the behavior of `get_params` yet, only prepare everything for the eventual change. Then, after the next release, we change `get_params` to be more in line with what sklearn does.

Unfortunately, it's not really possible to slap a deprecation warning onto `get_params`. I would be afraid that it would trigger too many false positives. Instead, we have to make clear in the release text that the change will happen and what users need to do to prepare for it, then hope they read it. I believe we should encourage using `copy.deepcopy` for the purpose instead of `clone`.

Overall, most people shouldn't be affected by the change, but I can imagine it leads to some surprising bugs, as many are not even aware when `get_params` is actually used under the hood (e.g. for grid search).

**Comment by thomasjpfan** [comment]
I agree with being compatible with the sklearn api of `clone`.

> making it so that old pickle files no longer work?

I do not think pickling will be affected by this change. Pickling serializes all the attribute regardless of how `get_params` work.

> as many are not even aware when get_params is actually used under the hood (e.g. for grid search).

Since grid search calls `fit`, even with the fitted net it will restarted from the beginning. If a user sets `warm_start=True` or passes in a module instance, I would say the grid search will give false results, since the training is continuing where the last parameter has left off.

**Comment by BenjaminBossan** [comment]
> Since grid search calls `fit`, even with the fitted net it will restarted from the beginning. If a user sets `warm_start=True` or passes in a module instance, I would say the grid search will give false results, since the training is continuing where the last parameter has left off.

That would be my biggest worry with the current situation, especially since it's not easy to notice.

> I do not think pickling will be affected by this change. Pickling serializes all the attribute regardless of how `get_params` work.

Pickling will probably not be a problem but still some code could break because of the change.
