### ISSUE TITLE
[BUG] TrainEndCheckpoint not working with LoadInitState

### ISSUE THREAD

**Issue by YannDubs** [skorch-dev/skorch#528]
I'm trying to use `TrainEndCheckpoint` with `LoadInitState` but it's not working. It doesn't even return any error as you are using `with suppress(Exception)`. The suppressed error is `*** AttributeError: 'TrainEndCheckpoint' object has no attribute 'f_history_'`, yet the file exists and `self.checkpoint.checkpoint_.f_history_==.../train_end_history.json'`.

I think the issue is that `TrainEndCheckpoint` stopped inheriting from `Checkpoint` in #463. I.e. it doesn't have a `f_history_` attribute anymore. This could be simply resolved by redirecting `self.f_history_` to `self.checkpoint_.f_history_`.

**Comment by BenjaminBossan** [comment]
Thank you very much for this detailed investigation. We will look into this.
