### ISSUE TITLE
Why does it use only one fixed validation in Kfold?

### ISSUE THREAD

**Issue by rightx2** [skorch-dev/skorch#539]
`skorch.dataset.CVSplit` said,

```
However, instead of cycling through all splits, only one fixed split (the first one) is used.
``` 

Is there any reason? Can't understand why it has to use only 1 fold even when 5 is given as cv split.

**Comment by githubnemo** [comment]
I don't think there is a very clever reason. The purpose of `CVSplit` is to provide validation data while re-using sklearn's CV infrastructure and we chose this way of implementing exactly that. Therefore, the number of folds is just a proxy for specifying the train/valid ratio.

If you think that defining a host of validation sets and cycling through them is a good idea, we are happy to hear you out!

**Comment by BenjaminBossan** [comment]
See my response here: https://github.com/skorch-dev/skorch/pull/540#issuecomment-535132966

**Comment by ottonemo** [comment]
I think the main issue here is that it is unclear how to do early stopping while doing cross-validation. This will be handled in https://github.com/skorch-dev/skorch/issues/544.
