### ISSUE TITLE
Provide 'dummy proof' examples on how to do both cross validation and early stopping

### ISSUE THREAD

**Issue by ottonemo** [skorch-dev/skorch#544]
Quoting the detailed request:
---
Are there any complete 'dummy proof' examples or tutorials on how to do both cross validation and early stopping? 
I have a skorch dataset and I want to be able to use cross validation for it, but I haven't found much information out there to do this, or it gets into a complicated mess with the dataset.

``` python
import numpy as np
import torch
from ICNN.module import ICNNModule
from ICNN.dataset import ICNNDataset
from skorch import NeuralNetBinaryClassifier
from skorch.dataset import CVSplit
from skorch.callbacks import EarlyStopping
from sklearn.model_selection import cross_val_score

net = NeuralNetBinaryClassifier(ICNNModule,
                          max_epochs=200,
                          lr=0.01,
                          callbacks=[EarlyStopping(patience=25)],
                          batch_size=16,
                          optimizer=torch.optim.SGD,
                          optimizer__momentum=0.90,
                          train_split=CVSplit(cv=10,stratified=True,random_state=0))


ds = ICNNDataset("data/icnn.csv")
y_train = np.array([y for X, y in iter(ds)])
net.fit(ds, y_train)
```
This is what I have so far, but I would like to have all out of fold scores. I'm new to skorch and any help would be greatly appreciated. Thanks!

_Originally posted by @ivanpmartell in https://github.com/skorch-dev/skorch/pull/540#issuecomment-540215814_

**Comment by BenjaminBossan** [comment]
@ivanpmartell

```python
import numpy as np
from sklearn.datasets import make_classification
from skorch import NeuralNetClassifier
from skorch.callbacks import EarlyStopping
from skorch.dataset import Dataset
from skorch.toy import make_classifier
from sklearn.model_selection import cross_validate
import torch

np.random.seed(0)
torch.manual_seed(0)

X, y = make_classification(random_state=0)
X = X.astype(np.float32)
ds = Dataset(X, y)
y = np.array([y for _, y in iter(ds)])

net = NeuralNetClassifier(
    make_classifier(),
    lr=1,
    max_epochs=100,
    callbacks=[EarlyStopping()],
    # consider setting verbose=0
)

scores = cross_validate(net, X, y, scoring='accuracy', cv=5)
```

Here is an example that uses `cross_validate` together with `EarlyStopping`. `cross_validate` will make sure that all data is used for training and for validation.

Of course, the training data will be split internally by skorch so that part of it can be used for early stopping. The net thus doesn't train on that part of the data. However, you should still consider this data to be part of the "training set" because it is actually used for training -- to decide when to stop it. Therefore, it is not an independent validation set and shouldn't be treated as such. Otherwise, you would run into the risk of data leakage.

**Comment by ivanpmartell** [comment]
Thank you for this @BenjaminBossan !
I've been using the Checkpoint callback, but I was wondering if it could be used in this scenario.
How would you go about having a different checkpoint folders for every fold? Is it possible without too much hassle?

**Comment by BenjaminBossan** [comment]
So I hope that solved your original issue.

Regarding the issue with the checkpoint: I believe this is indeed not possible right now. As a quick fix, I would suggest this:

`Checkpoint` has the `get_formatted_files` method that returns the filenames. You could have a global counter that is increased each time a net is fitted and then modify the filename in said method based on that counter. It could look somewhat like this:

```python
counter = 0

class MyNet(...):
    def fit(self, X, y, **fit_params):
        global counter
        counter += 1  # increase the counter with each fit call
        return super().fit(X, y, **fit_params)

class MyCheckpoint(Checkpoint):
    def get_formatted_files(self, *args, **kwargs):
        files_dict = super().get_formatted_files(*args, **kwargs)
        # add code to modify the values of the dict using "counter"
        return files_dict
```

This is just the first thing that came to my head, maybe others have better ideas. If so, we could think about integrating them into the existing callbacks.

**Comment by thomasjpfan** [comment]
One can use the id of the data: (It will be different in each split in cross_validate)

```py
class MyCheckpoint(Checkpoint):
	def on_train_begin(self, net, X, y, **kwargs):
		self.fn_prefix = id(X)
```

I do not think we should support this officially tho.

**Comment by BenjaminBossan** [comment]
> One can use the id of the data: (It will be different in each split in cross_validate)

Good idea. You can then use the timestamp of the saved parameters to identify which fold they belong to.

> I do not think we should support this officially tho.

I agree that we don't need a solution to this specific problem. However, I wonder if we can somehow make the naming more flexible, e.g. by allowing to pass a callable that returns the actual file name.

**Comment by ivanpmartell** [comment]
@BenjaminBossan Oh yes thank you so much!
I don't think I have access to close the issue as I'm not the one who originally created it.

**Comment by BenjaminBossan** [comment]
> I don't think I have access to close the issue as I'm not the one who originally created it.

Yeah I forget. @ottonemo is this good enough or do we need something like an FAQ entry?

**Comment by BenjaminBossan** [comment]
I will close this for now, since the question has been answered. If there are any questions left, feel free to re-open.

**Comment by iCHAIT** [comment]
@BenjaminBossan 

I am trying to accomplish something similar and have a question.  It would be great if you can help me understand this.

When I implement `cross_validate` why are the scores returned from `cross_validate` different from the `valid_acc`

Here is the code - 

```python

class NeuralNet(nn.Module):
    def __init__(self, num_units=512, nonlin=F.relu, dropout=0.5,):
        super(NeuralNet, self).__init__()
        self.num_units = num_units
        self.nonlin = nonlin
        self.dropout = dropout

        self.dense0 = nn.Linear(2048, num_units)
        self.nonlin = nonlin
        self.dropout = nn.Dropout(dropout)
        self.dense1 = nn.Linear(num_units, 128)
        self.output = nn.Linear(128, 2)
        
        
    def forward(self, X, **kwargs):
        X = self.nonlin(self.dense0(X))
        X = self.dropout(X)
        X = F.relu(self.dense1(X))
        X = F.softmax(self.output(X), dim=-1)
        return X

net = NeuralNetClassifier(
    NeuralNet,
    max_epochs = 15,
    lr = 0.02,
    callbacks=[EarlyStopping()],
 
)


scores = cross_validate(net, X, y, scoring='accuracy', cv=5)
```


Here are the results -

```
epoch    train_loss    valid_acc    valid_loss     dur
-------  ------------  -----------  ------------  ------
      1        0.6520       0.6562        0.6115  0.0084
      2        0.6071       0.6562        0.5680  0.0085
      3        0.5630       0.7188        0.5244  0.0078
      4        0.5111       0.8906        0.4847  0.0078
      5        0.4703       0.9844        0.4408  0.0082
      6        0.4315       1.0000        0.4052  0.0086
      7        0.3995       1.0000        0.3663  0.0078
      8        0.3477       1.0000        0.3201  0.0077
      9        0.3175       0.9844        0.2939  0.0085
     10        0.2823       0.9844        0.2622  0.0077
     11        0.2507       0.9844        0.2275  0.0085
     12        0.2214       0.9844        0.1931  0.0082
     13        0.2003       0.9844        0.1694  0.0082
     14        0.1729       1.0000        0.1423  0.0082
     15        0.1469       0.9844        0.1258  0.0082
  epoch    train_loss    valid_acc    valid_loss     dur
-------  ------------  -----------  ------------  ------
      1        0.6687       0.6406        0.6256  0.0077
      2        0.6129       0.6406        0.5828  0.0078
      3        0.5845       0.6406        0.5443  0.0088
      4        0.5453       0.6875        0.5021  0.0088
      5        0.5021       0.9062        0.4576  0.0076
      6        0.4683       0.9375        0.4141  0.0079
      7        0.4276       0.9375        0.3710  0.0084
      8        0.3863       0.9375        0.3315  0.0080
      9        0.3599       0.9531        0.2980  0.0076
     10        0.3298       0.9531        0.2661  0.0082
     11        0.2978       0.9531        0.2383  0.0081
     12        0.2634       0.9531        0.2140  0.0081
     13        0.2225       0.9531        0.1921  0.0081
     14        0.2152       0.9531        0.1745  0.0075
     15        0.1746       0.9531        0.1603  0.0078
  epoch    train_loss    valid_acc    valid_loss     dur
-------  ------------  -----------  ------------  ------
      1        0.6655       0.6406        0.6186  0.0076
      2        0.6160       0.6406        0.5762  0.0077
      3        0.5765       0.6406        0.5391  0.0077
      4        0.5429       0.7500        0.4967  0.0077
      5        0.5186       0.9219        0.4559  0.0077
      6        0.4771       0.9375        0.4143  0.0083
      7        0.4307       0.9375        0.3712  0.0086
      8        0.3926       0.9531        0.3304  0.0079
      9        0.3564       0.9688        0.2936  0.0077
     10        0.3241       0.9688        0.2578  0.0080
     11        0.2877       0.9688        0.2300  0.0076
     12        0.2545       0.9688        0.2037  0.0077
     13        0.2271       0.9844        0.1826  0.0078
     14        0.2034       0.9688        0.1646  0.0084
     15        0.1721       0.9688        0.1499  0.0080
  epoch    train_loss    valid_acc    valid_loss     dur
-------  ------------  -----------  ------------  ------
      1        0.6942       0.6406        0.6297  0.0078
      2        0.6169       0.6406        0.5842  0.0086
      3        0.5747       0.6406        0.5349  0.0084
      4        0.5284       0.8125        0.4841  0.0078
      5        0.4864       0.9062        0.4360  0.0077
      6        0.4525       0.9375        0.3892  0.0079
      7        0.3898       0.9531        0.3468  0.0078
      8        0.3589       0.9688        0.3084  0.0083
      9        0.3141       0.9844        0.2733  0.0082
     10        0.2707       0.9844        0.2412  0.0083
     11        0.2341       0.9844        0.2151  0.0082
     12        0.2124       0.9844        0.1895  0.0085
     13        0.1840       0.9844        0.1715  0.0077
     14        0.1579       0.9844        0.1561  0.0076
     15        0.1392       0.9844        0.1440  0.0075
  epoch    train_loss    valid_acc    valid_loss     dur
-------  ------------  -----------  ------------  ------
      1        0.6487       0.6406        0.6071  0.0074
      2        0.5937       0.6406        0.5659  0.0084
      3        0.5642       0.7188        0.5276  0.0083
      4        0.5241       0.8438        0.4892  0.0076
      5        0.4896       0.9219        0.4490  0.0076
      6        0.4391       0.9375        0.4080  0.0077
      7        0.3872       0.9375        0.3685  0.0082
      8        0.3603       0.9531        0.3299  0.0077
      9        0.3184       0.9844        0.2945  0.0082
     10        0.2773       0.9844        0.2614  0.0078
     11        0.2405       0.9844        0.2339  0.0082
     12        0.2186       0.9844        0.2088  0.0077
     13        0.1923       0.9844        0.1886  0.0077
     14        0.1547       0.9844        0.1712  0.0085
     15        0.1467       0.9844        0.1565  0.0086
```

and here is the output of `scores` from the above code - 


Output - 

```

>>> scores

{'fit_time': array([0.15866137, 0.15415931, 0.15254354, 0.15443516, 0.15276504]),
 'score_time': array([0.0031395 , 0.00242114, 0.00233197, 0.00213099, 0.0022583 ]),
 'test_score': array([0.9875, 0.975 , 0.9875, 1.    , 1.    ])}
```


I am not sure how is the `test_accuracy` computed here and why is it not concordant with the scores from any of the epochs for either fold?

**Comment by BenjaminBossan** [comment]
When you call `cross_validate` with `cv=5`, sklearn will split the data into 5 folds. Then it will train on 4 of the 5 and validate on the held out data (5 times). After sklearn passes 4/5th of the data as training data to `net.fit`, skorch will in turn split off part of that data (also 4/5th by default) for skorch-internal training and hold out 1/5th for skorch-internal validation.

For this reason, the skorch-internal validation scores (the ones you see printed when calling `net.fit`) are based on a _different_ hold out set than the ones shown by `cross_validate`.

In a sense, these two perform a very similar function, which is why we recommend to turn off skorch-interval validation (`net = NeuralNetClassifier(..., train_split=False)`) when validation is already covered by sklearn. But in cases like yours where you need early stopping, you can't do that. Still, you could turn off the print log (`net = NeuralNetClassifier(..., verbose=0)`) so as to avoid confusion. The sklearn values should be the ones to pay attention to.

**Comment by iCHAIT** [comment]
Thanks for the clarification @BenjaminBossan. Makes sense now 👍

**Comment by ivanpmartell** [comment]
cross_validate with a skorch dataset and the y values doesn't seem to work for me anymore. 
e.g.:
```
cross_validate(net, ds, y, scoring=scorer, cv=2)
```
whereas it works for skorch's fit:
```
net.fit(ds, y)
```

I get the error:
```
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
```

I believe this cross_validate code used to work, but not anymore. This is for a neuralnetclassifier

Also all the examples I see are using an X and a y numpy variables. What if the training data is too big to hold on X? This doesn't seem to make sense to me as skorch datasets seem to not work on sklearn functions anymore for me. Please let me know what I'm doing wrong. Thanks!

**Comment by BenjaminBossan** [comment]
@ivanpmartell Could you check whether [this](https://skorch.readthedocs.io/en/stable/user/FAQ.html#how-do-i-use-sklearn-gridseachcv-when-my-data-is-in-a-dataset) solves your problem?
