### ISSUE TITLE
Integrating Model Pruning and Quantization on Skorch  

### ISSUE THREAD

**Issue by katakissof** [skorch-dev/skorch#548]
Hello,
I would like to ask if skorch provides functionalities for optimizing the model footprint in memory and in speed as here https://github.com/NervanaSystems/distiller for example. 
If not are you planning to add such functionalities ?

Based on your experience which would be the best way to add them in your current interface because I need it for a project.

Thanks

**Comment by BenjaminBossan** [comment]
I haven't looked at distiller yet, so I really can't comment on that. From your question, I collect that you might have a suggestion. If so, please post it. In general, a good idea could be to start with the API for how you would like to use distiller with skorch and then we can see 1) if it could work and 2) if it's in scope for skorch.

**Comment by BenjaminBossan** [comment]
@katakissof Did you make any progress on this issue?

**Comment by katakissof** [comment]
@benjamin-work Yes I managed to integrate an example. Thank you, you can close the issue.

**Comment by BenjaminBossan** [comment]
@katakissof Sounds great. If you could share the example, we could evaluate if it's in scope for skorch to integrate this, otherwise you can close this issue.
