### ISSUE TITLE
Progress bar on score or predict

### ISSUE THREAD

**Issue by ivanpmartell** [skorch-dev/skorch#549]
Is it possible to have the ProgressBar() callback, or any callback work when calling predict? I believe all callbacks right now only work when training. I have to predict a huge dataset and am trying to find a way to get a tqdm progress bar to gauge the amount of time it's going to take.

**Comment by BenjaminBossan** [comment]
That's indeed a good idea. Until there is an official solution, you could change this line:

https://github.com/skorch-dev/skorch/blob/79b1c70fbf0b58e8f615f06e02c1bad81a0dbfe7/skorch/net.py#L911

to:

```python
        for data in tqdm.tqdm(iterator, total=<TOTAL-NUMBER-OF-ITERATIONS>):
```

I.e., subclass your neural net class's `forward_iter` method, copy paste the current code and modify this single line.

**Comment by ottonemo** [comment]
A slightly cleaner solution might be to provide `tqdm` as iterator for `iterator_valid`:

```python
def tqdm_iterator(dataset, **kwargs):
    return tqdm.tqdm(DataLoader(dataset, **kwargs))

net = NeuralNet(
    module, 
    iterator_valid=tqdm_iterator,
)
```

This has the obvious drawback that it will print the progress bar during fit as well.
@BenjaminBossan this is another argument for having a separate evaluation loop (separated from validation).

To circumvent this:
```python
def tqdm_iterator(dataset, **kwargs):
    return tqdm.tqdm(DataLoader(dataset, **kwargs))

net = NeuralNet(
    module, 
)
net.fit(X, y)
net.set_params(iterator_valid=tqdm_iterator)
net.predict(X)
```

**Comment by BenjaminBossan** [comment]
> A slightly cleaner solution might be to provide `tqdm` as iterator for `iterator_valid`

nice idea

> this is another argument for having a separate evaluation loop (separated from validation).

I won't oppose it if someone offers a good and clean implementation ;)

**Comment by githubnemo** [comment]
@ivanpmartell did this solve your issue?

**Comment by BenjaminBossan** [comment]
I will close this issue for now. @ivanpmartell if you still have questions, feel free to re-open.
