### ISSUE TITLE
Tensorboard import error

### ISSUE THREAD

**Issue by herozero777** [skorch-dev/skorch#550]
Code:
`from skorch.callbacks import Tensorboard`                                

ImportError: cannot import name 'Tensorboard' from 'skorch.callbacks' (/home/teemo/anaconda3/envs/pytor/lib/python3.7/site-packages/skorch/callbacks/__init__.py)

pyhton = 3.7.3
skorch = 0.6.0
tf = 2.0.0
tensorboard = 2.0.0

**Comment by BenjaminBossan** [comment]
The `Tensorboard` callback is not actually released yet. If you want to use it, you need to install skorch from source, as described [here](https://github.com/skorch-dev/skorch#from-source).

**Comment by herozero777** [comment]
Okay Thanks for the help.
