### ISSUE TITLE
How to give model validation data when i want do cross-validation and save each model?

### ISSUE THREAD

**Issue by sakuranew** [skorch-dev/skorch#551]
default parameter is **train_split=CVSplit(5)**
```python
skf = StratifiedKFold(n_splits=3)
for train, test in skf.split(X, y):
     validation_x=X[test]
```
How can i just give model the validation data **validation_x** rather than a **CVSplit(5)**
maybe i can do this by adding a callback and set train_split=None ,but it's too inconvenient

**Comment by sakuranew** [comment]
in keras , the fit function have parameter **validation_data**

**Comment by sakuranew** [comment]
> If you split your data by using train_test_split(), you can create your own skorch Dataset, and then pass it to predefined_split():


I find the solution

**Comment by BenjaminBossan** [comment]
If you have no further question, feel free to close the issue.
