### ISSUE TITLE
Bug: Error in Basic Usage Example

### ISSUE THREAD

**Issue by elouden** [skorch-dev/skorch#554]
When following the example notebook provided [here](https://nbviewer.jupyter.org/github/skorch-dev/skorch/blob/master/notebooks/Basic_Usage.ipynb), there is an error with the Neural Net Classifier.

RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target'

**Comment by thomasjpfan** [comment]
I am unable to see an error when running through the whole notebook in colab: https://colab.research.google.com/github/skorch-dev/skorch/blob/master/notebooks/Basic_Usage.ipynb

In which section are you seeing the error?

**Comment by elouden** [comment]
I see it in cell 10, when I call net.fit(x,y).  
Just tried it in google colab - and you're right, there's no error.

I was trying to run the code in a local jupyter notebook, I'll check and see if I have an older version of a package.

**Comment by elouden** [comment]
I created a new virtual environment with python 3.7 and installed pyTorch & Skorch.  Now running torch version 1.3.1, and skorch 0.6.0
I still see the same error regarding the scalar type for target.  
Any suggestions for how to get this working properly in my local environment?

**Comment by BenjaminBossan** [comment]
Just to make sure, you're not working on a 32 bit system, are you?

Could you tell us the dtype of `y`? If it's not int64, can you cast to int64?

**Comment by elouden** [comment]
It is a 64-bit system (Windows 10)

dtype of y is 'int34', cating to int64 fixes the problem.

Thank you!

**Comment by thomasjpfan** [comment]
I am open to explicitly casting in the example.

**Comment by BenjaminBossan** [comment]
> dtype of y is 'int34'

I hope it's int32 :)

> I am open to explicitly casting in the example.

Me too. Still strange why that happened. If someone else has Windows 10, maybe they could try to replicate.

**Comment by elouden** [comment]
yes, sorry :) int32

**Comment by BenjaminBossan** [comment]
@elouden Could you try this:

```python
from sklearn.datasets import make_classification
X, y = make_classification(1000, 20, n_informative=10, random_state=0)
print(X.dtype)
```

If you want to, you could also add the PR to fix the dtype issue.

**Comment by elouden** [comment]
running X.dtype -> I see 'float64'

FYI this seems to be an annoying quirk of Windows machines
https://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine#36279549

I could not find a way to adjust the default dtype.  When I was actually trying to build my own code and I wanted to use sklearn's Pipeline and the TextFeaturizer from dstoolbox, it was necessary to add the dtype transformation as part of the Pipeline.  
![image](https://user-images.githubusercontent.com/36549370/68607126-ed7c7080-047d-11ea-9c81-962b9e960745.png)

I'm not sure how many windows users are anticipated, but it could be useful to highlight this problem somewhere in the documentation.

**Comment by BenjaminBossan** [comment]
Thanks for investigating further, I learned something new today.

Even though this problem is not really skorch-specific, it would probably still make sense to document it somewhere. I will think where best to put it. If you have any suggestion, feel free to share it.

**Comment by sakuranew** [comment]
```python
import numpy as np
from torch.utils.data import DataLoader,Dataset
class a(Dataset):
    def __init__(self):
        self.x=np.asarray([1,2,3])
    def __len__(self):
        return 3
    def __getitem__(self, item):
        return self.x[item]

x=a()
l=DataLoader(x,batch_size=2)
v=next(l.__iter__())
print(v.dtype)
```
In torch=1.3,the result is torch.int32
In torch=1.2,the result is torch.int64
```python
self.x=np.asarray([1,2,3],dtype=np.int64)
```
this may fix this problem

**Comment by BenjaminBossan** [comment]
@sakuranew I tried this with torch==1.3.1 and get torch.int64.

**Comment by sakuranew** [comment]
@BenjaminBossan  maybe the numpy version ,i test on my pc and server
```python
import numpy as np
x=np.asarray([1,2,3])
print(np.__version__)
print(x.dtype)

1.16.5
int32

1.17.4
int64
```

**Comment by BenjaminBossan** [comment]
I'm on Ubuntu 18.04.3

```python
import sys
import numpy as np
x=np.asarray([1,2,3])
print(sys.version)
print(np.__version__)
print(x.dtype)
```

numpy 1.16.5:

```
3.7.5 (default, Oct 25 2019, 15:51:11) 
[GCC 7.3.0]
1.16.5
int64
```

numpy 1.17.4

```
3.7.5 (default, Oct 25 2019, 15:51:11) 
[GCC 7.3.0]
1.17.4
int64
```

Skimming over the [release notes of numpy](https://docs.scipy.org/doc/numpy/release.html), I can't find anything that would indicate such a change (but I also don't find a note for 1.16.5!).
