### ISSUE TITLE
`TestNeuralNet.test_train_net_after_copy` fails on ArchLinux with python 3.8

### ISSUE THREAD

**Issue by hubutui** [skorch-dev/skorch#559]
I'm trying to create package for ArchLinux, python upgraded to 3.8 recently, and skorch fails to pass the test. Here is the complete build log: [python-skorch.log](https://github.com/skorch-dev/skorch/files/3850361/python-skorch.log).
To reproduce:
1. An ArchLinux environment with `devtools` installed.
2. download [PKGBUILD](https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/python-skorch/PKGBUILD).
3. run `extra-x86_64-build`.

**Comment by BenjaminBossan** [comment]
Those are some strange errors. However, we don't officially support Python 3.8 yet, since some dependencies don't. If this changes, we will also start supporting 3.8. Before that, I can't help you any further.

**Comment by BenjaminBossan** [comment]
Is this still happening?

**Comment by hubutui** [comment]
@benjamin-work yes, here is the latest [build log](https://github.com/skorch-dev/skorch/files/5396968/log.txt)

**Comment by BenjaminBossan** [comment]
Thanks for reporting. The errors have changed, though, now it seems that pandas is not installed. Could you provide a link to the build script so that I can take a look?

**Comment by hubutui** [comment]
@BenjaminBossan Thanks, I install `pandas`, and now I could build it and pass all the tests.
