### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging' after installing skorch

### ISSUE THREAD

**Issue by NasGit3** [skorch-dev/skorch#577]
I recently installed skorch package. I installed it in a conda virtual environment using the installation guidance with conda:

```
    git clone https://github.com/skorch-dev/skorch.git
    cd skorch
    python setup.py install
```
However, when I run *import skorch* it throws me the packaging error:
   ` ModuleNotFoundError: No module named 'packaging'
`
I followed the solution suggested in this [page][2], but I still get the error. I have python 3.7.5 installed under this conda environment and I didn't get this error before installing skorch. 
 

  [1]: https://github.com/skorch-dev/skorch
  [2]: https://gist.github.com/hangtwenty/b9820fe204eebb0cc5b9aba49f3c8b22

**Comment by BenjaminBossan** [comment]
Does `conda install packaging` help?

Otherwise, can you install skorch from pip? We had a very recent release, so installing from source gives you almost no additional features.

**Comment by BenjaminBossan** [comment]
@NasGit3 any progress?

**Comment by NasGit3** [comment]
Thank you for your reply! I used "conda install -c conda-forge skorch" after I posted this issue and it worked.  Unfortunately, I didn't get to try your solution.

**Comment by BenjaminBossan** [comment]
Okay, great that you found a solution.
