### ISSUE TITLE
Attribute error when calling .classes_ on a loaded NeuralNetClassifier

### ISSUE THREAD

**Issue by SdgJlbl** [skorch-dev/skorch#582]
Hello, 

I am not sure if I'm doing something wrong, if it is the intended behaviour or a bug. 

The context:
I'm training a `NeuralNetClassifier` on some data, after using the `fit` method I can access the classes on which it was trained with the `classes_` attribute. 
I am then saving it and loading it again with the recommended `save_params` and `load_params` methods. 
On the newly loaded object, trying to access the `classes_` attribute gives the following traceback : 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-25e182b6b60b> in <module>
----> 1 new_net.classes_

~/miniconda3/envs/doc_classif/lib/python3.7/site-packages/skorch/classifier.py in classes_(self)
    109                     self.__class__.__name__))
    110             return self.classes
--> 111         return self.classes_inferred_
    112 
    113     # pylint: disable=signature-differs

AttributeError: 'NeuralNetClassifier' object has no attribute 'classes_inferred_'
```

As I said, not sure if it's the intended behaviour or not. 

Minimal reproducible example (inspired from the basic tutorial) available here :
https://gist.github.com/SdgJlbl/3fd51950ae4902277a5ebc50515e1e12

**Comment by ottonemo** [comment]
Thanks for reporting!

This is at least surprising behavior, so I'll label it as a bug for now. Indeed, `save_params` only saves the torch state dictionaries (model state, optimizer state) with the only exception being the history. This is problematic for parameters such as `classes_` which is inferred during training time. We need to discuss whether `save_params` should save such attributes or if it is out of scope.

As a workaround, consider using `pickle` instead which will do the same thing as `save_params` but will also save class attributes such as `classes_`.

**Comment by BenjaminBossan** [comment]
That's a difficult one. On the one hand, I agree that this could be unexpected. On the other hand, if we start persisting all kinds of attributes of the net during `save_params`, we actually end up re-implementing pickle and jeopardize compatibility (e.g. the `classes_` attribute was only introduced recently).

My suggestion would be to improve the documentation instead. We could even think about some nice error message for cases like the one above (though it's not quite easy to guess all possible cases). Anyway, it should be crystal clear that `save_params` is _only_ for the pytorch components and that pickle should be used for everything else.

**Comment by SdgJlbl** [comment]
I understand that this is an edge case; there is this dissonance between "oh sure save_params is just a wrapper around the PyTorch method" and "but if all my weights are saved, my network for sure knows how many neurons there are in my softmax layer". And to be honest, the Exception was not what I would have expected, but I understand how tricky it can be to determine the exact context that triggers a given exception. 

FYI, I was considering the idea of using `save_params` instead of pickle because there were stuffs in my callbacks I didn't want to pickle, but I removed my callbacks before pickling instead :)

**Comment by thomasjpfan** [comment]
> My suggestion would be to improve the documentation instead. 

Would the documentation say to "use pickle"? There is a use case of wanting the `NeuralNet` of just being a scikit-learn compatible estimator, used only for inference, thus not needing the callbacks. In this case, we tell users to manually remove the callbacks before pickling.

We can also have the documentation state that "set the `classes_`" manually.

**Comment by BenjaminBossan** [comment]
> I understand that this is an edge case

Out of curiosity, why did you want to access the `classes_` attribute on your model?



> "but if all my weights are saved, my network for sure knows how many neurons there are in my softmax layer"

Your model still knows it. In theory, we could do without the `classes_` attribute, it's not needed for training or predicting. However, some sklearn functions require it, which is why we added it recently.

> because there were stuffs in my callbacks I didn't want to pickle

You could also override the `__getstate__` method (which is used by pickle) on those callbacks and remove the offending attributes. It depends on your use case.

> We can also have the documentation state that "set the `classes_`" manually.

Yes, we should do that. Also, we might consider preparing a list of attribute names that might get lost during `save_params` and to raise a nice error message when `__getattr__` is called with any of them.

**Comment by SdgJlbl** [comment]
I am using the `classes_` attribute of my model to do some sanity checks (I am using ensembles of PyTorch and sklearn classifiers, and skorch is just perfect for this use case); another use-case is to map the numerical labels to human-friendly class names (eg in plots). Neither use-cases is absolutely necessary, but that attribute provides definitely some nice syntactic sugar. 

I didn't know about the `__getstate__` method, I'll check it out, thanks for the tip. 

As a end-user, I think that at least a mention in the documentation that using the `save_params` method will lose sklearn-like attributes, would be very helpful to make the right call when choosing a persistence method.

**Comment by BenjaminBossan** [comment]
@SdgJlbl I updated the docs in #585. Would this have helped you?

The PR does not include the discussed addition of error messages.

**Comment by SdgJlbl** [comment]
That would have been very helpful indeed. 
Thanks for taking the issue into account, and for all the great work on skorch! 👍

**Comment by BenjaminBossan** [comment]
@SdgJlbl The update to the docs has been merged. If you find further issues, feel free to re-open this.
