### ISSUE TITLE
how can I declare RNN/LSTM for regression?

### ISSUE THREAD

**Issue by nidhaloff** [skorch-dev/skorch#583]
It may sound like a simple task but I ve been struggling with this for two weeks. I'm working on a regression problem, I know how to use pytorch, I switched to skorch because it is amazing, I love the work you did guys but I didn't find a proper way to use LSTM since it always throws an error if I return two values in the forward function (predictions and hidden states) or when I initialize hidden states with zeros and then run my model on GPU. here is my declaration of the LSTM

```
 class LstmNetwork(nn.Module):

    def __init__(self, n_features, n_lstm_hidden=16, n_fc_hidden=64, n_out=2, num_layers=1, bi=False, dropout=0.0):
        super().__init__()

        self.n_features = n_features
        self.n_lstm_hidden = n_lstm_hidden
        self.n_fc_hidden = n_fc_hidden
        self.n_out = n_out
        self.num_layers = num_layers
        self.bi = bi
        self.dropout = dropout
        self.hidden_cell = self.init_hidden()

        self.lstm = nn.LSTM(
            input_size=self.n_features,
            hidden_size=self.n_lstm_hidden,
            num_layers=self.num_layers,
            bidirectional=self.bi,
            dropout=self.dropout)

        self.fc = nn.Linear(
            in_features=n_fc_hidden,
            out_features=n_out
        )

    def init_hidden(self):

        return (torch.zeros(1, 1, self.n_lstm_hidden),
                torch.zeros(1, 1, self.n_lstm_hidden))

    def forward(self, x):
        # I found this example on internet, but there is no initialisation for hidden states here, I tried to 
       # initialize hidden states as stated above but it throws an error when I run it on GPU
     # also I thought that we should also return the hidden states in the forward function in pytorch but 
    # if I do that here I get an Error.
    # I'm not sure if my declaration is correct, can someone help?
        out, hn = self.lstm(x)
        out = self.fc(out)
        return out
```

there are many examples on the internet about word embedding and NLP but I don't need that, my task is actually simpler, I just want to do regression like predicting hourse prices for example. In my declaration I'm not sure if my forward function is correct, I should initialize the hidden states as zeros but if I pass it to the self.lstm then it throws an error when I run it on GPU. also I can't return the hidden states in the forward function with the prediction output as in pytorch because skorch throws an error. Can someone explain to me how would the lstm work in skorch and help me on this?

**Comment by BenjaminBossan** [comment]
Thanks for your kind words, we appreciate that.

Generally, when you encounter errors, it's very helpful if you can post the error message and the full stacktrace.

When it comes to simple regression/classification tasks with RNNs, be sure to have a look at [this example](https://github.com/skorch-dev/skorch/blob/master/examples/rnn_classifer/RNN_sentiment_classification.ipynb). As to how to return multiple values from your `forward` method, please have a look at the [FAQ](https://skorch.readthedocs.io/en/stable/user/FAQ.html#how-can-i-deal-with-multiple-return-values-from-forward).

> it always throws an error if ... I initialize hidden states with zeros and then run my model on GPU

To me, this doesn't sound like a skorch error. Do you get the same error with pure pytorch? Could it be that your hidden state is not on GPU? If so, send it to the GPU before using it.

**Comment by BenjaminBossan** [comment]
@nidhaloff Any updates on this issue?

**Comment by BenjaminBossan** [comment]
Since I haven't heard back from you, @nidhaloff, I'll assume the issue was fixed. Re-open if it's not the case.
