### ISSUE TITLE
Sklearn cross_val_score for Tensor Dataset/ Dataloader

### ISSUE THREAD

**Issue by rudra0713** [skorch-dev/skorch#588]
Hi,
  I am trying to use the cross_val_score() function for my input. Before trying skorch, My preprocessing function would return `f_inputs, f_masks, f_labels` (each of them is a torch.tensor), then I would use the Dataloader class in the following manner:
`train_data = TensorDataset(f_inputs, f_masks, f_labels)
  train_sampler = RandomSampler(train_data)
  train_dataloader = DataLoader(train_data, sampler=train_sampler, batch_size=batch_size)
`
Finally, I used to iterate over train_dataloader which was a tuple of those 3 (f_inputs, f_masks, f_labels) and pass them to the forward() function of my model. 

Now, I am trying to use cross_validation for my model. Therefore, I decided to use sklearn.cross_val_score().
When I tried the train_data variable as input(X) for cross_val_score(), it is giving me an error
`TypeError: take(): argument 'index' (position 1) must be Tensor, not numpy.ndarray`
I think, the reason this does not work because according to sklearn, X   "Can be for example a list, or an array" as input. I am not sure how to proceed from here. Any help will be greatly appreciated.

**Comment by BenjaminBossan** [comment]
You're correct, sklearn won't let you pass pytorch `Dataset`s or `DataLoader`s directly. Can you try the following:

* wrap your `TensorDataset` inside `skorch.helper.SliceDataset`
* don't use `DataLoader`, this is handled by skorch
* if you only want to shuffle your training data, also let skorch handle this: `net = skorch.NeuralNet(..., iterator_train__shuffle=True)`

In addition it might be necessary to pass `y` values to sklearn directly. I assume that your `f_labels` are your targets. If the above doesn't work, try to move `f_labels` outside the dataset. Maybe it's just an array of values? Then pass it separately to the function: `cross_val_score(net, X=my_dataset, y=f_labels, ...)`.

**Comment by rudra0713** [comment]
Hi, thanks for your suggestion. Using SlideDataset instead of TensorDataset does help me go on a little bit more but it seems that I cannot pass a tuple of two variables via X (for my case, they would be f__inputs and f_masks, and you are right, f_labels are the 'y' values). I am working with a toy example right now, if this works properly, then I will try to use skorch for my main task.

first, I defined a custom Dataset class.
`
    class MyDataset(torch.utils.data.Dataset):

    def __init__(self, X_1, X_2):
        super(MyDataset, self).__init__()
        self.X_1 = X_1
        self.X_2 = X_2

    def __len__(self):
        return len(self.X_1)

    def __getitem__(self, index):
        return self.X_1[index], self.X_2[index]`

Then, 
`
key_a = np.random.random((100, 10)).astype(np.float32) 
key_b = np.random.random((100, 20)).astype(np.float32)

key_a = torch.from_numpy(key_a)
key_b = torch.from_numpy(key_b)

y = np.random.randint(0, 2, size=100)
X = MyDataset(key_a, key_b)

X = SliceDataset(X)

logistic = NeuralNetClassifier(MyModule, max_epochs=1, lr=1e-2, train_split=None)
scores = cross_val_score(logistic, X, y, cv=2, scoring="accuracy")
`
But inside the forward() of MyModule, it only gets the first variable of X, not the second one. How can I solve this issue? Previously, this used to be taken care of by the Dataloader class.

**Comment by BenjaminBossan** [comment]
I think for your case, putting your data into a dictionary might be the better choice. Look at [this section](https://skorch.readthedocs.io/en/stable/user/dataset.html#id1) of the docs for an example.

To use the dict with sklearn's `cross_val_score`, wrap it into a `skorch.helper.SliceDict`.

Btw, you can pass numpy arrays directly, no need for converting to torch tensors.

**Comment by rudra0713** [comment]
Thanks. SliceDict solved the issue.
