### ISSUE TITLE
NeuralNetClassifier defaults to train_split=CVSplit, but train/validation splitting is already handled by GridSearchCV when using it

### ISSUE THREAD

**Issue by joshuacwnewton** [skorch-dev/skorch#599]
(I want to preface by saying thank you for developing skorch! I've found it very useful. I appreciate the hard work you've put into developing this library.)

skorch=0.7.0
scikit-learn=0.22.1

My starting code, for context. (src here: https://github.com/joshuacwnewton/swift_classification/blob/master/swift_classification/cnn/__main__.py)

```
    net = NeuralNetClassifier(
        TwoClassSqueezeNet,
        criterion=nn.CrossEntropyLoss,
        batch_size=args.batch_size,
        max_epochs=args.num_epochs,
        module__num_classes=args.num_classes,
        optimizer=optim.SGD,
        iterator_train__shuffle=True,
        iterator_train__num_workers=args.num_workers,
        iterator_valid__shuffle=True,
        iterator_valid__num_workers=args.num_workers,
        device='cuda',
        # train_split = None  # (Uncomment for fix to bug)
    )

    params = {
            'optimizer__lr': [1e-5, 1e-4, 1e-3],
            'optimizer__momentum': [0.5, 0.9, 0.99, 0.999],
            'optimizer__nesterov': [True, False]
        }
    gs = GridSearchCV(net, params, refit=False, cv=3, scoring='accuracy',
                      verbose=3)

    # SliceDataset used because train_set is a custom PyTorch dataset
    X_sl = SliceDataset(train_set, idx=0)  # idx=0 is the default
    y_sl = SliceDataset(train_set, idx=1)

    gs.fit(X_sl, y_sl)
```

For this code, when `net` is created, the NeuralNetClassifier constructor defaults to `self.train_split=CVSplit` with `CV=5` because train_split was not provided. CVSplit isn't actually necessary, though, because training/validation splitting is already handled by scikit-learn (see snippet below).

```
# Snippet from sklearn/model_selection/_validation.py/_fit_and_score()
# This is called during GridSearchCV.
# train/test are indices created by StratifiedKFold, again within GridSearchCV

    X_train, y_train = _safe_split(estimator, X, y, train)
    X_test, y_test = _safe_split(estimator, X, y, test, train)

    try:
        if y_train is None:
            estimator.fit(X_train, **fit_params)
        else:
            estimator.fit(X_train, y_train, **fit_params)
```

If I run the original code, NeuralNetClassifier tries to apply CVSplit to the SliceDatasets during estimator.fit. It does so here:

```
# Snippet from skorch/net.py/NeuralNet/get_split_datasets()
# This is called during fit_loop()

        dataset = self.get_dataset(X, y)
        if self.train_split:
            dataset_train, dataset_valid = self.train_split(
                dataset, y, **fit_params)
        else:
            dataset_train, dataset_valid = dataset, None
```

When self.train_split is called here, the program crashes. _(The reason it crashes has to do with an attempted conversion from SliceDataset -> numpy. I don't think the exact reason is critical here, though, because CVSplit probably shouldn't be performed in the first place.)_

To fix this and get GridSearchCV to run as expected, I had to explicitly set `train_split=None` (see "Fix for bug" in original code). This allows the splitting be taken care of by GridSearchCV, then everything works as expected.

I didn't see `train_split=None` in the docs for grid search, here: https://nbviewer.jupyter.org/github/skorch-dev/skorch/blob/master/notebooks/Basic_Usage.ipynb#Performing-a-grid-search 

What do you think of my fix? Is this intended?

**Comment by BenjaminBossan** [comment]
Good observation. It's true that `train_split` should be set to False or None in the linked notebook. If you want to, please create a PR to fix this. Also, the docs should probably mention this prominently.

As to whether train split should always be deactivated in grid search: Not necessarily, sometimes you might still need it, e.g. when using early stopping. Furthermore, there is no easy way for skorch to turn it off during a grid search because skorch doesn't know that a grid search is being performed.

Finally, the crash: This is a bug and should be fixed.

I didn't check the code but I suspect that it would work if `y` was a numpy array. If that's indeed the reason, you could try to turn off stratification (`train_split=CVSplit(..., stratified=False)`) to make it work (I think). Otherwise, we have a tough time because the stratification is performed by sklearn, which assumes `y` to be numpy-array-like. skorch should, however, raise a more helpful error message if this occurs (again, if you'd like to, you could create a PR for this).

**Comment by joshuacwnewton** [comment]
Thank you so much for taking the time to write such a detailed response. I am (relatively) new to software engineering/machine learning as I'm just a senior undergraduate student, so your comments are very helpful for my understanding. :)

I have never contributed to an open-source project before, so I am a bit nervous to create PRs. I am curious to try, though. Hopefully I will have time in between my course work!

**Comment by BenjaminBossan** [comment]
> Thank you so much for taking the time to write such a detailed response.

You're welcome!

> I'm just a senior undergraduate student

No reason to be shy ;) You did a great job at identifying the underlying issue.

> I have never contributed to an open-source project before, so I am a bit nervous to create PRs

I would encourage you to go ahead once you have time. We will do our best to help you guide through the process should you encounter any problem.

From a technical point of view, you might want to read about [creating forks](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) and then about [creating PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by BenjaminBossan** [comment]
@joshuacwnewton Are you still willing to work on this?

**Comment by joshuacwnewton** [comment]
Hi @BenjaminBossan! Thanks for checking in. :)

My ability to contribute has been severely affected by the coronavirus outbreak. (Not to get too deep into personal matters, of course.) Right now, I'm trying to limit my commitments to the bare minimum, as I don't feel confident that I'll be able to follow through if I make new promises.

I'm still very curious about contributing to skorch, though. I hope that I will be able to once things become less hectic for me. I hope you are doing alright, as well!

**Comment by BenjaminBossan** [comment]
I'm doing fine, thanks. Stay safe as well.
