### ISSUE TITLE
Dataparallel not working 

### ISSUE THREAD

**Issue by soulhi-vz** [skorch-dev/skorch#602]
Hi,
The code below works only on one GPU. Other GPUs are not used.
Please advise.

torch.cuda.device_count()
>16

net = MyNet(
    module=Autoencoder,
    max_epochs=500,
    batch_size=100,
    lr=learning_rate,
    criterion=torch.nn.MSELoss,
    optimizer=torch.optim.Adam,
    iterator_train__shuffle=True,
    callbacks = [skorch.callbacks.EarlyStopping(monitor='valid_loss', patience=10, threshold=0.0001)],
    device=device,
)

model_mg = torch.nn.DataParallel(net, device_ids=range(torch.cuda.device_count()))

model_mg.module.fit(df_n, df_n);

Thanks
/Said

**Comment by BenjaminBossan** [comment]
I've never used `DataParallel` and have no setup to test it, thus I can't debug your code. However, I can see in your code that it can't work this way. `DataParallel` wraps the pytorch module, not the net.

You could try something like this, although, as I said, I can't test it and you might run into further trouble:

```python
def get_autoencoder(
        module,
        device_ids=range(torch.cuda.device_count()),
        output_device=None,
        dim=0,
        **kwargs
):
    return torch.nn.DataParallel(
        module=module(**kwargs),
        device_ids=device_ids,
        output_device=output_device,
        dim=dim,
    )

net = MyNet(
    module=get_autoencoder,
    max_epochs=500,
    batch_size=100,
    lr=learning_rate,
    criterion=torch.nn.MSELoss,
    optimizer=torch.optim.Adam,
    iterator_train__shuffle=True,
    callbacks = [skorch.callbacks.EarlyStopping(monitor='valid_loss', patience=10, threshold=0.0001)],
    device=device,
)

net.fit(df_n, df_n)
```

**Comment by soulhi-vz** [comment]
Hi Benjamin,
Thanks for your prompt answer. Your fix works! 
Thanks
/Said

**Comment by BenjaminBossan** [comment]
Very nice. I'll close the issue, re-open if there are further errors.
