### ISSUE TITLE
GridSearch on multi-classes classification task

### ISSUE THREAD

**Issue by 7ianwo0o** [skorch-dev/skorch#609]
Hallo,
I am using Skorch on multi-classes task. This is my code right now.

> `#------------Logistic regression------------------
class Neuralnetwork(nn.Module):
    def __init__(self,in_dim=128,out_dim=7):
        super(Neuralnetwork,self).__init__()
        self.dense = nn.Linear(in_dim,out_dim)
    def forward(self,x):
        x = self.dense(x)
        # res = F.log_softmax(x, dim=-1).max(1)[1]
        res = F.softmax(x)
        return res

> torch.manual_seed(0)
net_ins = Neuralnetwork()
net = NeuralNetClassifier(
                        module=net_ins,
                        max_epochs=200,
                        verbose=1,
                        )
param_grid = {'lr': [0.001, 0.01, 0.1, 1, 10, 100, 1000] }
clf = GridSearchCV(net, param_grid, verbose=1)
x_trian, y_train = x.numpy().astype(np.float32),y.numpy().reshape(-1,1).astype(np.int64)
clf.fit(x_trian,y_train)
`

But i got an error

  File "/usr/local/lib/python3.7/site-packages/skorch/net.py", line 1099, in get_loss
    return self.criterion_(y_pred, y_true)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 209, in forward
    return F.nll_loss(input, target, weight=self.weight, ignore_index=self.ignore_index, reduction=self.reduction)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/functional.py", line 1871, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: multi-target not supported at ../aten/src/THNN/generic/ClassNLLCriterion.c:20`

So i want to know how can i fix it ? What i did wrong ? Thanks

**Comment by BenjaminBossan** [comment]
Hi,

The error message says it:

> RuntimeError: multi-target not supported at ../aten/src/THNN/generic/ClassNLLCriterion.c:20`

You have multiple classes but `NLLLoss` does not support multiple classes. This is not really related to skorch, you would encounter the same problem with pure pytorch.

[Here](https://discuss.pytorch.org/t/what-kind-of-loss-is-better-to-use-in-multilabel-classification/32203) is a discussion about what could be done but let me make another proposal:

```python
class MultiClassNLLLoss(torch.nn.NLLLoss):
    def forward(self, input, target):
        num_outputs = input.shape[1]
        assert num_outputs == target.shape[1]

        loss = 0
        for i in range(num_outputs):
            loss += super().forward(input[:, i], target[:, i])

        return loss

net = NeuralNetClassifier(..., criterion=MultiClassNLLLoss)
```

The code isn't tested but I hope you understand what's happening: iterate over each output, thus treating each output as a separate classification, and sum up the individual losses.

**Comment by BenjaminBossan** [comment]
@7ianwo0o any updates?

**Comment by BenjaminBossan** [comment]
Since there hasn't been any follow-up for a month, I'll assume that answer worked. Please re-open if that's not true.
