### ISSUE TITLE
How to correctly using NeuralNet baseclass (training seems good, but prediction gone wrong)

### ISSUE THREAD

**Issue by drr3d** [skorch-dev/skorch#618]
Hi..thx for beautiful works.

currently i learn and trying to use this module to implement this [Autoencoders](https://github.com/shaharazulay/adversarial-autoencoder-classifier/blob/master/source/_train_semi_supervised.py) network on skorch.

this is some part of my code:
```
class AdversarialAutoencoders(nn.Module):
    def __init__(self, encoder, decoder, discriminator_cat, discriminator_gauss, **kwargs):
        super().__init__()
        self.encoder = encoder(**params_for('encoder', kwargs))
        self.decoder = decoder(**params_for('decoder', kwargs))     # Encoder/Decoder
        self.discriminator_cat = discriminator_cat(**params_for('discriminator_cat', kwargs))
        self.discriminator_gauss = discriminator_gauss(**params_for('discriminator_gauss', kwargs))
    
    def zero_grad_all(self, *models):
        [m.zero_grad() for m in models]

    def forward(self, X, target=None):
        if target is not None:
            if target[0] == -1:
                labeled = False
            else:
                labeled = True
        else:
            labeled = True
                
        X.resize_(X.shape[0], self.encoder.input_size)
        
        X_noisy = add_noise(X)

        X, X_noisy, target = Variable(X), Variable(X_noisy), Variable(target)
        if cuda:
            X, X_noisy, target = X.cuda(), X_noisy.cuda(), target.cuda()
        
        loss=D_loss=G_loss = None
        
        if not labeled:
            #######################
            # Reconstruction phase
            #######################
            latent_vec = torch.cat(self.encoder(X_noisy), 1)
            X_rec = self.decoder(latent_vec)

            #######################
            # Discriminator phase
            #######################
            self.encoder.eval()
            
            z_real_cat = sample_categorical(X.shape[0], n_classes=n_classes)
            z_real_gauss = Variable(torch.randn(X.shape[0], z_dim))
            if cuda:
                z_real_cat = z_real_cat.cuda()
                z_real_gauss = z_real_gauss.cuda()

            z_fake_cat, z_fake_gauss = self.module_.encoder(X)

            D_real_cat = self.discriminator_cat(z_real_cat)
            D_real_gauss = self.discriminator_gauss(z_real_gauss)
            D_fake_cat = self.discriminator_cat(z_fake_cat)
            D_fake_gauss = self.discriminator_gauss(z_fake_gauss)

            #######################
            # Generator phase
            #######################
            self.module_.encoder.train()
            z_fake_cat, z_fake_gauss = self.module_.encoder(X)

            D_fake_cat = self.module_.discriminator_cat(z_fake_cat)
            D_fake_gauss = elf.module_.discriminator_gauss(z_fake_gauss)
            pred = D_fake_cat
        
        #######################
        # Semi-supervised phase
        #######################
        if labeled:
            pred, _ = self.encoder(X)
                
        return pred

class Trainer(skorch.NeuralNet):
    def __init__(self, *args, 
        optimizer_autoencoder=optim.Adam, 
        optimizer_G=optim.Adam,
        optimizer_D=optim.Adam,
        optimizer_classifier=optim.Adam,
        epsilon = np.finfo(float).eps,
        **kwargs):
        
        self.optimizer_autoencoder = optimizer_autoencoder
        self.optimizer_G = optimizer_G
        self.optimizer_D = optimizer_D
        self.optimizer_classifier = optimizer_classifier
        self.epsilon=epsilon
        self.old_state_dict = {}

        super().__init__(*args, **kwargs)
        
    def initialize_optimizer(self):
        kwargs = self._get_params_for('optimizer_autoencoder')
        self.optimizer_autoencoder_ = self.optimizer_autoencoder(itertools.chain(self.module_.encoder.parameters(),
                                                                                 self.module_.decoder.parameters()),
                                                                 **kwargs)
        
        kwargs = self._get_params_for('optimizer_G')
        self.optimizer_G_ = self.optimizer_G(self.module_.encoder.parameters(), **kwargs)
        
        kwargs = self._get_params_for('optimizer_D')
        self.optimizer_D_ = self.optimizer_D(itertools.chain(self.module_.discriminator_gauss.parameters(),
                                                             self.module_.discriminator_cat.parameters()), 
                                             **kwargs)
        
        kwargs = self._get_params_for('optimizer_classifier')
        self.optimizer_classifier_ = self.optimizer_classifier(self.module_.encoder.parameters(), 
                                                               **kwargs)
    
    def zero_grad_all(self, *models):
        [m.zero_grad() for m in models]

    def train_step_all(self, *optima):
        [m.step() for m in optima]

    def get_loss(self, y_pred, y_true, **kwargs):
        return F.cross_entropy(y_pred, y_true)
    
    def evaluation_step(self, Xi, training=False):
        self.check_is_fitted()
        with torch.set_grad_enabled(training):
            self.module_.train(training)
            return self.infer(Xi)
    
    def initialize(self):
        """Initializes all components of the :class:`.NeuralNet` and
        returns self.

        """
        self.initialize_virtual_params()
        self.initialize_callbacks()
        self.initialize_criterion()
        self.initialize_module()
        self.initialize_optimizer()
        self.initialize_history()

        self.initialized_ = True
        
        for key in self.module_.state_dict():
            self.old_state_dict[key] = self.module_.state_dict()[key].clone()
        
        return self
    
    def train_step(self, X, target=None):
        # set to training mode
        self.module_.train()

        if target[0] == -1:
            labeled = False
        else:
            labeled = True
        
        y_pred = self.infer(X)
        loss = self.get_loss(y_pred, target)
        loss.backward()
        
        if not labeled:
            self.train_step_all(self.optimizer_autoencoder_,
                                self.optimizer_D_,
                                self.optimizer_G_)
        else:
            self.optimizer_classifier_.step()
        
        self.zero_grad_all(self.optimizer_autoencoder_,
                           self.optimizer_D_,
                           self.optimizer_G_,
                           self.optimizer_classifier_)

        return {'loss': loss, 'y_pred': y_pred}
    
    def monitorTrain(self):
        ### for monitoring if there is update on network learning weight
        # Save new params
        new_state_dict = {}
        for key in self.module_.state_dict():
            new_state_dict[key] = self.module_.state_dict()[key].clone()

        # Compare params
        for key in self.old_state_dict:
            if not (self.old_state_dict[key] == new_state_dict[key]).all():
                print('Diff in {}'.format(key))

    def _predict(self, X):
        pred_labels = []
        i=0
        for yp in self.forward_iter(X, training=False):
            pred_labels.append(torch.argmax(yp, dim=1))
        pred_label = np.concatenate(pred_labels, 0)
        return pred_label
            
    def predict(self, X):
        X.resize_(X.shape[0], self.module_.encoder.input_size)
        X = Variable(X)
        return self._predict(X)
```

this is how i initialize the trainer:
```
trainer = Trainer(
    criterion=torch.nn.NLLLoss,
    
    # We extended the trainer to support two optimizers
    # but to get the behavior of one optimizer we can 
    # simply use SGD for both, just like in the tutorial.
    optimizer_autoencoder = torch.optim.Adam,
    #optimizer_encoder__lr = 0.01,
    optimizer_G = torch.optim.Adam,
    #optimizer_decoder__lr = 0.02,
    optimizer_D = torch.optim.Adam,
    #optimizer_discriminator__lr = 0.03,
    optimizer_classifier = torch.optim.Adam,
    
    module = AdversarialAutoencoders,

    module__encoder = Q_net,
    module__encoder__input_size=X_dim,
    module__encoder__n_classes=z_dim,
    module__encoder__in_hidden_size=in_features,
    module__encoder__out_hidden_size=out_features,
    module__decoder=P_net,
    module__decoder__input_size=X_dim,
    module__decoder__n_classes=z_dim,
    module__decoder__in_hidden_size=in_features,
    module__decoder__out_hidden_size=out_features,
    module__discriminator_gauss=D_net_gauss,
    module__discriminator_gauss__z_size=2,
    module__discriminator_gauss__in_hidden_size=in_features,
    module__discriminator_gauss__out_hidden_size=out_features,
    module__discriminator_cat= D_net_cat,
    module__discriminator_cat__n_classes=z_dim,
    module__discriminator_cat__in_hidden_size=in_features,
    module__discriminator_cat__out_hidden_size=out_features,

    # We have no internal validation.
    train_split=None,
    
    # The decoding code is not meant to be batched
    # so we have to deal with a batch size of 1 for
    # both training and validation/prediction.
    iterator_train__batch_size=train_batch_size,
    iterator_valid__batch_size=valid_batch_size,
    
    # We are training only one large epoch.
    max_epochs=3,
    
    # Training takes a long time, add a progress bar
    # to see how far in we are. Since we are doing 
    # grid search with cross-validation splits and the
    # total amount of batches_per_epoch varies, we set
    # the batches_per_epoch method to 'auto', instead 
    # of the default, 'count'.
    callbacks=[
        skorch.callbacks.ProgressBar(batches_per_epoch='auto'),
    ],
    
    device=('cuda' if use_cuda else 'cpu'),
    verbose=100,
)

trainer.fit(X_train, y_train)
```

this is some information about training
![skorch_ask](https://user-images.githubusercontent.com/6335497/79555697-363df280-80ca-11ea-94be-db0a2e015e53.png)

![skorch_2](https://user-images.githubusercontent.com/6335497/79555812-61284680-80ca-11ea-866f-e344e5547a1e.png)

i just wonder, it seems the training are going well (or not) and the weight were updated (or not), but when it came into validation:
```
y_pred_net = trainer.predict(X_test)
```
gave me quite bad results:
![skorch_3](https://user-images.githubusercontent.com/6335497/79556032-b2383a80-80ca-11ea-8efd-220a60eeaeb3.png)

this how i generate the data:
```
dl = DataLoader(MNIST(os.getcwd(), train=True, download=False))

tensor = dl.dataset.data
tensor = tensor.to(dtype=torch.float32)
tr = tensor.reshape(tensor.size(0), -1) 
tr = tr/128
targets = dl.dataset.targets
targets = targets.to(dtype=torch.long)

X_train = tr[0:50000]
y_train = targets[0:50000]
X_test = tr[50000:60000]
y_test = targets[50000:60000]
```

what am i missing here?

Note:
---
I tried basic module for that AutoEncoders and all things going well, got 96% acc using that dataset, when i try to reproduce that incorect prediction result(reimplementation on skorch) using that basic module, that behavior is happening when i'm not doing(by disabling) the `optimizer.step()`

this is what happen when i try to disable that step:
![skorch_4](https://user-images.githubusercontent.com/6335497/79557078-26271280-80cc-11ea-9323-d4ed4d1645d8.png)
as u can see, the weigh are not updated(thats why there is no difference between parameters on initialize and after training finished)

**Comment by BenjaminBossan** [comment]
Hi

> thx for beautiful works

Thanks :) I see that you used some advanced features of skorch, nice to see.

So first of all a general comment: Adversarial training in skorch is currently not as nice as it could be, as discussed in #593. For that reason, PR #596 and #597 are in the works. If these are merged, the code should be a bit easier to use. You can have a look at [this notebook](https://github.com/skorch-dev/skorch/blob/feature-facilitate-customization-of-net/notebooks/dcgan.ipynb) to see how DCGAN could be implemented with the changes.

One big difference to your code is that you're basically calculating the loss inside of the `forward` method of the module, which makes it necessary to have code that branches on whether -- and what -- target is passed. Maybe this could be cleaned up and moved to the `train_step` instead.

Some questions I have at first glance:

* When is `target[0] == -1` ever true? Are some of your samples unlabeled?
* AFAICT, `D_fake_gauss` and `D_fake_cat` are never used
* Could you show your code for the `encoder` module?

Overall, it's quite hard for me to see through all the things that are happening, it would take me much more time to understand all of it. Perhaps, you could refactor the code a bit, inspired by the linked notebook, which could clear a few things up.

From what I can gather, your classifier should be trained to correctly predict the multi-class classification task (targets from 0..9) and you expect it to be better during validation (it's basically predicting random). However, I don't see why you would expect that. During training, there seems to be hardly any progress in the loss, so I wasn't surprised to see that validation gives random output.

> I tried basic module for that AutoEncoders and all things going well, got 96% acc using that dataset

What exactly did you do here? Are you using the exact same hyper-parameters?

> when i try to reproduce that incorect prediction result(reimplementation on skorch) using that basic module, that behavior is happening when i'm not doing(by disabling) the `optimizer.step()`

If I understand you correctly, you're saying that if you use the module with pure PyTorch and disable module updates, you get the same results? Again, this is what I would expect, given that the train loss hardly moved at all.

Minor comments:

* in `predict`, you do `X.resize_`, i.e. you mutate the incoming data -- `predict` should not have any side effects though; ideally, you should also not mutate X during fit
* you use `Variable` but that is only necessary in very old PyTorch versions (which are not officially supported anymore)
* `if cuda:` in `forward`: shouldn't be necessary with skorch

**Comment by drr3d** [comment]
Hi.. thx for very fast response.. :)

> So first of all a general comment: Adversarial training in skorch is currently not as nice as it could be, as discussed in #593. For that reason, PR #596 and #597 are in the works. If these are merged, the code should be a bit easier to use. You can have a look at this notebook to see how DCGAN could be implemented with the changes.

ic thx for the info, i'll take a look on that notebooks. 

> When is target[0] == -1 ever true? Are some of your samples unlabeled?

yes, my current real case only have fewer labels than MNIST, but there is -1 label, -1 label is label provided by checker team, in sort, i handle fraud datasets, and some label are corrected by another team(human of course :D), when those team feel uncertain about label belong to what class, they just put on -1

> AFAICT, D_fake_gauss and D_fake_cat are never used

correct for this case, because all MNIST dataset that i use, contain no -1 label

> One big difference to your code is that you're basically calculating the loss inside of the forward method of the module, which makes it necessary to have code that branches on whether -- and what -- target is passed. Maybe this could be cleaned up and moved to the train_step instead.

i think i have wrote the loss calculation on `train_step()` rit?
```
def train_step(self, X, target=None):
        # set to training mode
        self.module_.train()

        if target[0] == -1:
            labeled = False
        else:
            labeled = True
        
        y_pred = self.infer(X)
        loss = self.get_loss(y_pred, target)
        loss.backward()
```

before this, i also have tried to put all forward method on `AdversarialAutoencoders` into `Trainer(NeuralNet)`, but the result are the same, still got very low prediction results.

> What exactly did you do here? Are you using the exact same hyper-parameters?
If I understand you correctly, you're saying that if you use the module with pure PyTorch and disable module updates, you get the same results? Again, this is what I would expect, given that the train loss hardly moved at all.

yes i use the exact same hyper-params.
yap, on pure PyTorch code with disable condition on the `optimizer.step()` method, i've got the same result(low score on val) as on Skorch code that i place above with `optimizer.step()` is running.

f.y.i: on pure PyTorch implementation also give me hard to move loss values, and the difference is really not much from Skorch implementation, around `+- 2.1` too. but both of them have decreasing  loss value on each epoch.

so all i can think now is:
1. i write wrong implementation on Skorch.
2. if there is a chance somehow when training is on going, on each `train_step()` iteration execute, all the parameter resets to initial condition? (if this happen i think when training is finished, the module seems only seen 1 batch of data?)

> Minor comments:

good point, i'll try

ok, mate! i'll take a look on notebook that u give me, and i'll put the result again here..

Cheers,
~ stay safe ~

**Comment by drr3d** [comment]
Hi mate,

i think i figure it out whats the problem is,
first i try to modify my code like u show me in ur notebook, so now it will become like this:
```
class AdversarialAutoencoders(nn.Module):
    ...
    ...
    def forward(self, X, target=None):
        X = X.unsqueeze(0)
        return self.encoder(X)

class AAETrainer(skorch.NeuralNet):
    ...
    ... 
    def train_step(self, X, target):
        # set to training mode
        self.module_.train()
        
        if target[0] == -1:
            labeled = False
        else:
            labeled = True
                
        X.resize_(X.shape[0], self.module_.encoder.input_size)
        
        X_noisy = add_noise(X)

        if cuda:
            X, X_noisy, target = X.cuda(), X_noisy.cuda(), target.cuda()
        
        loss=D_loss=G_loss = None

        if not labeled:
            #######################
            # Reconstruction phase
            #######################
            latent_vec = torch.cat(self.module_.encoder(X_noisy), 1)
            X_rec = self.module_.decoder(latent_vec)

            recon_loss = F.binary_cross_entropy(X_rec + epsilon, X + epsilon)
            recon_loss.backward()
            
            self.optimizer_autoencoder_.step()
            
            self.zero_grad_all(self.module_.encoder,
                               self.module_.decoder,
                               self.module_.discriminator_cat,
                               self.module_.discriminator_gauss)

            #######################
            # Discriminator phase
            #######################
            self.module_.encoder.eval()
            
            z_real_cat = sample_categorical(X.shape[0], n_classes=n_classes)
            z_real_gauss = Variable(torch.randn(X.shape[0], z_dim))
            if cuda:
                z_real_cat = z_real_cat.cuda()
                z_real_gauss = z_real_gauss.cuda()

            z_fake_cat, z_fake_gauss = self.module_.encoder(X)

            D_real_cat = self.module_.discriminator_cat(z_real_cat)
            D_real_gauss = self.module_.discriminator_gauss(z_real_gauss)
            D_fake_cat = self.module_.discriminator_cat(z_fake_cat)
            D_fake_gauss = self.module_.discriminator_gauss(z_fake_gauss)

            D_loss_cat = - torch.mean(torch.log(D_real_cat + epsilon) + torch.log(1 - D_fake_cat + epsilon))
            D_loss_gauss = - torch.mean(torch.log(D_real_gauss + epsilon) + torch.log(1 - D_fake_gauss + epsilon))

            D_loss = D_loss_cat + D_loss_gauss
            D_loss.backward()
            
            self.optimizer_D_.step()

            # Init gradients
            self.zero_grad_all(self.module_.encoder,
                               self.module_.decoder,
                               self.module_.discriminator_cat,
                               self.module_.discriminator_gauss)

            #######################
            # Generator phase
            #######################
            self.module_.encoder.train()
            z_fake_cat, z_fake_gauss = self.module_.encoder(X)

            D_fake_cat = self.module_.discriminator_cat(z_fake_cat)
            D_fake_gauss = self.module_.discriminator_gauss(z_fake_gauss)

            G_loss = - torch.mean(torch.log(D_fake_cat + epsilon)) - torch.mean(torch.log(D_fake_gauss + epsilon))
            G_loss.backward()
            
            self.optimizer_G_.step()
            
            # Init gradients
            self.zero_grad_all(self.module_.encoder,
                               self.module_.decoder,
                               self.module_.discriminator_cat,
                               self.module_.discriminator_gauss)
        
        #######################
        # Semi-supervised phase
        #######################
        if labeled:
            y_pred, _ = self.module_.encoder(X)
            loss = F.cross_entropy(y_pred, target)
            loss.backward()
            
            self.optimizer_classifier_.step()

            self.zero_grad_all(self.module_.encoder,
                               self.module_.decoder,
                               self.module_.discriminator_cat,
                               self.module_.discriminator_gauss)
                
        return {'G_loss': G_loss, 'D_loss': D_loss, 'loss': loss, 'y_pred': y_pred}

    def forward_iter(self, X, training=False, device='cpu'):
        for data in X:
            yp = self.evaluation_step(data, training=training)
            yield yp
           
    def predict(self, X):
        pred_labels = []

        for yp in self.forward_iter(X, training=False):
            pred_labels.append(torch.argmax(yp[0], dim=1))
        
        pred_label = np.concatenate(pred_labels, 0)
        
        return pred_label
```

the dumb thing i did was:
1. MNIST has 784 features, and i set it into 768 features on training (my bad..sorry)
2. you were right about not to resize input data on prediction, my last code before this i did resize so the input will have dim `768 x 768`. but if im not resizing the input data on prediction, it will produce size error, and since im using the `BatchNorm1d()` layer for encoder, here is the [solutions](https://discuss.pytorch.org/t/batchnorm1d-valueerror-expected-2d-or-3d-input-got-1d-input/42081), then i do little change to squeze the tensor on `forward()`

and now all is good:
loss
![skorch_isgood_1](https://user-images.githubusercontent.com/6335497/79628958-9cc91c00-816f-11ea-9b2b-b7c9e5310083.png)

accuracy
![skorch_isgood_2](https://user-images.githubusercontent.com/6335497/79628962-a18dd000-816f-11ea-9f30-91b9553a8c9c.png)

thx for the help :+1: 
~keep up the good works. ~

**Comment by BenjaminBossan** [comment]
Nice that you found a solution that works so quickly. I hope that the adversarial training part also does what it's supposed to do. If you have no further question, feel free to close the issue.

Overall, I think that this shows that we really need an official example of adversarial training in skorch so that other people can take inspiration.
