### ISSUE TITLE
Checkpointing of auxiliary objects

### ISSUE THREAD

**Issue by ottonemo** [skorch-dev/skorch#635]
As discussed in PR #621, in some circumstances the criterion might change during training (learnable parameters) which makes it desirable for check pointing.

Additionally, #597 makes it easier to add additional modules, optimizers and criteria which do not adhere to the standard naming, rendering checkpointing for such objects useless as well.

- [x] We need to save the criterion as well (possibly optional)
- [x] We need to be able to deal with multiple optimizers / models / criteria when checkpointing

I can see the following options:

1. introduce `f_criterion` to checkpoint and instead of saving only the one optimizer/model/criterion we save *all* of them in their respective file - we can find those using the prefix and the registered parameters 
2. re-group files into a) models and b) training artifacts (history, optimizer, criterion) and save them independently

With (1) I'm a little worried that there is yet another parameter that needs saving in the future, resulting in an ever expanding parameter list for the checkpoint callback. Maybe this is irrational, I'm interested in other opinions.

**Comment by BenjaminBossan** [comment]
>     2. re-group files into a) models and b) training artifacts (history, optimizer, criterion) and save them independently

What I would like to avoid is a custom skorch storing format, even if it's just `{'module': ..., 'criterion': ...}`. Maybe that doesn't follow from your suggestion, I just want to throw this in.

If we look at the code for `save_params` and `load_params`, we see a certain regularity:

https://github.com/skorch-dev/skorch/blob/1f6b5428a0d58b9d0d2ef08384aeb45c1c14df55/skorch/net.py#L1638-L1652

I wonder if we can build on that and allow to pass arbitrary `f_*` kwargs. Thus, if a user wants to add `net.myoptimizer_` as an attribute, they can pass `f_myoptimizer` to `save_params`. I haven't thought this through, but it could be worth investigating.

**Comment by thomasjpfan** [comment]
> What I would like to avoid is a custom skorch storing format

I agree. Although this use case of saving custom objects has been concerned a few times.

What was the historical purpose of `save_params`? When I was working with it, I was assuming it was used for checkpointing.

**Comment by BenjaminBossan** [comment]
> What was the historical purpose of `save_params`?

I think that historically, the idea was to give a more general, pickle- and skorch-independent way of storing model parameters. That's why we tried to stick to what PyTorch recommends instead of providing our own storing format, even if that would be more convenient sometimes. At least for me, checkpoints were not even the first concern.

**Comment by BenjaminBossan** [comment]
This has been solved via #652
