### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by stsievert** [skorch-dev/skorch#644]
I'm drafting a paper that makes use of Skorch. Is there a citation you'd like me to use?

**Comment by BenjaminBossan** [comment]
Hey, I never thought we might get cited one day :hugs: 

We don't have any bibtex entry prepared but here is a proposal:

```
@misc{skorch,
  author       = {Marian Tietz and
                  Thomas J. Fan and
                  Daniel Nouri and
                  Benjamin Bossan},
  title        = {skorch: A scikit-learn compatible neural network library that wraps PyTorch},
  month        = jul,
  year         = 2017
}
```

Not sure what the etiquette is for naming all contributors, because that would be a much longer list than this.

Unfortunately, we don't have a doi, if you need it, I could try to create one.

**Comment by stsievert** [comment]
> Not sure what the etiquette is for naming all contributors, because that would be a much longer list than this.

Hm... Dask has the same problem. They have a bunch of contributors but ask for citations regardless. Dask's citation looks like this (https://docs.dask.org/en/latest/cite.html):

``` bibtex
@Manual{dask,
  title = {Dask: Library for dynamic task scheduling},
  author = {{Dask Development Team}},
  year = {2016},
  url = {https://dask.org},
}
```

I like `@manual` alongside the inclusion of the documentation URL. Here's the description of when to use `@manual` from bibtex.com:

> **`@manual`**
> A technical manual for a machine software such as would come with a purchase to explain operation to the new owner.
> 
> —https://www.bibtex.com/e/entry-types/#manual

It's up to you on how you want to include the authors. It's up to you, but I might do:

``` 
author = {Marian Tietz and Thomas J. Fan and Daniel Nouri and Benjamin Bossan and {Skorch Developers}}
```

**Comment by BenjaminBossan** [comment]
Thanks for the tips, putting this all together, we get:

```
@manual{skorch,
  author       = {Marian Tietz and
                  Thomas J. Fan and
                  Daniel Nouri and
                  Benjamin Bossan and
                  {skorch Developers}},
  title        = {skorch: A scikit-learn compatible neural network library that wraps PyTorch},
  month        = jul,
  year         = 2017,
  url          = {https://skorch.readthedocs.io/en/stable/}
}
```
