### ISSUE TITLE
TransformedTargetRegressor compatibility

### ISSUE THREAD

**Issue by DanielAtKrypton** [skorch-dev/skorch#649]
I am working on a [project ](https://github.com/DanielAtKrypton/time_series_predictor) in which I use the `TransformedTargetRegressor` functionality with skorch.
For any reason after applying the `TransformedTargetRegressor`, history can not be retrieved anymore.

Any ideas on how to overcome this issue? For example, running [this](https://github.com/DanielAtKrypton/time_series_predictor/blob/master/run_this.py):
```python
import torch

from src.flights_dataset import FlightsDataset
from src.model import BenchmarkLSTM
from time_series_predictor import TimeSeriesPredictor

if __name__ == "__main__":
    tsp = TimeSeriesPredictor(
        BenchmarkLSTM(),
        max_epochs=50,
        train_split=None,
        optimizer=torch.optim.Adam
    )

    tsp.fit(FlightsDataset())
    mean_loss = tsp.score(tsp.dataset)
    history = tsp.ttr.history
```

Should work right out of the box.

**Comment by ottonemo** [comment]
Shouldn't it be `tsp.ttr.regressor.history`?

**Comment by DanielAtKrypton** [comment]
> Shouldn't it be tsp.ttr.regressor.history?

The output of `print(tsp.ttr.regressor.history)` returns:
```python
Traceback (most recent call last):
  File "c:/Users/dani_/Workspaces/Python/time_series_predictor/run_this.py", line 20, in <module>
    print(tsp.ttr.regressor.history)
AttributeError: 'Pipeline' object has no attribute 'history'
```

And if I select the `NeuralNetRegressor` object, with [regressor key](https://github.com/DanielAtKrypton/time_series_predictor/blob/270f35ad153fa25288a730fc9a60185371f65f7e/time_series_predictor/time_series_predictor.py#L56) I used to create the pipeline, as follows:
```python
print(tsp.ttr.regressor['regressor'].history)
```

The output shown is:
```python
None
```

But there was a successful fit at first. Somehow external access to history was lost in the process.

**Comment by DanielAtKrypton** [comment]
I was able to collect history by simply issuing the following command after the fit process:
```python
print(tsp.ttr.regressor_['regressor'].history)
```

This happens because the object that method fit is called upon is [`regressor_`](https://github.com/DanielAtKrypton/time_series_predictor/blob/270f35ad153fa25288a730fc9a60185371f65f7e/time_series_predictor/sklearn/compose/_target.py#L207) rather than `regressor`. It is actually a [`regressor` clone](https://github.com/DanielAtKrypton/time_series_predictor/blob/270f35ad153fa25288a730fc9a60185371f65f7e/time_series_predictor/sklearn/compose/_target.py#L205).
