### ISSUE TITLE
How to make skorch stop printing history?

### ISSUE THREAD

**Issue by Beau-Yang** [skorch-dev/skorch#659]
Sometimes I do not need to print the history information. What can I do to prevent the code from printing it? Thanks a lot.

**Comment by BenjaminBossan** [comment]
Pass the argument `verbose=0` to the net.

According to the [docs](https://skorch.readthedocs.io/en/stable/net.html):

> verbose : int (default=1)
>    Control the verbosity level.

I think this could indeed be documented better.

**Comment by Beau-Yang** [comment]
It does work. Thank you so much.
