### ISSUE TITLE
Link external resources

### ISSUE THREAD

**Issue by BenjaminBossan** [skorch-dev/skorch#664]
By now, we have a few external resources about skorch. Maybe we can collect a list here and then think about integrating it. Where? Possibly in the README, the docs, or on our new skorch.net domain.

Here is what I have so far:

* @githubnemo's [poster](https://github.com/githubnemo/skorch-poster) for PyTorch developer conference
* @thomasjpfan's [talk](https://www.youtube.com/watch?v=yAXsxf2CQ8M) "Skorch - A Union of Scikit-learn and PyTorch" at PyData 2018
* @thomasjpfan's [talk](https://www.youtube.com/watch?v=0J7FaLk0bmQ) "Skorch: A Union of Scikit learn and PyTorch" at SciPy 2019
* my [talk](https://www.youtube.com/watch?v=Qbu_DCBjVEk) "skorch: A scikit-learn compatible neural network library" at PyCon/PyData 2019
* @jakubczakon's [blog post](https://neptune.ai/blog/model-training-libraries-pytorch-ecosystem) "8 Creators and Core Contributors Talk About Their Model Training Libraries From PyTorch Ecosystem"

**Comment by thomasjpfan** [comment]
I am okay with having these resources in the README.
