### ISSUE TITLE
given a ImageFolder dataset, how to retrieve the item_path for any element?

### ISSUE THREAD

**Issue by SergioMarreroMarrero** [skorch-dev/skorch#666]
I am performing a batch prediction using a ImageFolder dataset object. I want to map all predicitions with each _image_path_ of each image of the dataset. How can I do that?

**Comment by BenjaminBossan** [comment]
Hey Sergio, unfortunately, I don't understand what exactly you would like to achieve. Can you maybe give an example?

In general, it seems you're talking about `ImageFolder` from [torchvision](https://github.com/pytorch/vision), maybe you can find the answer in their docs or can ask the question on their issue tracker. skorch has no relation to `ImageFolder`.

**Comment by SergioMarreroMarrero** [comment]
Hi Benjamin. 

Thanks for your attention and sorry for don't explain myself better. Although I mentioned ImageFolder the question is related with skorch. Let me explain again:


Suppose `net `is an object from the class` skorch.classifier.NeuralNetClassifier`. I have a folder with some images, such that: _image1.jpg, image2.jpg, image3.png.._.  Over these images a build a `dataset` using the class `skorch.dataset.Dataset`, in such way this `dataset `_will always yield a tuple of two values, the first from the data (X) and the second from the target (y)_. Because my `net `is already trained I go straight forward to predict, so then I do:

`pred = net.predict(X=dataset) `

Now that I have my predictions in `pred`, I want to join each image name with the correspond prediction. It would look like as:

_the image: image1.jpg  has the the prediction: 1
the image: image2.jpg  has the the prediction: 0
the image: image3.png has the the prediction: 0_


How do I resolve this in a proper and reliably way in skorch?

**Comment by BenjaminBossan** [comment]
Do you use the skorch `Dataset` and `ImageFolder` in conjunction? Ideally, you could paste some code that shows your custom dataset class.

In general though, the order should be conserved, so e.g. if the `ImageFolder` class returns images in alphabetical order, that should also be the order of the predictions.

**Comment by SergioMarreroMarrero** [comment]
I think it is not a reliable way for on production models. No, actually I'm using `ImageFolder` yielding a tuple (X[idx], y[idx]). FInally I did it in PyTorch because I needed this extra level of reliability.

**Comment by BenjaminBossan** [comment]
Okay, it seems you solved your problem, I'll close the issue for now.
