### ISSUE TITLE
Pytorch geometric support

### ISSUE THREAD

**Issue by mshuaibii** [skorch-dev/skorch#671]
When trying to integrate skorch with pytorch geometric you run into errors in skorch's `to_tensor`. Specifically, skorch is unable to recognize the corresponding `Data` objects of geometric. Has anyone found a way to work around this? I can get around this by commenting out the `raise TypeError("Cannot convert this data type to a torch tensor.")` but was hoping there was an alternative way around this?

**Comment by BenjaminBossan** [comment]
Thanks for reporting. It would be great to make skorch work with PyTorch geometric. Do you have a minimal example to reproduce the error?

@ottonemo @thomasjpfan What are your thoughts on somehow making it possible for `to_tensor` to not raise an error when it cannot understand the type?

**Comment by mshuaibii** [comment]
```
from torch_geometric.datasets import QM9
from torch_geometric.data import DataLoader
from skorch.utils import to_tensor

dataset = QM9(root="./qm9")
loader = DataLoader(dataset, batch_size=32, shuffle=True)
device = "cpu"

for batch in loader:
   to_tensor(batch, device)
```

Skorch is unable to detect that the pytorch geometric objects are already tensors and essentially breaks here. This is the main issue I've been running into that has required modifying the source code. The other implementation details into the skorch framework are fairly straight forward. Allowing us to bypass this check somehow would resolve this for geometric. Otherwise a geometric specific check may look something like this:

```
keys = batch.keys
for key in keys:
   batch.key = torch.as_tensor(batch.key, device=device)
```

**Comment by thomasjpfan** [comment]
> Skorch is unable to detect that the pytorch geometric objects are already tensors and essentially breaks here.

The [geometric Data](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.Data) are tensors + more metadata. They pytorch geometric data loader uses a [custom collate_fn](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/data/dataloader.html#DataLoader) that special cases the `Data` object, returning a custom `Batch` object:

```
		if isinstance(elem, Data):
            return Batch.from_data_list(batch, self.follow_batch)
```

> What are your thoughts on somehow making it possible for to_tensor to not raise an error when it cannot understand the type?

Since we call `to_tensor` only in `infer` and `get_loss`, we can 

1. Tell users to subclass and override these two methods.
2. Have a parameter that controls if `to_tensor` passes through `X`.
3. Have `to_tensor` pass through `X` if we do not recognize it.

**Comment by mshuaibii** [comment]
> 1. Tell users to subclass and override these two methods.
> 2. Have a parameter that controls if `to_tensor` passes through `X`.
> 3. Have `to_tensor` pass through `X` if we do not recognize it.

Is option 1. something that can be implemented without modifying the source code? I'm specifically using the `NeuralNetRegressor` class. Would I just inherit the parent and redefine `infer` and `get_loss` to remove the `to_tensor` calls? Option 2 sounds great, but looking for a temporary solution until such a change is made?

Thanks!

**Comment by BenjaminBossan** [comment]
> I'm imagining just inheriting that parent and redefine `infer` and `get_loss` to remove the `to_tensor` calls?

Exactly, you create your own custom class (which we encourage in skorch) that inherits from `NeuralNetRegressor` and override those two methods. Similar to how you create your own `nn.Module`s.

> something that can be implemented without modifying the source code

By that, you probably mean having to go inside the skorch source code and changing it. That shouldn't be necessary either way. You wrote at the beginning:

> I can get around this by commenting out the raise TypeError("Cannot convert this data type to a torch tensor.")

To achieve the same outcome, you can write your own `to_tensor` function and then:

```python
import skorch.net
skorch.net.to_tensor = my_custom_to_tensor
```

That should do the trick without having to fuzz with the skorch source code. This way, you also don't need to care where exactly (in the `net.py` module) `to_tensor` is being used. The disadvantage of this technique ("monkey patching") is that it might sometimes not work if the import order is wrong.

>     2. Have a parameter that controls if `to_tensor` passes through `X`.

Problem here is of course that `to_tensor` is called inside certain methods, so it's not possible to change the parameter easily. One way around is to add a parameter in `NeuralNet` to control this but this seems to be really ugly to me.

Instead, we could have a global config variable inside `utils.py`, say `permissive_to_tensor` or so, that is controlling the behavior. Users could then set `skorch.utils.permissive_to_tensor = True` to flip the current behavior. I don't think it's a bad pattern per se, but it's uncommon in Python, thus might be confusing. Another disadvantage is that we wouldn't be able to easily modify that behavior in a backwards compatible way once it's there -- module `__getattr__` was only implemented in Python 3.7 and module `__setattr__` doesn't exist at all AFAIK.

>     3. Have `to_tensor` pass through `X` if we do not recognize it.

I would probably not change the current behavior, at least not by default.

A fourth way would be to recognize the PyTorch geometric `data` object. I would, however, not add PyTorch geometric as a dependency, meaning we couldn't check the type. Instead, we would need to check the behavior (similar to how sklearn checks for pandas DataFrames), but I find that to be brittle.

**Comment by thomasjpfan** [comment]
> I would probably not change the current behavior, at least not by default.

This behavior change does not change anything for the documented data types we support. For unsupported data types we can say "use at your own risk".

With a global configuration option we need to be careful with its interaction with pytorch's `DataLoader` and multiple `num_workers` or `dask` when it uses multiple processes. When a new process is spawned, it would need to know to set the global configuration. Because of this I am -0.5 on global configuration.

Another option is to add another `FAQ` question in regards to custom objects from the DataLoader or Dataset objects.

**Comment by BenjaminBossan** [comment]
> This behavior change does not change anything for the documented data types we support. For unsupported data types we can say "use at your own risk".

Though that is true, we also don't state that unsupported types are just passed (or raise an error for that matter). So users might just assume that the contract is whatever happens to be implemented. I admit, however, that it's hard to imagine that anyone relies on `to_tensor` throwing a `TypeError` in their code.

> When a new process is spawned, it would need to know to set the global configuration. Because of this I am -0.5 on global configuration.

Is that so? In that case, I agree that we shouldn't do it. Presumably, that would also affect monkey patching.

I made a small test for `DataLoader`:

```python
# inside skorch/utils.py

const = 0
class FooDataset(torch.utils.data.Dataset):
    def __init__(self, n):
        self.n = n

    def __len__(self):
        return self.n

    def __getitem__(self, i):
        if 0 <= i < self.n:
            return [i + const]
        raise IndexError

# inside script

>>> from skorch.utils import FooDataset
>>> import skorch.utils
>>> skorch.utils.const = -100
>>> from torch.utils.data import DataLoader

>>> batches = [batch for batch in DataLoader(FooDataset(50), batch_size=10, num_workers=1)]
>>> batches
[[tensor([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91])],
 [tensor([-90, -89, -88, -87, -86, -85, -84, -83, -82, -81])],
 [tensor([-80, -79, -78, -77, -76, -75, -74, -73, -72, -71])],
 [tensor([-70, -69, -68, -67, -66, -65, -64, -63, -62, -61])],
 [tensor([-60, -59, -58, -57, -56, -55, -54, -53, -52, -51])]]

>>> batches = [batch for batch in DataLoader(FooDataset(50), batch_size=10, num_workers=4)]
>>> batches
[[tensor([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91])],
 [tensor([-90, -89, -88, -87, -86, -85, -84, -83, -82, -81])],
 [tensor([-80, -79, -78, -77, -76, -75, -74, -73, -72, -71])],
 [tensor([-70, -69, -68, -67, -66, -65, -64, -63, -62, -61])],
 [tensor([-60, -59, -58, -57, -56, -55, -54, -53, -52, -51])]]

skorch.utils.const = 500
>>> batches = [batch for batch in DataLoader(FooDataset(50), batch_size=10, num_workers=4)]
batches
[[tensor([500, 501, 502, 503, 504, 505, 506, 507, 508, 509])],
 [tensor([510, 511, 512, 513, 514, 515, 516, 517, 518, 519])],
 [tensor([520, 521, 522, 523, 524, 525, 526, 527, 528, 529])],
 [tensor([530, 531, 532, 533, 534, 535, 536, 537, 538, 539])],
 [tensor([540, 541, 542, 543, 544, 545, 546, 547, 548, 549])]]
```

So this seems to work as expected. But maybe my example is too simplistic? I agree though that with dask I would expect such an example not to work but I didn't test.
