### ISSUE TITLE
Does skorch support class_weight?

### ISSUE THREAD

**Issue by hadifar** [skorch-dev/skorch#673]
I already saw [this](https://skorch.readthedocs.io/en/stable/user/FAQ.html#i-want-to-use-sample-weight-how-can-i-do-this) thread but I am wondering to know does Skorch supports `class_weight`? Same as `class_weight` in `RandomForestClassfifier`.

This is my last attempt:

```
        net = NeuralNetClassifier(
            module=Classifier,
            module__args=args,
            module__n_classes=2,
            max_epochs=args.n_epochs,
            lr=args.lr,
            # Shuffle training data on each epoch
            train_split=None,
            iterator_train__shuffle=False,
            device=args.device,
            criterion=torch.nn.NLLLoss,
            criterion__weight=class_weight
            # callbacks=[f1, prec, recall],
        ) 
```

Is it the correct way to do this?

**Comment by BenjaminBossan** [comment]
Yes, this seems good to me. Did it not work for you?

**Comment by BenjaminBossan** [comment]
@hadifar Any updates?

**Comment by BenjaminBossan** [comment]
I assume the problem has been solved. If not, feel free to re-open the issue.
