### ISSUE TITLE
How to use dask dataframe in .fit function?

### ISSUE THREAD

**Issue by Sinha-Ujjawal** [skorch-dev/skorch#679]
How to use dask dataframe in .fit function?

I am getting the following error-
```bash
NotImplementedError: 'DataFrame.iloc' only supports selecting columns. It must be used like 'df.iloc[:, column_indexer]'
```

**Comment by BenjaminBossan** [comment]
Hi, there is no official support for dask DataFrames. That doesn't mean it cannot work, but to tell you more, I would need to see the full stacktrace or even better have a minimal code example.

Meanwhile, if it's possible in your context, you could convert the dask DataFrame to a pandas DataFrame, which is supported.

**Comment by BenjaminBossan** [comment]
@Sinha-Ujjawal did you make any progress?

**Comment by BenjaminBossan** [comment]
Closing for now due to inactivity. Just to re-iterate, dask dataframes are not supported. The only viable solution is probably to convert to pandas.
