### ISSUE TITLE
Predefined split broken (TypeError: _make_split() got multiple values for argument 'valid_ds')

### ISSUE THREAD

**Issue by Dewald928** [skorch-dev/skorch#681]
I am currently working on the 0.8.1.dev0 version, because I want the LR scheduler on batch training.
But when I updated from 0.8.0 I get the following error when I use a predefined dataset in the train_split. (I didn't change anything except from the update)

`TypeError: _make_split() got multiple values for argument 'valid_ds'`

I know a few things changed with the unsupervised inputs, but I can't seem to figure out what to do to fix this. 
Is there an extra parameter I need to add somewhere or something I'm missing?

**Comment by BenjaminBossan** [comment]
Could you check if the breakage could have been caused by #646? That's the only recent change to the train/valid splitting that comes to my mind, and as the discussion suggests, it might break existing code.

**Comment by Dewald928** [comment]
Yes it is caused by #646 
I checked out the commit #626 everything was still working there.

The issue happens only when I pass a valid_ds to the trainsplit parameter

**Comment by BenjaminBossan** [comment]
Could you please provide a minimal code example to reproduce the error?

**Comment by Dewald928** [comment]
Even if I just run the simple snippet below, I get the same error.


```
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from skorch import NeuralNetClassifier
from skorch.dataset import Dataset
from skorch.helper import predefined_split
from skorch.toy import make_classifier

X, y = make_classification(n_samples=10000, n_features=2, n_redundant=0,
                           n_informative=1, n_clusters_per_class=1,
                           weights=[0.1, 0.9], class_sep=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33,
                                                    random_state=1)

valid_ds = Dataset(X_test, y_test)

model = make_classifier(**{"input_units": 2})

net = NeuralNetClassifier(
    model,
    max_epochs=10,
    lr=0.1,
    train_split=predefined_split(valid_ds),
)

net.fit(X, y)
y_proba = net.predict_proba(X)
```

**Comment by Dewald928** [comment]
I still seem to get the error. 

I tried checking out the branch with

```pip install git+https://github.com/skorch-dev/skorch.git@bugfix/predefined_split-bug-caused-by-646``

since I'm using conda. Don't know if that is good practice.

Perhaps someone could just validate, perhaps another issue on my side.

**Comment by BenjaminBossan** [comment]
Hmm, that's strange. I see two possibilities here:

1) your Python environment still uses the old code
2) there is another error still happening

To check for possibility 1), could you please try to run the code example you gave above? If that fails, it means the old code is still being used, given that it passes for me.

If it passes, it means there is a difference between the example and your actual code, i.e. option 2). Then it would be good if you could provide a more complete example that triggers the error despite the fix.

**Comment by Dewald928** [comment]
The issue was on my side. I had issues with my commit.

Everything is working now with #682.

Closing the issue.

**Comment by michelewang** [comment]
Has this been fixed? I've tried using skorch in another one of my projects on Colab, but I'm still running into the same issue.

**Comment by Dewald928** [comment]
Try `pip install git+https://github.com/skorch-dev/skorch.git`
It should get the latest dev branch. It seems they haven't made a new release with the fix yet.

**Comment by michelewang** [comment]
Thank you so much!!! I found your solution worked in Colab but not when I was running my identical code on a Jupyter notebook in a cluster..  Do you know if the skorch dev branch is compatible with cuda 10.2 and pytorch 1.7.0? On the [website](https://skorch.readthedocs.io/en/stable/user/installation.html#from-source) it seems skorch only officially supports up til pytorch 1.6.0, but I'm not sure if that's the issue..

**Comment by BenjaminBossan** [comment]
Glad to hear that it works @michelewang 

skorch should work just fine with PyTorch 1.7. In general, since we mostly stick to the stable API of PyTorch, skorch will work out of the gate with new PyTorch versions. The only reason why it's not written on the website is because we want to ensure this via our CI first. And there, it seems that PyTorch 1.7 works without problems (see [here](https://github.com/skorch-dev/skorch/pull/686#issuecomment-720080998)).

Regarding cuda, whatever works with your PyTorch version should work with skorch.

**Comment by jiajiexiao** [comment]
@BenjaminBossan just out of curiosity...is there a plan to make a release with this fix in the near future?

**Comment by BenjaminBossan** [comment]
Hi @jiajiexiao, I really hope so. There are a few big PRs open that I'd like to be merged first, though it's not strictly necessary. @ottonemo WDYT?
