### ISSUE TITLE
Output the weight and bias of class 'skorch.regressor.NeuralNetRegressor'

### ISSUE THREAD

**Issue by lfangyu09** [skorch-dev/skorch#690]
<class 'skorch.regressor.NeuralNetRegressor'>[initialized](
  module_=MLPModel(
    (model): Sequential(
      (0): Linear(in_features=200, out_features=400, bias=True)
      (1): ReLU()
      (2): Dropout(p=0.4, inplace=False)
      (3): Linear(in_features=400, out_features=400, bias=True)
      (4): ReLU()
      (5): Dropout(p=0.4, inplace=False)
      (6): Linear(in_features=400, out_features=1, bias=True)
    )
  ),
)

How can I output the weight and bias of each layer in class 'skorch.regressor.NeuralNetRegressor'?

**Comment by BenjaminBossan** [comment]
You can access the PyTorch module of the net using the `net.module_` attribute. From there, just proceed as with any PyTorch module. E.g.:

```python
# all learnable parameters
list(net.module_.parameters())

# all learnable parameters including their names
list(net.module_.named_parameters())
```

**Comment by lfangyu09** [comment]
Thanks!

**Comment by lfangyu09** [comment]
> You can access the PyTorch module of the net using the `net.module_` attribute. From there, just proceed as with any PyTorch module. E.g.:
> 
> ```python
> # all learnable parameters
> list(net.module_.parameters())
> 
> # all learnable parameters including their names
> list(net.module_.named_parameters())
> ```

Thanks!
