### ISSUE TITLE
Runtime error in Advanced_Usage.ipynb example notebook 

### ISSUE THREAD

**Issue by notuntoward** [skorch-dev/skorch#691]
If I run the example notebook [Advanced_Usage.ipynb](https://github.com/skorch-dev/skorch/blob/master/notebooks/Advanced_Usage.ipynb), I get the error below after running cell 21.  This with this config:

Windows 10
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
IPython 7.18.1
Skorch 0.90

**The error**

> [21]: net.fit(dataset, y=y)

> Re-initializing module.
> Re-initializing optimizer.

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-21-97f5c23b7a37> in <module>
> ----> 1 net.fit(dataset, y=y)
> 
> ~\anaconda3\envs\pytorch\lib\site-packages\skorch\classifier.py in fit(self, X, y, **fit_params)
>     140         # this is actually a pylint bug:
>     141         # https://github.com/PyCQA/pylint/issues/1085
> --> 142         return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
>     143 
>     144     def predict_proba(self, X):
> 
> ~\anaconda3\envs\pytorch\lib\site-packages\skorch\net.py in fit(self, X, y, **fit_params)
>     852             self.initialize()
>     853 
> --> 854         self.partial_fit(X, y, **fit_params)
>     855         return self
>     856 
> 
> ~\anaconda3\envs\pytorch\lib\site-packages\skorch\net.py in partial_fit(self, X, y, classes, **fit_params)
>     811         self.notify('on_train_begin', X=X, y=y)
>     812         try:
> --> 813             self.fit_loop(X, y, **fit_params)
>     814         except KeyboardInterrupt:
>     815             pass
> 
> ~\anaconda3\envs\pytorch\lib\site-packages\skorch\net.py in fit_loop(self, X, y, epochs, **fit_params)
>     724             self.notify('on_epoch_begin', **on_epoch_kwargs)
>     725 
> --> 726             self.run_single_epoch(dataset_train, training=True, prefix="train",
>     727                                   step_fn=self.train_step, **fit_params)
>     728 
> 
> ~\anaconda3\envs\pytorch\lib\site-packages\skorch\net.py in run_single_epoch(self, dataset, training, prefix, step_fn, **fit_params)
>     761             yi_res = yi if not is_placeholder_y else None
>     762             self.notify("on_batch_begin", X=Xi, y=yi_res, training=training)
> --> 763             step = step_fn(Xi, yi, **fit_params)
>     764             self.history.record_batch(prefix + "_loss", step["loss"].item())
>     765             self.history.record_batch(prefix + "_batch_size", get_len(Xi))
> 
> ~\anaconda3\envs\pytorch\lib\site-packages\skorch\net.py in train_step(self, Xi, yi, **fit_params)
>     657             step_accumulator.store_step(step)
>     658             return step['loss']
> --> 659         self.optimizer_.step(step_fn)
>     660         self.optimizer_.zero_grad()
>     661         return step_accumulator.get_step()
> 
> ~\anaconda3\envs\pytorch\lib\site-packages\torch\autograd\grad_mode.py in decorate_context(*args, **kwargs)
>      13         def decorate_context(*args, **kwargs):
>      14             with self:
> ---> 15                 return func(*args, **kwargs)
>      16         return decorate_context
>      17 
> 
> ~\anaconda3\envs\pytorch\lib\site-packages\torch\optim\sgd.py in step(self, closure)
>      84         if closure is not None:
>      85             with torch.enable_grad():
> ---> 86                 loss = closure()
>      87 
>      88         for group in self.param_groups:
> 
> ~\anaconda3\envs\pytorch\lib\site-packages\skorch\net.py in step_fn()
>     654         step_accumulator = self.get_train_step_accumulator()
>     655         def step_fn():
> --> 656             step = self.train_step_single(Xi, yi, **fit_params)
>     657             step_accumulator.store_step(step)
>     658             return step['loss']
> 
> ~\anaconda3\envs\pytorch\lib\site-packages\skorch\net.py in train_step_single(self, Xi, yi, **fit_params)
>     597         self.module_.train()
>     598         y_pred = self.infer(Xi, **fit_params)
> --> 599         loss = self.get_loss(y_pred, yi, X=Xi, training=True)
>     600         loss.backward()
>     601 
> 
> ~\anaconda3\envs\pytorch\lib\site-packages\skorch\classifier.py in get_loss(self, y_pred, y_true, *args, **kwargs)
>     125             eps = torch.finfo(y_pred.dtype).eps
>     126             y_pred = torch.log(y_pred + eps)
> --> 127         return super().get_loss(y_pred, y_true, *args, **kwargs)
>     128 
>     129     # pylint: disable=signature-differs
> 
> ~\anaconda3\envs\pytorch\lib\site-packages\skorch\net.py in get_loss(self, y_pred, y_true, X, training)
>    1100         """
>    1101         y_true = to_tensor(y_true, device=self.device)
> -> 1102         return self.criterion_(y_pred, y_true)
>    1103 
>    1104     def get_dataset(self, X, y=None):
> 
> ~\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
>     720             result = self._slow_forward(*input, **kwargs)
>     721         else:
> --> 722             result = self.forward(*input, **kwargs)
>     723         for hook in itertools.chain(
>     724                 _global_forward_hooks.values(),
> 
> ~\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\loss.py in forward(self, input, target)
>     209 
>     210     def forward(self, input: Tensor, target: Tensor) -> Tensor:
> --> 211         return F.nll_loss(input, target, weight=self.weight, ignore_index=self.ignore_index, reduction=self.reduction)
>     212 
>     213 
> 
> ~\anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
>    2216                          .format(input.size(0), target.size(0)))
>    2217     if dim == 2:
> -> 2218         ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
>    2219     elif dim == 4:
>    2220         ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
> 
> RuntimeError: expected scalar type Long but found Int

**Comment by thomasjpfan** [comment]
Before the call to `fit`, does casting `y` help?:

```py
y = y.astype(np.int64)
net.fit(dataset, y=y)
```

**Comment by notuntoward** [comment]
Unfortunately, I get the same error.

**Comment by BenjaminBossan** [comment]
You have these lines directly before, right?

```python
X, y = make_classification(1000, 20, n_informative=10, random_state=0)
X = X.astype(np.float32)
dataset = MyDataset(X, y)
```

Please change them to:

```python
X, y = make_classification(1000, 20, n_informative=10, random_state=0)
X = X.astype(np.float32)
y = y.astype(np.int64)
dataset = MyDataset(X, y)
```

Does that solve the issue? If yo, could you please tell us what kind of system you use? I.e. OS and whether it's 32bit or 64bit.

**Comment by BenjaminBossan** [comment]
@notuntoward Any updates? Did you manage to make it run?
