### ISSUE TITLE
Fit pipeline on GPU

### ISSUE THREAD

**Issue by LL8848** [skorch-dev/skorch#697]
There seems a problem when use a pipeline with the module on GPU to fit a tensor that has been put on GPU as well.  Please see the code below.  As the pipeline has scaler/transformer, the GPU tensor seems to convert back to CPU numpy array, which leads to `TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`

How to work around this issue?

Cheers

```python 
from skorch.utils import to_device, to_tensor
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

estimator = NeuralNetRegressor(
    module=RegressorModule(num_units=9),
    max_epochs=50,
    lr=0.1,
    train_split=None,
    device=device  # uncomment this to train with CUDA
)
pipe0 = Pipeline([('log',FunctionTransformer(np.log,np.exp,validate=True)),
                 ('scale',StandardScaler()),
                 ('model',estimator)])
pipe = TransformedTargetRegressor(regressor=pipe0,
                                  transformer=MinMaxScaler(),
                                  check_inverse=True)

X_train = to_tensor(X_train, device)
y_train = to_tensor(y_train, device)

pipe.fit(X_train,y_train) 
```

**Comment by BenjaminBossan** [comment]
Usually, the conversion to a (cuda) torch tensor should happen _inside_ the `NeuralNetRegressor`, i.e. `X_train = to_tensor(X_train, device)` shouldn't be necessary. The reason for that is:

1. You avoid back and forth casting through `StandardScaler` etc. 
2. You usually don't want to send the whole `X_train` to your GPU, which can take a lot of memory, but instead only each batch.

In your specific case, what is the value of `device`? It should be `'cuda'`. If that's the case and the error still happens, we need to investigate further. For that, please post the full stacktrace of the error.

Also some unsolicited advice:

* You usually shouldn't pass an initialized module to the net, instead do `net = NeuralNet(RegressorModule, module__num_units=9, ...)`
* Using first log and then standard scaling as preprocessing seems unconventional to me.
* I wouldn't wrap the whole pipe inside `TransformedTargetRegressor`, but only the final estimator:

```python
net = NeuralNetRegressor(...)
pipe = Pipeline([
    ...,
    ('regressor', TransformedTargetRegressor(net, ...)),
])
```

**Comment by LL8848** [comment]
Now it's working.  Thanks a lot!  Your advice is super helpful.

**Comment by BenjaminBossan** [comment]
That's great, I'll close the issue then.
