### ISSUE TITLE
BUG: Corrupted history.json with custom epoch scorer/checkpoint

### ISSUE THREAD

**Issue by pdimitrov-thoughtriver** [skorch-dev/skorch#698]
I have the following issue with a corrupted json history file:

~/projects/ptc/ptc/net.py in fit(self, X, y, sample_weight, **kwargs)
    393         net = super()
    394         net.initialize()
--> 395         net.load_params(checkpoint = Checkpoint(dirname = self.checkpoint_dir))
    396 
    397     def get_loss(self, y_pred, y_true, X, *args, **kwargs):

~/anaconda3/envs/latest_fathom/lib/python3.6/site-packages/skorch/net.py in load_params(self, f_params, f_optimizer, f_criterion, f_history, checkpoint, **kwargs)
   1975                 self.initialize()
   1976             if f_history is None and checkpoint.f_history is not None:
-> 1977                 self.history = History.from_file(checkpoint.f_history_)
   1978             kwargs_full.update(**checkpoint.get_formatted_files(self))
   1979 

~/anaconda3/envs/latest_fathom/lib/python3.6/site-packages/skorch/history.py in from_file(cls, f)
    160 
    161         with open_file_like(f, 'r') as fp:
--> 162             return cls(json.load(fp))
    163 
    164     def to_file(self, f):

~/anaconda3/envs/latest_fathom/lib/python3.6/json/__init__.py in load(fp, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    297         cls=cls, object_hook=object_hook,
    298         parse_float=parse_float, parse_int=parse_int,
--> 299         parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
    300 
    301 

~/anaconda3/envs/latest_fathom/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

~/anaconda3/envs/latest_fathom/lib/python3.6/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

~/anaconda3/envs/latest_fathom/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 2288 (char 2287)

with the history file looking like this:

[{"batches": [{"train_loss": 2132.9609375, "train_batch_size": 512}, {"train_loss": 77.48575592041016, "train_batch_size": 512}, {"train_loss": 164.7255859375, "train_batch_size": 512}, {"train_loss": 117.14952850341797, "train_batch_size": 512}, {"train_loss": 194.2737274169922, "train_batch_size": 512}, {"train_loss": 170.26641845703125, "train_batch_size": 512}, {"train_loss": 179.06944274902344, "train_batch_size": 512}, {"train_loss": 165.21841430664062, "train_batch_size": 512}, {"train_loss": 121.10197448730469, "train_batch_size": 512}, {"train_loss": 141.53895568847656, "train_batch_size": 512}, {"train_loss": 115.98213195800781, "train_batch_size": 512}, {"train_loss": 140.24972534179688, "train_batch_size": 512}, {"train_loss": 157.20755004882812, "train_batch_size": 512}, {"train_loss": 84.15714263916016, "train_batch_size": 512}, {"train_loss": 74.5554428100586, "train_batch_size": 512}, {"train_loss": 105.78357696533203, "train_batch_size": 512}, {"train_loss": 76.74254608154297, "train_batch_size": 512}, {"train_loss": 170.40023803710938, "train_batch_size": 512}, {"train_loss": 92.17536163330078, "train_batch_size": 512}, {"train_loss": 188.14419555664062, "train_batch_size": 512}, {"train_loss": 129.93206787109375, "train_batch_size": 512}, {"train_loss": 99.55220031738281, "train_batch_size": 512}, {"train_loss": 102.05860900878906, "train_batch_size": 512}, {"train_loss": 130.03506469726562, "train_batch_size": 512}, {"train_loss": 80.4686279296875, "train_batch_size": 285}, {"valid_loss": 91.0097427368164, "valid_batch_size": 512}, {"valid_loss": 107.46955871582031, "valid_batch_size": 512}, {"valid_loss": 97.85794067382812, "valid_batch_size": 512}, {"valid_loss": 96.49768829345703, "valid_batch_size": 512}, {"valid_loss": 88.699462890625, "valid_batch_size": 512}, {"valid_loss": 97.90634155273438, "valid_batch_size": 512}, {"valid_loss": 9.231088638305664, "valid_batch_size": 72}], "epoch": 1, "train_batch_count": 25, "valid_batch_count": 7, "dur": 2.512906789779663, "train_loss": 210.7600457371917, "train_loss_best": true, "valid_loss": 94.57324892873983, "valid_loss_best": true, "f1": 0.4992266683127829, "f1_best": true, "ave_recall": 0.28522747692875305, "ave_recall_best": true, "mcc": 0.0, "mcc_best": true, "perplexity": 

where it cuts off unexpectedly. The custom metric I use is called perplexity. If I remove the perplexity metric from the epoch scoring + checkpointing, the issue disappears. Unfortunately, I dont think I can (re-)produce a simple MWE at the moment. The whole infrastructure/model is very complicated. 

Any idea how to fix this? I'm almost at the end of my code writing at the moment and would like to start testing for productionization ASAP.

Thank you,

**Comment by BenjaminBossan** [comment]
What is the type of perplexity? If it's a torch scalar, it will not be json-serializable. In that case, turn it into a float by calling `.item()` on it.

**Comment by pdimitrov-thoughtriver** [comment]
Thank you, Benjamin, for the quick reply.

Your hunch is right. It's not torch.Tensor, but some other messed up type from scipy which came about from using scipy.special.logsumexp. It's neither numpy.ndarray, nor ordinary Python float. In fact, my lower precision implementation using np.log and scipy.special.expit was working just fine, but once I switched to logsumexp the type apparently silently changed.

Would it be possible to catch this before/during serializing or dumping the history instead of when the history is read back? It threw me for a loop and I got nowhere trying to debug the issue.

Thanks again,

Peter

**Comment by BenjaminBossan** [comment]
> Would it be possible to catch this before/during serializing or dumping the history instead of when the history is read back?

Tbh I would have thought that this should already happen. E.g.:

```python
>>> json.dumps(np.zeros(3))
TypeError: Object of type ndarray is not JSON serializable
```

Could you tell me what the type is that caused your problem? When I used `scipy.special.logsumexp`, I just got a `numpy.float64`, which works fine.

**Comment by pdimitrov-thoughtriver** [comment]
Looks like float32:

ipdb> np.exp(-np.where(true, -logsumexp(-stack, 0), -logsumexp(stack, 0)).mean())  # quantity to be json serialized
1.0353758
ipdb> isinstance(np.exp(-np.where(true, -logsumexp(-stack, 0), -logsumexp(stack, 0)).mean()), float)
False
ipdb> isinstance(np.exp(-np.where(true, -logsumexp(-stack, 0), -logsumexp(stack, 0)).mean()), np.ndarray)
False
ipdb> import torch
ipdb> isinstance(np.exp(-np.where(true, -logsumexp(-stack, 0), -logsumexp(stack, 0)).mean()), torch.Tensor)
False
ipdb> float(np.exp(-np.where(true, -logsumexp(-stack, 0), -logsumexp(stack, 0)).mean()))
1.0353758335113525
ipdb> true
array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)
ipdb> predicted
array([-6.6099715, -8.62557  , -3.7062001, ..., -4.465137 , -4.465137 ,
       -7.6093526], dtype=float32)
ipdb> -logsumexp(-stack, 0)
array([-6.6113176, -8.62575  , -3.7304738, ..., -4.4765744, -4.4765744,
       -7.609848 ], dtype=float32)

HTH,

**Comment by BenjaminBossan** [comment]
Strange, both `np.float32` and arrays with dtype `np.float32` (which your last object seems to be) raise `TypeError: Object of type ndarray is not JSON serializable` for me. What platform are you on?

**Comment by pdimitrov-thoughtriver** [comment]
I'm on Ubuntu 20.04 with python 3.6.10 with master version of skorch from last week, I believe. Incidentally, I changed scipy.special.logsumexp to np.logaddexp with explicit cast:

            def score_f(true, logits, *args, **kwargs):
                return np.exp(
                    np.where(true, np.logaddexp(-logits, 0), np.logaddexp(logits, 0)).mean(),
                    dtype = np.float64
                )

This version works fine while the version w/o the explicit cast and coming with np.float32 arguments is not being serialized properly...

**Comment by BenjaminBossan** [comment]
Hmm, that's strange. Could you please try this:

```python
import json
import numpy as np
x = np.zeros(3, dtype=np.float32)
json.dumps(x[0])
json.dumps(x)
```

The two last lines result in `TypeError: Object of type float32 is not JSON serializable` for me on Ubuntu 18.04, Python 3.8.

**Comment by pdimitrov-thoughtriver** [comment]
Hi Benjamin,

Sorry for the late reply, have not looked recently at this issue at all. I have the same problem on ubuntu 20.04 + python 3.6.10:

Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import json 
   ...: import numpy as np 
   ...: x = np.zeros(3, dtype=np.float32) 
   ...: json.dumps(x[0]) 
   ...: json.dumps(x)                                                                                                                                                                                         
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-b3af85651af7> in <module>
      2 import numpy as np
      3 x = np.zeros(3, dtype=np.float32)
----> 4 json.dumps(x[0])
      5 json.dumps(x)

~/anaconda3/envs/latest_fathom/lib/python3.6/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    229         cls is None and indent is None and separators is None and
    230         default is None and not sort_keys and not kw):
--> 231         return _default_encoder.encode(obj)
    232     if cls is None:
    233         cls = JSONEncoder

~/anaconda3/envs/latest_fathom/lib/python3.6/json/encoder.py in encode(self, o)
    197         # exceptions aren't as detailed.  The list call should be roughly
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
    201             chunks = list(chunks)

~/anaconda3/envs/latest_fathom/lib/python3.6/json/encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258 
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

~/anaconda3/envs/latest_fathom/lib/python3.6/json/encoder.py in default(self, o)
    178         """
    179         raise TypeError("Object of type '%s' is not JSON serializable" %
--> 180                         o.__class__.__name__)
    181 
    182     def encode(self, o):

TypeError: Object of type 'float32' is not JSON serializable

**Comment by BenjaminBossan** [comment]
> Sorry for the late reply, have not looked recently at this issue at all. I have the same problem on ubuntu 20.04 + python 3.6.10:

Maybe I'm getting confused, but this is correct, is it not? I.e. since `np.float32` is not json serializable, it should cause an error during encoding, which prevents the creation of a corrupted json.

**Comment by pdimitrov-thoughtriver** [comment]
Apologies, Benjamin, misunderstood the intent of the previous post. I've only tried the code you suggested, and yes, it's clear that np.float32 is not JSON-serializable.

**Comment by BenjaminBossan** [comment]
No worries. Tbh I'm at a loss what happened during the initial issue. But I guess you found your workaround, so maybe it's not really worth investigating further.
