### ISSUE TITLE
How to dump the model trained with skorch to ONNX format?

### ISSUE THREAD

**Issue by quant-science** [skorch-dev/skorch#704]
The model is trained with skorch, if i want to put the model into production(the model production enviroment is using ONNX format), what should i do ?

**Comment by BenjaminBossan** [comment]
I haven't worked with ONNX but my guess is that you would only dump the PyTorch module itself. You can access it using the `net.module_` attribute.

Without the skorch model surrounding it, you will need your own data handling etc. If you could also work without ONNX, I would just pickle the whole net and use it in prod, but that might not be possible depending on your setup.

**Comment by quant-science** [comment]
Benjam, thanks for your quick feedback. I use the following demo code to dump the pytorch module .
`class RegressorModule(nn.Module):
    def __init__(self, num_units=10, dropout=0.5):
        super(RegressorModule, self).__init__()
        self.num_units = num_units
        self.dropout = torch.nn.Dropout(dropout)
        self.dense0 = nn.Linear(20, num_units)
        self.dense1 = nn.Linear(num_units, 10)
        self.output = nn.Linear(10, 1)

    def forward(self, X, **kwargs):
        X = F.relu(self.dense0(X))
        X = self.dropout(X)
        X = F.relu(self.dense1(X))
        X = self.output(X)
        return X

net_regr = NeuralNetRegressor(
    module=RegressorModule)

**for i,j in net_regr.module.named_parameters():
    print(i)**

`

**TypeError: named_parameters() missing 1 required positional argument: 'self'**

Any suggestions to dump the RegressorModule module? thanks

**Comment by BenjaminBossan** [comment]
Please use `net.module_` and not `net.module` (the former is the trained module instance, the latter the untrained module class).

**Comment by quant-science** [comment]
It works, thanks Benjam
