### ISSUE TITLE
using gpu with randomsearchcv

### ISSUE THREAD

**Issue by GTimothee** [skorch-dev/skorch#712]
Hi,

I am trying to use skorch to perform a randomsearchcv to find good hyperparameters. 

I am finetuning a resnet18 from torchvision. 

I create a net object following the tutorial in the docs, and I pass the "device='cuda:0'" parameter:
```
class PretrainedModel(nn.Module):
    def __init__(self, nb_classes):
        super().__init__()
        model = models.resnet18(pretrained=True)
        model.fc = nn.Linear(model.fc.in_features, nb_classes)
        self.model = model
        
    def forward(self, x):
        return self.model(x)

net = NeuralNetClassifier(
        PretrainedModel, 
        criterion=nn.CrossEntropyLoss,
        # lr=0.001,
        # batch_size=4,
        # max_epochs=1,
        module__nb_classes=len(class_names),
        optimizer=optim.SGD,
        # optimizer__momentum=0.9,
        iterator_train__shuffle=True,
        iterator_train__num_workers=4,
        iterator_valid__shuffle=True,
        iterator_valid__num_workers=4,
        train_split=predefined_split(val_ds),
        callbacks=[lrscheduler, checkpoint],
        device='cuda:0' # comment to train on cpu
    )
```

when I just perform a simple training using "net.fit(train_ds, y=None)" everything works fine. 

But when I want to use gridsearchcv using: 
```
gs = RandomizedSearchCV(net, params, refit=False, cv=3, scoring='accuracy')
gs.fit(train_ds, y=None)
```

then I do not see any gpu usage in "nvidia-smi". Does anyone know why ?

**Comment by BenjaminBossan** [comment]
Hmm, good question. It should work on the GPU, not sure what's happening here. From the training time, can you confirm that the GPU is really not being used?

Also, to help debugging, could you try to turn off every "unnecessary" extra and check if that fixes the problem? E.g.:

```
net = NeuralNetClassifier(
    PretrainedModel, 
    criterion=nn.CrossEntropyLoss,
    module__nb_classes=len(class_names),
    train_split=False,
    device='cuda:0' # comment to train on cpu
)
```

**Comment by GTimothee** [comment]
Thank you for your answer,
Finally I am not using skorch for the moment so I close this issue, but I will reopen it next time I want to use skorch
