### ISSUE TITLE
Unable to Clone repo

### ISSUE THREAD

**Issue by michelewang** [skorch-dev/skorch#720]
Hi, I'm trying to run the examples on my local machine but am running into an error when I try to clone this repository. Specifically, I get: 
git clone https://github.com/skorch-dev/skorch.git
fatal: could not create work tree dir 'skorch': Permission denied

Has anyone run into this before? How else did you run the code from the examples on your local machine?

**Comment by thomasjpfan** [comment]
You can clone the repo by running:

```bash
 git clone https://github.com/skorch-dev/skorch    
```
