### ISSUE TITLE
CSV Logging

### ISSUE THREAD

**Issue by cod3licious** [skorch-dev/skorch#726]
Not sure if I just overlooked something here... There are a bunch of useful looking logger callbacks (TensorBoard, Neptune, ...), but is there also an option to just write the results that are normally printed additionally to a simple csv file?

It looks like tabulate (used in the PrintLog) doesn't have a csv option yet (see [this issue](https://github.com/astanin/python-tabulate/issues/55)), but besides that it would be nice to have a little example somewhere on how to use the PrintLog to write the same results (minus the colors) to a file with a specific name.

**Comment by ottonemo** [comment]
Depending on what you need you can just convert the history to a pandas dataframe, modify it to your liking and export it to CSV, like so:

```python
net.fit(X, y)
df = pd.DataFrame(net.history).set_index('epoch')
df.write_csv('history.csv')
```

Would that meet your requirements?

**Comment by cod3licious** [comment]
Thanks for the quick reply! It might still be a bit nicer to have continuous logging to a file, e.g. when training happens in a job on a cluster, especially if that might crash for some reason before the whole history could be saved. But this is already very helpful!! :)

**Comment by BenjaminBossan** [comment]
> It might still be a bit nicer to have continuous logging to a file

Also take a look at the `sink` parameter ([docs](https://skorch.readthedocs.io/en/stable/callbacks.html#skorch.callbacks.PrintLog)), which you can replace with a function that writes to a file, a logger, or whatever you like (`print` being the default). This allows you to write your results continuously. Although, as you mentioned, you still don't have a csv format from tabulate, you may find another format that can easily be converted to csv later on.
