### ISSUE TITLE
How can I replicate the EpochScoring after training?

### ISSUE THREAD

**Issue by ricglz** [skorch-dev/skorch#742]
I want want to be able to calculate the same accuracy as the `EpochScoring`, but I'm unable to.

```
  epoch    train_acc    train_loss    valid_acc    valid_loss      lr       dur
-------  -----------  ------------  -----------  ------------  ------  --------
      1       0.6730        1.3965       0.6256        1.8170  0.0001  303.8801
```

This is my current output after training for one epoch. And I've tried to replicate the `valid_acc` value in 2 different ways but with no results

> Note the predefined split is an `ImageFolder` so I will use the targets for the real value

### Using predict

This one was the most straightforward, using predict I thought I would obtain the same accuracy

```python
pred = rexnet.predict(test_ds)
sk_metrics.accuracy_score(test_ds.targets, pred)
```

With this, I obtained a score of `0.5525`, definitely very different to the `valid_acc` shown in the logs even though is the same dataset

### Using forward_iter

```python
class MyClassifier(NeuralNetBinaryClassifier):
...
    def _get_y_values(self, X):
        y_pred = []
        nonlin = self._get_predict_nonlinearity()
        for yp in self.forward_iter(X, training=False):
            outputs = nonlin(yp)
            predicted = torch.argmax(outputs.data, dim=1)
            y_pred.append(to_numpy(predicted))
        y_pred = np.concatenate(y_pred)
        return X.targets, y_pred

    def score(self, X):
        y_true, y_pred = self._get_y_values(X)
        return sk_metrics.accuracy_score(y_true, y_pred)
...

net.score(test_ds)
```
 And this achieved `0.5569`

Am I doing something wrong? Is there something else I should do? If you need anymore code I could actually share a copy of the colab notebook I'm working on, the only problem would be the Dataset

**Comment by BenjaminBossan** [comment]
Your general approach looks sound to me. My first instinct for why there is a discrepancy is that you're not predicting on the exact same data as is being used for validation. Could you share how you define your `train_split` (or the whole notebook)?

**Comment by ricglz** [comment]
Sure here's [the notebook](https://colab.research.google.com/drive/1M-qqhV6nBwIJdaLfLVC_XICdsVk8aaqA?usp=sharing)

**Comment by BenjaminBossan** [comment]
Nice notebook, good to see someone using some of the more advanced features.

Regarding your problem, could try turning off the shuffling of the validation data:

```python
# remove this or set to false
iterator_valid__shuffle=True
```

**Comment by BenjaminBossan** [comment]
@ricglz did you have time to try my suggestion?

**Comment by ricglz** [comment]
Yeah, it seems like that was the problem, thanks!

**Comment by BenjaminBossan** [comment]
Great. Btw. we now warn users about this setting (#710).
