### ISSUE TITLE
How to use EpochScoring with Dataset

### ISSUE THREAD

**Issue by qmeeus** [skorch-dev/skorch#744]
Hi,
 
It is not clear to me how we can use EpochScoring with a custom Dataset object. The input to the scoring function always seem to be `None`. How can I prevent this?

The dataset looks like this:
```python
class SequenceDataset:

    def __init__(self, features, labels):
        self.features = features
        self.feature_lengths = [len(feats) for feats in self.features]
        self.labels = labels

        self.input_dim = self.features[0].shape[-1]
        self.output_dim = self.labels[0].shape[-1]

    def __getitem__(self, index):
        inputs = torch.tensor(self.features[index])
        input_lengths = torch.tensor(self.feature_lengths[index])
        labels = torch.tensor(self.labels[index])
        return inputs, input_lengths, labels

    def __len__(self):
        return len(self.features)
```

Other relevant stuff:
```python
def error_rate(y_true, y_pred):
    y_pred = y_pred[:, 1, :] > .5
    return 1 - (y_true == y_pred).all(-1).mean()

net = NeuralNet(
    ...
    callbacks=[
        EpochScoring(scoring=metrics.make_scorer(error_rate), lower_is_better=True),
    ]
)
```

Thank you very much

**Comment by BenjaminBossan** [comment]
That's strange, you mean that `y_true` and `y_pred` are `None`? Could check if adding the argument `use_caching=False` to the `EpochScoring` callback changes anything?

In general, I would not expect your code to work as is because your `__getitem__` does not return exactly 2 elements. Did you make any further changes that you didn't include in your code above?

**Comment by qmeeus** [comment]
Hi @BenjaminBossan

Only `y_true` is `None`, `y_pred` seems to be the output of `predict`, although for some reason, `predict` and `predict_proba` return a tensor of shape `(B, 2, K)` where `B` is the batch size, `K` is the output dimension of the model and 2 is the number of value that each output unit can take (multilabel binary classification).

You are right, I have a custom `data_collator` that I pass to the net constructor with `iterator_{train,valid}__collate_fn`. As you can see in the code below, it returns batches where each element is a tuple composed of a dictionary with the input and lengths and then the labels:
```python
    def data_collator(batch):
        """
        batch should be a list of (sequence, target, length) tuples...
        Returns a padded tensor of sequences sorted from longest to shortest,
        """
        batch, _ = map(list, zip(*batch))
        features, lengths, labels = map(list, zip(*batch))
        features = nn.utils.rnn.pad_sequence(features, batch_first=True, padding_value=0.)
        lengths = torch.stack(lengths, 0)
        labels = torch.stack(labels, 0)
        # See https://skorch.readthedocs.io/en/latest/user/neuralnet.html#multiple-input-arguments
        return {"inputs": features, "input_lengths": lengths}, labels
```

Setting `use_caching` to `False` gives me the following error:

```python
Traceback (most recent call last):
  File "train_smart_light.py", line 204, in <module>
    net.fit(dataset)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/net.py", line 903, in fit
    self.partial_fit(X, y, **fit_params)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/net.py", line 862, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/net.py", line 782, in fit_loop
    self.notify("on_epoch_end", **on_epoch_kwargs)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/net.py", line 325, in notify
    getattr(cb, method_name)(self, **cb_kwargs)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/callbacks/scoring.py", line 470, in on_epoch_end
    current_score = self._scoring(cached_net, X_test, y_test)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/callbacks/scoring.py", line 180, in _scoring
    return scorer(net, X_test, y_test)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 169, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true,
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 206, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 53, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/net.py", line 1159, in predict
    return self.predict_proba(X)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/net.py", line 1122, in predict_proba
    for yp in self.forward_iter(X, training=False):
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/net.py", line 964, in forward_iter
    dataset = self.get_dataset(X)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/net.py", line 1247, in get_dataset
    return dataset(X, y, **kwargs)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/dataset.py", line 156, in __init__
    self.X_indexing = check_indexing(X)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/utils.py", line 256, in check_indexing
    multi_indexing(data[0], 0)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/utils.py", line 338, in multi_indexing
    return check_indexing(data)(data, i)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/utils.py", line 215, in _indexing_list_tuple_of_data
    return [multi_indexing(x, i, indexing)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/utils.py", line 215, in <listcomp>
    return [multi_indexing(x, i, indexing)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/utils.py", line 335, in multi_indexing
    return indexing(data, i)
  File "~/bin/anaconda3/envs/espnet-stable/lib/python3.8/site-packages/skorch/utils.py", line 230, in _indexing_other
    return data[i]
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number
```

**Comment by BenjaminBossan** [comment]
Hmm, it's really tough to debug this without actually being able to run it. Could you elaborate on what your features and labels are (type, data type, shape)?

Meanwhile, maybe you could try out the following:

- determine your lengths once at the beginning: `lengths = np.array([len(feats) for feats in features])` (torch tensor also works)
- put your input features into a dict: `X_dict = {'inputs': features, 'input_lengths': lengths}`
- adjust your module's forward method to take arguments called `input` and `input_lengths`, like the dict keys (if not already the case)
- use the default collate function
- perform the `pad_sequence` inside of the module's `forward` method
- fit using the dict: `net.fit(X_dict, labels)`

**Comment by qmeeus** [comment]
I have here a minimal working example with random data:
https://gist.github.com/qmeeus/a1761836eecf382eb8b36ae218fa8dc8

I would really like to be able to use skorch out of the box with preexisting models, because this is what attracted me originally in this library.

I found that the error caused by `use_caching=False` was due to not subclassing the dataset class. I guess that there is a check, something like `isinstance(X, torch.utils.data.Dataset)` that failed where it should not have. The original error (passing `None` instead of the labels to scoring function) remains though. It can be verified in the code snippet with the assertion at line 98:
```python
  File "test_skorch.py", line 98, in error_rate
    assert y_true is not None
AssertionError
```

**Comment by BenjaminBossan** [comment]
In your example, if I set `use_caching=True` (i.e. the default), it works for me. Could you try to confirm that?

The reason why `y` is None is that skorch tries to extract it from your custom dataset but doesn't know how, so it falls back to None. If you use a `skorch.dataset.Dataset` and use the attribute names `X` and `y` for your input and target data, skorch will know.

However, I would approach this whole problem differently. Instead of padding on the fly, which creates some overhead, I would rather pad the data once before passing it to fit and then just use the default collate function. In skorch, if you want to have an `X` that consists of multiple inputs, you can use a [dictionary](https://skorch.readthedocs.io/en/stable/user/neuralnet.html?highlight=multiple#multiple-input-arguments):

```python
features, target = generate_random_data()
padded = nn.utils.rnn.pad_sequence(
    [torch.as_tensor(x, dtype=torch.float32) for x in features], batch_first=True, padding_value=0.)
lengths = np.array([len(x) for x in features])
X = {'inputs': padded, 'input_lengths': lengths}  # Note: keys match argument names in forward method

net = NeuralNet(
    module=AttentiveRecurrentDecoder,
    module__input_dim=dataset.input_dim,
    module__output_dim=dataset.output_dim,
    module__d_model=64,
    criterion=nn.BCEWithLogitsLoss,
    batch_size=64,
    max_epochs=50,
    lr=0.2,
    callbacks=[
        EpochScoring(scoring=metrics.make_scorer(error_rate), lower_is_better=True, use_caching=False),
        EpochScoring(scoring=metrics.make_scorer(accuracy), lower_is_better=False, use_caching=True),
        EarlyStopping(monitor="valid_loss", patience=5),
        LRScheduler(policy="ReduceLROnPlateau", patience=3)
    ],
    device="cpu"
)

net.fit(X, target)
```

In this example, I used both `caching=True` and `caching=False` for demonstration purposes, but obviously you should either always use it (recommended except if memory is a problem) or not.

Btw., your module doesn't use the `input_lengths`. Not sure if you simplified it here, but if you don't actually need it, there is also no need to use a dict.

**Comment by qmeeus** [comment]
You are right on both accounts:

- Setting `caching` to `True` works. The key was to make sure that the `Dataset` class inherited from `torch.utils.data.Dataset`. I have not yet tried to subclass `skorch.dataset.Dataset` but this is on my todo list

- I forgot to use `input_lengths`, which are used in conjunction with `nn.utils.rnn.pack_padded_sequence`. The reason why I want to pad the batches on the fly is because I have sequences of various lengths in my dataset and I prefer to save some memory by padding to the batch's max length rather than the whole training set. Additionally, the `SequenceDataset` is a bit simplified and I sometimes use lazy loading because some datasets are too large to fit entirely in memory. 

Thank you for the amazing library and for your answers, it was extremely helpful!

**Comment by BenjaminBossan** [comment]
>     * I forgot to use `input_lengths`, which are used in conjunction with `nn.utils.rnn.pack_padded_sequence`. The reason why I want to pad the batches on the fly is because I have sequences of various lengths in my dataset and I prefer to save some memory by padding to the batch's max length rather than the whole training set.

Okay, that makes total sense. If you have further questions feel free to ask.

> Thank you for the amazing library and for your answers, it was extremely helpful!

Thanks, glad to hear that.
