### ISSUE TITLE
How can I achieve non-random train/valid split?

### ISSUE THREAD

**Issue by ray38** [skorch-dev/skorch#747]
Hi all,

Long story short,  for a specific project, in order to train with huge amount of pre-shuffled data efficiently, we are trying to look for a way to do train/valid split in a non-random way with skorch, but the current CVSplit class doesn't seem to support it. i.e. if I want val_split = 0.1, I want it just take the last (or first) 10% as the validation set, so that their indices are still in order after split.

Is there a way to achieve this with existing tools, or do I need to write a custom class for train_split? if so, what methods are needed for the class?

Thanks a lot!

**Comment by BenjaminBossan** [comment]
Hi, skorch uses several heuristics to determine what kind of splitting strategy is best based on the parameters and data. Most of that is itself delegated to sklearn's `check_cv`. So I cannot give you a direct answer unless I know what parameters you use and what type of data you're dealing with. However, if you pass `train_split=CVSplit(KFold(10))` (with `KFold` being `sklearn.model_selection.KFold`), you might get exactly what you asked for.

> do I need to write a custom class for train_split?

This is actually easier than it may sound. You can pass a function to `train_split`. That function must have the following signature:

```python
def my_split(dataset, y, **fit_params):
    # split my data somehow
    return dataset_train, dataset_valid
```

So you basically accept a dataset and return the two split datasets (usually based on the incoming dataset). In the function body, you can split the data easily as you described above. `torch.utils.data.Subset` could come in handy for that.

**Comment by ray38** [comment]
@BenjaminBossan Thank you so much for your help!

I wrote the following custom splitter and it worked well

```
class InOrderSplit:
    def __init__(self, val_frac):
        self.val_frac = val_frac

    def __call__(self, dataset):
        len_dataset = len(dataset)
        len_val = int(len_dataset * self.val_frac)
        len_train = len_dataset - len_val
        train_idx = list(range(0, len_train))
        val_idx = list(range(len_train, len_dataset))
        train_dataset = torch.utils.data.Subset(dataset, train_idx)
        val_dataset = torch.utils.data.Subset(dataset, val_idx)
        return train_dataset, val_dataset
```

just to make sure, in case I missed it, even with the original CV splitter, it was only split once right (i.e. valid set stays constant between different epochs)?

**Comment by BenjaminBossan** [comment]
> I wrote the following custom splitter and it worked well

This looks good.

> just to make sure, in case I missed it, even with the original CV splitter, it was only split once right (i.e. valid set stays constant between different epochs)?

Exactly. Even if there was randomness in your train split, since it's only called once at the start of `fit`, the split would stay constant during the training (except, obviously, if you call fit twice).

**Comment by BenjaminBossan** [comment]
It looks like this issue has been solved. Feel free to re-open if another question comes up.

**Comment by ray38** [comment]
@BenjaminBossan Hey Ben, I do have a quick follow up question if you don't mind:
does this "inorder" play well with iterator_train__shuffle?
for example, I have a dataset of 10M,  and want to use the last 1M for validation, but I still want the 9M training data to be re-shuffled every epoch. would it be simply turn on iterator_train__shuffle with the in-order sampler (and it won't mess up my val_split order), or do I maybe need to write a customized sampler to do this?

**Comment by BenjaminBossan** [comment]
The train/valid split happens _before_ the `Dataset`s are passed to their respective  `DataLoader`s, and since shuffling happens inside the `DataLoader`, everything works as expected.

**Comment by ray38** [comment]
That makes sense, Thanks a lot!

**Comment by MagicPatze** [comment]
I have seen this issue when I was running into the same problem, only that I do want to randomly shuffle the data. 

I do not know why, but I programmed 2 different versions but none worked. The first one is quite similar to the one presented before : 
```python
class RNGSampler: 
  def __init__(self, validperc): 
    self.validperc = validperc

  def __call__(self, x, y): 
    """
    validperc: rel. size valid set
    """
    self.x = x
    self.y = y 
    validperc = self.validperc

    # shuffle data
    xs, ys = shuffle(x,y, random_state= 7)
    dataset = np.concatenate((xs,ys), axis=1)

    train_idx = range(0,int(validperc*dataset.shape[0]))
    val_idx = range(int(validperc*dataset.shape[0]), dataset.shape[0])

    train_dataset = torch.utils.data.Subset(dataset, train_idx)
    val_dataset = torch.utils.data.Subset(dataset, val_idx)

    return train_dataset, val_dataset
```
And I call the class like this: 
```python 
sampler = RNGSampler(validperc=0.1)
nn = NeuralNetRegressor(NeuralNet, verbose=0, train_split = sampler(x = x, y = y))
```

In the other version I was relying on the skorch documntation saying that the format of the train and validation dataset can also be arrays: 

```python 
class Sampler: 
  def __init__(self, x, y):
    self.x = x
    self.y = y

  def randomsplit(self,validperc): 
    """
    validperc: rel. size valid set
    """
    self.validperc = validperc
    x = self.x 
    y = self.y 

    # shuffle data
    xs, ys = shuffle(x,y, random_state= 7)

    x_valid = xs[:int(validperc*xs.shape[0]),:]
    y_valid = ys[:int(validperc*ys.shape[0]),:]

    x_train = xs[int(validperc*xs.shape[0]):,:]
    y_train = ys[int(validperc*ys.shape[0]):,:]

    valid_array = np.concatenate((x_valid, y_valid), axis = 1)
    train_array = np.concatenate((x_train, y_train), axis= 1)

    return train_array, valid_array 
```
And I used it like this: 
```python
sampler = Sampler(x, y)
nn = NeuralNetRegressor(NeuralNet, verbose=0, train_split = sampler.randomsplit(validperc = 0.1)
```

However, in both of these examples I get the same error which is: 
```python 
TypeError: 'tuple' object is not callable
```
Is there anything obvious I am not seeing?
