### ISSUE TITLE
how to convert data type

### ISSUE THREAD

**Issue by xiaolongwu0713** [skorch-dev/skorch#758]
Hi, I put my training data in a pytorch dataset and feed to skorch like below:
`net.fit(train_ds,y=None)`
However it gives me below error:
```
Re-initializing optimizer.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-23-c7f7e2f1acab> in <module>()
----> 1 net.fit(train_ds,y=None)

18 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py in _conv_forward(self, input, weight, bias)
    394                             _pair(0), self.dilation, self.groups)
    395         return F.conv2d(input, weight, bias, self.stride,
--> 396                         self.padding, self.dilation, self.groups)
    397 
    398     def forward(self, input: Tensor) -> Tensor:

RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same
```

I checked the numpy array is float32 before I put it into dataset. 
How can I convert it to float? or how to solve this?

**Comment by BenjaminBossan** [comment]
Inside the `train_ds`, the input data is float32 but later its float64? That's strange. skorch does not change the dtype on its own. I'm afraid I can't give you any good tips here except to jump into the debugger to trace back at which point the conversion happens. If you could share the whole code, I might also take a look.

**Comment by xiaolongwu0713** [comment]
I have to explicitly convert it like below to solve the problem:

`return x.astype(np.float32),y.astype(np.float32)
`
