### ISSUE TITLE
default lower_is_better in EarlyStopping callback inconsistent with sklearn

### ISSUE THREAD

**Issue by xiaolongwu0713** [skorch-dev/skorch#765]
Hi, 
Do you think it would be better idea to set the lower_is_better=False in EarlyStopping callback in order to be consistent with sklearn scoring function convention that higher return values are better than lower return values?
https://scikit-learn.org/stable/modules/model_evaluation.html#common-cases-predefined-values

**Comment by BenjaminBossan** [comment]
If you suggest to change the default: I don't think so. We have to marry two standards here, sklearn and PyTorch (or deep learning in general). For the latter, the objective is minimized by default, so if we changed the default, it would do the wrong thing most of the time.

**Comment by BenjaminBossan** [comment]
I assume the question has been answered. If not, feel free to re-open.
