### ISSUE TITLE
Add MLflow builtin callback

### ISSUE THREAD

**Issue by cacharle** [skorch-dev/skorch#769]
MLflow website: <https://mlflow.org/>

I'll be happy to implement it myself if you want.

**Comment by ottonemo** [comment]
Hi! Sounds great :)

There are a few loggers implemented (https://github.com/skorch-dev/skorch/blob/master/skorch/callbacks/logging.py#L733) and tested (https://github.com/skorch-dev/skorch/blob/master/skorch/tests/callbacks/test_logging.py#L19) already, I think you can base your implementation on those if you want.
