### ISSUE TITLE
Point module to module_

### ISSUE THREAD

**Issue by marcosfelt** [skorch-dev/skorch#777]
Currently, when you call `module` on a NeuralNet or NeuralNetRegressor, you get the uninitialized module instead of the initialized one.   Would it be a good idea to put some documentation about this or create a property that points module to module_?

See https://github.com/skorch-dev/skorch/blob/1673a89c0baf71b44fe3cbdc3d34bcca7970f889/skorch/net.py#L545

**Comment by BenjaminBossan** [comment]
Yes, this is a very deliberate design choice. We leave the input arguments to the net untouched, whereas attributes that are changed are suffixed with an underscore. This is more or less in line with sklearn conventions. Therefore, `module` should not point to `module_`.

When it comes to the documentation, we mention it in the docstring (though it could be more explicit) and [here](https://skorch.readthedocs.io/en/stable/user/neuralnet.html#initialization), for instance. Still, if you have a suggestion how we can improve the docs, feel free to share it or to create a PR.
