### ISSUE TITLE
Allow one EpochScoring callback to score both train and validation dataset

### ISSUE THREAD

**Issue by cacharle** [skorch-dev/skorch#780]
Currently we can only choose one of the two. It would be nice if we could score both dataset with one callback and add suffix to the score names like `_train` and `_valid`.

**Comment by BenjaminBossan** [comment]
What would be the advantage compared to having two separate callbacks, one for train and one for valid?

**Comment by cacharle** [comment]
A cleaner interface when we need the score for both sets.

I want all my metrics to be run on both sets and also suffix them either by `_train` or `_valid` depending on which it's ran on.
I do have a helper which creates 2 callbacks but it feel like something which should be handled by the library.

**Comment by BenjaminBossan** [comment]
> I do have a helper which creates 2 callbacks

You could share the code here for future users who may want the same solution.

> but it feel like something which should be handled by the library.

I disagree here, I believe this is easy enough to achieve as a user and AFAICT, having the possibility to combine both doesn't seem to provide a big benefit (say, higher runtime performance).
