### ISSUE TITLE
Sharpness Aware Minimization

### ISSUE THREAD

**Issue by robintibor** [skorch-dev/skorch#785]
Hi, thanks so much for maintaining a scikit-learn compatible PyTorch framework.

We were wondering what would you consider the best way to use Sharpness Aware Minimization (https://github.com/davda54/sam https://arxiv.org/abs/2010.01412) together with skorch. How would one go to implement it in the cleanest way?

For some context, we are using skorch in our EEG deep learning framework [Braindecode](https://github.com/braindecode/braindecode/) and would like to evaluate some recent well-performing deep learning training improvements on our EEG datasets.

**Comment by ottonemo** [comment]
Hi!

Interesting question, it seems to me that there is minimal effort involved to make this work with skorch.

The SAM optimizer has support for the closure-style invocation which is very close to what skorch uses internally to support optimizers like LGBFS. This means that it should work basically out of the box. Their example is this:

```
from sam import SAM
...

model = YourModel()
base_optimizer = torch.optim.SGD  # define an optimizer for the "sharpness-aware" update
optimizer = SAM(model.parameters(), base_optimizer, lr=0.1, momentum=0.9)
...

for input, output in data:
  def closure():
    loss = loss_function(output, model(input))
    loss.backward()
    return loss

  loss = loss_function(output, model(input))
  loss.backward()
  optimizer.step(closure)
  optimizer.zero_grad()
```

I haven't tested this but I think the equivalent skorch usage would look like this:

```
net = skorch.NeuralNet(
    model,
    optimizer=SAM,
    optimizer__base_optimizer=torch.optim.SGD,
    optimizer__lr=0.1,
    optimizer__momentum=0.9,
)
```

As mentioned before, skorch already supports the `optimizer.step(closure)` API of pytorch and as this is exactly what is used in the SAM example, everything should work as expected.

We are zeroing gradients in each `step_fn` call and I checked with the SAM implementation if that is something that concurs with their ideas - it seems to me that it does. Before calling the closure the gradients are zeroed anyway.

Give it a try and report back, it seems to be an interesting application and if there are any problems we are interested in fixing them :)

**Comment by ottonemo** [comment]
@robintibor Did this resolve your question?

**Comment by robintibor** [comment]
Hi, thanks for the answer, just had a brief test of your suggestion but could not make it work:
https://colab.research.google.com/drive/1U9s-UCHac6rwJOh8i9_KaAkUffVvE7YF?usp=sharing

```python
import torch
from sam.sam import SAM
import numpy as np
from sklearn.datasets import make_classification
from torch import nn

from skorch import NeuralNetClassifier


X, y = make_classification(1000, 20, n_informative=10, random_state=0)
X = X.astype(np.float32)
y = y.astype(np.int64)

class MyModule(nn.Module):
    def __init__(self, num_units=10, nonlin=nn.ReLU()):
        super(MyModule, self).__init__()

        self.dense0 = nn.Linear(20, num_units)
        self.nonlin = nonlin
        self.dropout = nn.Dropout(0.5)
        self.dense1 = nn.Linear(num_units, num_units)
        self.output = nn.Linear(num_units, 2)
        self.softmax = nn.Softmax(dim=-1)

    def forward(self, X, **kwargs):
        X = self.nonlin(self.dense0(X))
        X = self.dropout(X)
        X = self.nonlin(self.dense1(X))
        X = self.softmax(self.output(X))
        return X


net = NeuralNetClassifier(
    MyModule,
    max_epochs=10,
    optimizer=SAM,
    optimizer__base_optimizer=torch.optim.SGD,
    optimizer__lr=0.1,
    optimizer__momentum=0.9,
    # Shuffle training data on each epoch
    iterator_train__shuffle=True,
)

net.fit(X, y)

->
---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-2-20932a6b5c8a> in <module>()
     42 )
     43 
---> 44 net.fit(X, y)

11 frames

/content/sam/sam.py in _grad_norm(self)
     51                     torch.stack([
     52                         ((torch.abs(p) if group["adaptive"] else 1.0) * p.grad).norm(p=2).to(shared_device)
---> 53                         for group in self.param_groups for p in group["params"]
     54                         if p.grad is not None
     55                     ]),

RuntimeError: stack expects a non-empty TensorList
```

**Comment by ottonemo** [comment]
Ah, yes - I thought that the SAM implementation will use the `step_fn` for the first and the second call but it does not, so it seems. That's why the list is empty, there are at that time no parameters with gradients present to estimate the 'sharpness'.

The simplest solution would be to call `train_step_single` twice, so that there are gradients present before
optimizer invocation:

```python
class SAMClassifier(skorch.NeuralNetClassifier):
    def train_step(self, batch, **fit_params):
        self.train_step_single(batch, **fit_params)
        return super().train_step(batch, **fit_params)
```

Full example:

```python
class SAMClassifier(skorch.NeuralNetClassifier):
    def train_step(self, batch, **fit_params):
        self.train_step_single(batch, **fit_params)
        return super().train_step(batch, **fit_params)

net = SAMClassifier(
    MyModule,
    max_epochs=10,
    optimizer=SAM,
    optimizer__base_optimizer=torch.optim.SGD,
    optimizer__lr=0.1,
    optimizer__momentum=0.9,
    # Shuffle training data on each epoch
    iterator_train__shuffle=True,
)

net.fit(X, y)
```

**Comment by robintibor** [comment]
but it would also be possible to change SAM optimizer code to work as you originally planned? to avoid needing a separate classifier for SAM?

**Comment by ottonemo** [comment]
I think so, yes. Basically what would need to happen is that the closure is called twice, once for the first optimization step (estimating sharpness) and a second time for the actual gradient computation. This would of course be as inefficient as calling `train_step_single` twice but performance seems secondary here.

**Comment by ottonemo** [comment]
I had a closer look at the SAM implementation and the closure invocation does the following:

```python
    def step(self, closure=None):
        # ...
        self.first_step(zero_grad=True)
        closure()
        self.second_step()
```

Adding a second `closure()` before `self.first_step` would make this work the way I outlined it at first.

I think the reason why there are two steps is that there are cases where the sharpness estimate is circumstantial, for example the README outlines a case where training with multiple GPUs makes it necessary to compute sharpness locally (per GPU) and then combine the results in the final backward pass. So the cleanest way would be to adhere to the calling scheme and to modify skorch's train step. You could make it conditional to the SAM optimizer:

```python
class SAMClassifier(skorch.NeuralNetClassifier):
    def train_step(self, batch, **fit_params):
        # provide gradients for SAM optimizer to estimate sharpness of loss landscape
        if isinstance(self.optimizer, sam.SAM):
            self.train_step_single(batch, **fit_params)
        return super().train_step(batch, **fit_params)
```

I hope this helps.

**Comment by BenjaminBossan** [comment]
Since there were no further replies for a year, I assume the issue is solved :) Feel free to re-open in case it's not.
