### ISSUE TITLE
Light History

### ISSUE THREAD

**Issue by PierreGtch** [skorch-dev/skorch#791]
Hi all,
I think it could be useful to be able to save a lightened version of the `History` that would only contain epoch-level variables and forget about the batch-level ones.
This would be handy when, for example, you run experiments on a cluster and want to only download the `History` objects for analysis. Depending on your dataset shape and the metrics you record, the histories can easily weigh several hundred megabytes.

It can already be done:
```python
light_history = History()
for i in range(len(history)):
    light_history.new_epoch()
    for k in history[i].keys():
        if k=='batches':
            continue
        light_history.record(k,history[i,k])
light_history.to_file('light_history.json')
```
But it forces to copy everything before saving. There could be a more integrated way to do this.

**Comment by BenjaminBossan** [comment]
Under the hood, the `history` object is basically a list of dicts. Therefore, if you don't care about mutating it, you can just delete the `'batches'` key from each epoch:

```python
for row in net.history:
    del row['batches']
```

You could even write a simple callback that deletes the batches each time `on_epoch_end` if you're worried about the size.

**Comment by PierreGtch** [comment]
Ok, thank you for the help
