### ISSUE TITLE
MlflowLogger absent in the latest release when pip install

### ISSUE THREAD

**Issue by eunbeejang** [skorch-dev/skorch#797]
Hello,

I've pip install the latest release (0.10.0) but MlflowLogger #770 is not there. Are you planning to update it soon?

Thank you

**Comment by BenjaminBossan** [comment]
Indeed, there hasn't been a release since the `MlflowLogger` was released. You could install the skorch master branch directly from github as explained [here](https://stackoverflow.com/a/20101940), if you don't mind the small risk of something changing on master that might impact your work.

**Comment by BenjaminBossan** [comment]
We released version 0.11 two weeks ago. When installing skorch with pip, you should therefore be able to use the `MlflowLogger`.
