### ISSUE TITLE
NeuralNetClassifier cannot fit tensor labels because of NeuralNetClassifier.check_data

### ISSUE THREAD

**Issue by TheAutumnOfRice** [skorch-dev/skorch#802]
A small bug.
Ver. 0.10.0
In classifier.py / Line 107-120: (NeuralNetClassifier.check_data)
```python
    def check_data(self, X, y):
        if (
                (y is None) and
                (not is_dataset(X)) and
                (self.iterator_train is DataLoader)
        ):
            msg = ("No y-values are given (y=None). You must either supply a "
                   "Dataset as X or implement your own DataLoader for "
                   "training (and your validation) and supply it using the "
                   "``iterator_train`` and ``iterator_valid`` parameters "
                   "respectively.")
            raise ValueError(msg)
        if y is not None:
            self.classes_inferred_ = np.unique(y)
```
The line 120 `np.unique(y)` limits that `y` should be numpy array but not torch tensor. As Y cannot be cuda tensors, the numpy array `y`  goes through `to_device` function in every epoch, wasting a lot of time.

I think it might be better if `np.unique` or `torch.unique` can be automatically selected according to the type of y.

**Comment by BenjaminBossan** [comment]
Thank you for reporting.

> I think it might be better if `np.unique` or `torch.unique` can be automatically selected according to the type of y.

That sounds reasonable. Would you like to work on that?

**Comment by TheAutumnOfRice** [comment]
@BenjaminBossan 
Thanks for your replying.
I manage to make a pull request. #803 
Hope it helps!

**Comment by BenjaminBossan** [comment]
Solves via #803
