### ISSUE TITLE
Question: Restart training? 

### ISSUE THREAD

**Issue by JakobRiber** [skorch-dev/skorch#812]
Hello

I work with small ANN's and would like to implement two callbacks: 
1) One to retrain my model X amount of times, return the best one. 
2) One which restarts training X amount of times if it encounters a nan in the history. 

I have implemented my own callbacks before, but I fail to see the logic with this one.
In particular I don't know which of the initializers to use, and if this is the correct way to "restart" training? 

Any inputs would be highly appreciated!

**Comment by JakobRiber** [comment]
Hello @ottonemo  apologies for not following up, I solved the "problem" by reformulating my problem and doing it in an outside loop. 
My original idea was having a lot ``GridSearchCV's`` for different models, so I would like to have them all with the same syntax, i.e. one which would allow me to get the ``.cv_results_`` and ``.predict()`` functionality. 
And I actually found out, that one can specify a list of  dictionaries to the ``GridSearchCV`` and it will then fit them independently, so one could basically just repeat the first parameters N_repetition number of times. 

Regarding number two. 
I train some rather small ANN's (1-10 layers, 1-200 neurons) with the LBFGS solver and uses ``BayesSearchCV`` and 9/10 times it converges faster and better. But sometimes it gets stuck, or explodes and gives Nan's, both because of poor hyperparameter combinations, but sometimes it also happens for good combinations, which messes up the score for those hyper parameter combinations, and thus biases the ``BayesSearchCV`` .. Most times just restarting training solves the issue. So I wanted to catch that. 
But I recon that this should probably just be solved outside the loop aswell, so you can just check this as solved. :)

**Comment by BenjaminBossan** [comment]
Okay, we'll close the issue for now. Feel free to re-open if you have more questions.
