### ISSUE TITLE
load_best fails when parallelism is enabled

### ISSUE THREAD

**Issue by dnwissel** [skorch-dev/skorch#819]
Hi,

I was really happy to see that the new `load_best` parameter for `Checkpoint` was officially released a few days ago. Unfortunately, I have encountered issues when running in parallel (seems to be related to all histories being written to the same location?).

Reproducible example:

Single-core works fine:

```py
import skorch
import torch
from sklearn.model_selection import GridSearchCV
from skorch.callbacks import Checkpoint

X = torch.ones(10, 1)
y = torch.ones(10, 1)
model = skorch.net.NeuralNet(
    torch.nn.Linear(1, 1),
    criterion=torch.nn.MSELoss,
    callbacks=[
        ("cp", Checkpoint(load_best=True)),
    ],
    max_epochs=100,
    verbose=0
)

param_grid = {"lr": [0.01, 0.001]}
grid = GridSearchCV(model, param_grid, scoring="r2", cv=2, n_jobs=1)
grid.fit(X, y)
```

But as soon as n_jobs is increased, I start hitting failed estimators:

```py
import skorch
import torch
from sklearn.model_selection import GridSearchCV
from skorch.callbacks import Checkpoint

X = torch.ones(10, 1)
y = torch.ones(10, 1)
model = skorch.net.NeuralNet(
    torch.nn.Linear(1, 1),
    criterion=torch.nn.MSELoss,
    callbacks=[
        ("cp", Checkpoint(load_best=True)),
    ],
    max_epochs=100,
    verbose=0
)

param_grid = {"lr": [0.01, 0.001]}
grid = GridSearchCV(model, param_grid, scoring="r2", cv=2, n_jobs=-1)
grid.fit(X, y)
```

```
/Users/slightlier/miniforge3/envs/thesis/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/Users/slightlier/miniforge3/envs/thesis/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/slightlier/miniforge3/envs/thesis/lib/python3.9/site-packages/skorch/net.py", line 1215, in fit
    self.partial_fit(X, y, **fit_params)
  File "/Users/slightlier/miniforge3/envs/thesis/lib/python3.9/site-packages/skorch/net.py", line 1177, in partial_fit
    self.notify('on_train_end', X=X, y=y)
  File "/Users/slightlier/miniforge3/envs/thesis/lib/python3.9/site-packages/skorch/net.py", line 359, in notify
    getattr(cb, method_name)(self, **cb_kwargs)
  File "/Users/slightlier/miniforge3/envs/thesis/lib/python3.9/site-packages/skorch/callbacks/training.py", line 196, in on_train_end
    net.load_params(checkpoint=self)
  File "/Users/slightlier/miniforge3/envs/thesis/lib/python3.9/site-packages/skorch/net.py", line 2402, in load_params
    self.history = History.from_file(checkpoint.f_history_)
  File "/Users/slightlier/miniforge3/envs/thesis/lib/python3.9/site-packages/skorch/history.py", line 229, in from_file
    return cls(json.load(fp))
  File "/Users/slightlier/miniforge3/envs/thesis/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Users/slightlier/miniforge3/envs/thesis/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/slightlier/miniforge3/envs/thesis/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/slightlier/miniforge3/envs/thesis/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 8182 (char 8181)
```

I am on an M1 MBP with Python 3.9.7 and skorch 0.11.0. For me the issue isn't extremely pressing, and I haven't really had time to dig into the logic too deeply yet, but at least out of the box, things don't seem to work for me with parallelism enabled.

Would be curious if anyone has any idea whether this is fixable as-is or whether I'm just doing something wrong. Thanks in advance and happy to provide any more details!

**Comment by dnwissel** [comment]
Update: I just tested the new `load_best` parameter that was added to `EarlyStopping` on the `master` today and it seems to work properly on both simulated data (see below) and my own data. 

Reproducible example:

```py
import os
import random

import numpy as np
import skorch
import torch
from sklearn.model_selection import GridSearchCV
from skorch.callbacks import EarlyStopping


def seed_torch(seed=42):
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


seed_torch()
X = torch.randn(100, 1)
y = torch.randn(100, 1)
model = skorch.net.NeuralNet(
    torch.nn.Sequential(
        torch.nn.Linear(1, 1), torch.nn.ReLU(), torch.nn.Linear(1, 1)
    ),
    criterion=torch.nn.MSELoss,
    callbacks=[
        ("cp", EarlyStopping(load_best=True)),
    ],
    max_epochs=100,
    verbose=0,
)


param_grid = {"lr": [10, 1, 0.1, 0.01, 0.001]}
grid = GridSearchCV(model, param_grid, scoring="r2", cv=5, n_jobs=-1)
grid.fit(X, y)

print(grid.best_score_)
print(grid.best_params_)
```

The above now gives the same results when either using parallelism or not (i.e., whether `n_jobs > 1` or not), while the same using `Checkpoint(load_best=True)` works only without parallelism. 

@cedricrommel just out of curiosity if you have time to look at this: Is the above correct with respect to the new `load_best` parameter in `EarlyStopping`, i.e., should it be able to be used within a CV even when `n_jobs > 1`?

Thanks a bunch!

**Comment by BenjaminBossan** [comment]
Thank you for reporting the error. I'm not exactly sure why the loading fails with the error you pasted, but it's not hard to imagine that when you have different jobs trying to write to and read from the same file (`Checkpoint` stores the data in files), there is potential for conflicts. In contrast, stores `EarlyStopping` the model weights as an attribute, which is why it works.

Note that `EarlyStopping` only stores the weights of your module whereas `Checkpoint` can store other stuff like the optimizer or the history. Actually, the error you get is coming from the history object, so when you set `Checkpoint(load_best=True, f_history=None)`, the error goes away (at least when I'm testing).

However, I'm not sure if this is safe to use, since the problem of concurrent processes writing to and reading from the same fail doesn't disappear. Maybe we could allow a callable as a filename so that when called creates a random filename and thus avoid the conflict.

Anyway, I think using `EarlyStopping` is probably more appropriate for what you're trying to achieve. `Checkpoint` is not really intended to be used in conjunction with grid search. So as long as restoring only the model weights is enough for you, you should be fine.

**Comment by dnwissel** [comment]
Great, as you said, I think for my use case the usage of `EarlyStopping` directly makes more sense anyway. 

So from my side this is resolved, would you prefer me to keep it open to keep track of the (potential) issue, otherwise I will close?

**Comment by BenjaminBossan** [comment]
Let's close for now, since the specific problem seems to be solved.
