### ISSUE TITLE
question about transfer learning

### ISSUE THREAD

**Issue by yifnzhao** [skorch-dev/skorch#823]
Hi, 
Thanks for developing skorch! I have a question regarding transfer learning. In the [tutorial](https://github.com/skorch-dev/skorch/blob/master/notebooks/Transfer_Learning.ipynb), it shows how to load resnet18 and connect to a fully connected layer. I am trying to do transfer learning with a model trained with skorch framework, and so I am wondering what would be the equivalent of 
```
model_conv = models.resnet18(pretrained=True)
for param in model_conv.parameters():
    param.requires_grad = False
num_ftrs = model_conv.fc.in_features
model_conv.fc = nn.Linear(num_ftrs, 2)
``` 
in skorch.

Many thanks,
Yifan

**Comment by BenjaminBossan** [comment]
skorch models are not different than PyTorch models. When you have a trained net, you can access the PyTorch module using the `module_` attribute. E.g.:

```python
net = NeuralNet(...)
net.fit(X, y)
model_conv = net.module_
```

The specific names of the model parameters, e.g. `in_features` and `fc` depend on how you defined your module, so they may differ.

**Comment by yifnzhao** [comment]
Thank you!
