### ISSUE TITLE
Using callbacks and using 'nested' parameters in GridSearchCV 

### ISSUE THREAD

**Issue by MagicPatze** [skorch-dev/skorch#825]
Hello everyone! 

I want to use the callback function in order to implement an lr_scheduler. 
The relevant imports for this part of my script are the following: 
```python
from torch import optim
from torch.optim.lr_scheduler import CyclicLR, LinearLR
from sklearn.model_selection import GridSearchCV
from skorch import NeuralNetRegressor
from skorch.callbacks import LRScheduler
```
Then, quite similar to the [(basic usage tutorial)](https://nbviewer.org/github/skorch-dev/skorch/blob/master/notebooks/Basic_Usage.ipynb) I implement firstly a NeuralNetRegressor (as my problem is a regression problem) and include the callback as follows: 
``` python
nn = NeuralNetRegressor(NeuralNet, 
			callbacks = [('lr_scheduler', LRScheduler(policy=CyclicLR, base_lr = 0.001, max_lr = 0.01)),],
	                verbose=0, train_split = False)
```

I directly insert the regressor into the GridSearch and don't make use of a pipeline. 
The Hyperparameters I set like this: 
```python 
params = {
         	'max_epochs':[100],
		'lr': [0.01],
		'module__num_variables': [nn_num_variables],
                'module__hl_sizes': [[20,20,10]],
		'optimizer': [optim.Adam, optim.SGD],
		'callbacks__lr_scheduler__policy': [CyclicLR, LinearLR]
                }
```

And finally, the Gridsearch: 
```python 
gs = GridSearchCV(nn, params, refit=False, cv=2, verbose=5)
```

My problem is, that the output for me is the following: 
```python
ValueError: optimizer must support momentum with `cycle_momentum` option enabled
warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Florian\anaconda3\envs\jlhiwi\lib\site-packages\sklearn\model_selection\_search.py:969: UserWarning: One or more of the test scores are non-finite: [        nan -0.00073714]
  warnings.warn(
Backend Qt5Agg is interactive backend. Turning interactive mode on.
```

So, after making some research, I found that Adam can not work with an LRScheduler that cycles the momentum. 

Therefore, my question is: 
Can I set a hyperparameter, that is nested, with GridSearch? For example, now I would try to set the parameter 'cycle_momentum', but its a parameter that exists only if the lr_scheduler is CycleLR. 
The same problem I had earlier, when I wanted (or still want to) set for example parameters for Adam, which only exist for Adam. For example the 'betas' parameters. Is that possible to do?

**Comment by BenjaminBossan** [comment]
This is more of an sklearn question than a skorch question. Could you please look if [this](https://scikit-learn.org/stable/modules/grid_search.html#exhaustive-grid-search) would work for you? Otherwise, the best solution is probably to just run two grid searches, one with and one without lr scheduling.

**Comment by MagicPatze** [comment]
Thank you very much, that seems to work perfectly!
