### ISSUE TITLE
Disable 'dur' output when fitting model

### ISSUE THREAD

**Issue by gloryVine** [skorch-dev/skorch#828]
The question is basically in the title: I find that the rightmost column, `dur`, clutters the output during fitting, and I do not need epoch-specfic duration information. How can I disable printing it?

**Comment by BenjaminBossan** [comment]
Add the `'dur'` key to the list of columns that the `PrintLog` callback should ignore:

```python
net = NeuralNet(..., callbacks__print_log__keys_ignored=['dur'])
```

**Comment by BenjaminBossan** [comment]
@gloryVine Did you have time to test yet?

**Comment by BenjaminBossan** [comment]
I'll assume this is resolved. If not, feel free to re-open.
