### ISSUE TITLE
GridSearchCV train_split error 

### ISSUE THREAD

**Issue by MagicPatze** [skorch-dev/skorch#829]
I have read [this issue](https://github.com/skorch-dev/skorch/issues/747) before and I am having the same problem basically. 
The only difference basically is, that I do want to shuffle my data. 

I do not know why, but I programmed 2 different versions but none worked. The first one is quite similar to the one presented before : 
```python
class RNGSampler: 
  def __init__(self, validperc): 
    self.validperc = validperc

  def __call__(self, x, y): 
    """
    validperc: rel. size valid set
    """
    self.x = x
    self.y = y 
    validperc = self.validperc

    # shuffle data
    xs, ys = shuffle(x,y, random_state= 7)
    dataset = np.concatenate((xs,ys), axis=1)

    train_idx = range(0,int(validperc*dataset.shape[0]))
    val_idx = range(int(validperc*dataset.shape[0]), dataset.shape[0])

    train_dataset = torch.utils.data.Subset(dataset, train_idx)
    val_dataset = torch.utils.data.Subset(dataset, val_idx)

    return train_dataset, val_dataset
```
And I call the class like this: 
```python 
sampler = RNGSampler(validperc=0.1)
nn = NeuralNetRegressor(NeuralNet, verbose=0, train_split = sampler(x = x, y = y))
```

In the other version I was relying on the skorch documntation saying that the format of the train and validation dataset can also be arrays: 

```python 
class Sampler: 
  def __init__(self, x, y):
    self.x = x
    self.y = y

  def randomsplit(self,validperc): 
    """
    validperc: rel. size valid set
    """
    self.validperc = validperc
    x = self.x 
    y = self.y 

    # shuffle data
    xs, ys = shuffle(x,y, random_state= 7)

    x_valid = xs[:int(validperc*xs.shape[0]),:]
    y_valid = ys[:int(validperc*ys.shape[0]),:]

    x_train = xs[int(validperc*xs.shape[0]):,:]
    y_train = ys[int(validperc*ys.shape[0]):,:]

    valid_array = np.concatenate((x_valid, y_valid), axis = 1)
    train_array = np.concatenate((x_train, y_train), axis= 1)

    return train_array, valid_array 
```
And I used it like this: 
```python
sampler = Sampler(x, y)
nn = NeuralNetRegressor(NeuralNet, verbose=0, train_split = sampler.randomsplit(validperc = 0.1)
```

However, in both of these examples I get the same error which is: 
```python 
TypeError: 'tuple' object is not callable
```
Is there anything obvious I am not seeing?

**Comment by BenjaminBossan** [comment]
_Replying here and not in the closed issue_

Could you please explain first what you want to achieve? Is your intent just to create of the training data? In that case, why not use the default implementation, which already creates a random split? It already allows you to specify the proportion of data to use for training and for validation.

If this is not what you're after, could you please explain in more detail? Also, could you please paste the whole stacktrace?

**Comment by MagicPatze** [comment]
Well, I just want to implement a random split stating the percentage of the validation and training set. If that is already implemented, I might have missed that. How is that the default implementation? Isn't the default implementation the randomCVsplit? I would like to avoid that because of my special use case. 
If it is easy to implement a standard random split, please indicate me how to do it. Thanks!

**Comment by BenjaminBossan** [comment]
> I just want to implement a random split stating the percentage of the validation and training set

This is already possible with the `cv` argument of `CVSplit`. Please take a look at the [docs](https://skorch.readthedocs.io/en/stable/dataset.html#skorch.dataset.CVSplit) to see all possibilities.

> Isn't the default implementation the randomCVsplit? I would like to avoid that because of my special use case.

I believe there is probably a misunderstanding of what's going on here. The default is a random split. Probably you think it does something that it actually doesn't do. From my understanding, it should do what your code tries to achieve.

**Comment by MagicPatze** [comment]
Oh, I think I indeed made a big mistake there. I thought the skorch cvsplit would be similar to the sklearn cvsplit for gridsearch, where it cycles through every split, alternating the validation split. I am very sorry I did not clarify myself well and for not reading the documentations well enough. 
Thank you for your help!
