### ISSUE TITLE
readthedocs search optimization

### ISSUE THREAD

**Issue by ottonemo** [skorch-dev/skorch#834]
readthedocs analytics says that we have several search results that yield little or no useful results. Let's improvethose:

- gpu (only 2 results): make sure that explanation of `device` parameter mentions `gpu` as well
- gridsearch (0 results): make sure to include the term `gridsearch` in the [meta data](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#html-metadata) of the `GridSearchCV` page (or similar)
- seed (0 results): think about a FAQ answer
- earlystop (0 results): make sure to include the `earlystop` keyword in the callbacks section

**Comment by BenjaminBossan** [comment]
Should we close this or leave it open as a reminder?

**Comment by ottonemo** [comment]
This was addressed in #879 and #836.
