### ISSUE TITLE
Isinstance checks for huggingface BatchEncoding

### ISSUE THREAD

**Issue by BenjaminBossan** [skorch-dev/skorch#838]
When using tokenizers from huggingface's `transformers` library, we run into a small annoyance:

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
tokens = tokenizer(X)
type(tokens)  # returns transformers.tokenization_utils_base.BatchEncoding,
skorch.dataset.Dataset(tokens)  # fails
```

This is a type that skorch does not understand. The catch is, however, that the type is _almost_ a dictionary. Using:

```python
tokens_dict = {key: val for key, val in tokenizer(X).items}
skorch.dataset.Dataset(tokens_dict)  # works
```
The only problem is that `isinstance(tokens, dict)` fails because it does not inherit from `dict`. Instead, when looking at the `__mro__` of `BatchEncoding`, we get:

```python
(transformers.tokenization_utils_base.BatchEncoding,
 collections.UserDict,
 collections.abc.MutableMapping,
 collections.abc.Mapping,
 collections.abc.Collection,
 collections.abc.Sized,
 collections.abc.Iterable,
 collections.abc.Container,
 object)
```

So one possible solution for us would be to always check for `UserDict` on top of `dict` where we do `isinstance` checks. A quick check turned up these 4 places, but there might be more:

https://github.com/skorch-dev/skorch/blob/6ca5c4e20357963e845e8a0a488b7c7dffdf82f7/skorch/utils.py#L94
https://github.com/skorch-dev/skorch/blob/6ca5c4e20357963e845e8a0a488b7c7dffdf82f7/skorch/utils.py#L126
https://github.com/skorch-dev/skorch/blob/baf058038e299242db3ff6ca22300ba7a46f129e/skorch/dataset.py#L43
https://github.com/skorch-dev/skorch/blob/c0df4d1a11e1e023bc7ce868efaa266d6964f203/skorch/net.py#L1361

This is not the most elegant solution but I can't think of anything better if we want to integrate more smoothly with huggingface (short of asking them to add an option to return plain dicts).

**Comment by thomasjpfan** [comment]
We can check for `Mapping` instead:

```python
from transformers import AutoTokenizer
from collections.abc import Mapping

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
tokens = tokenizer(["This is a sentence"])

print(isinstance(tokens, Mapping))
# True
```

**Comment by BenjaminBossan** [comment]
Yes, good idea. `MutableMapping` would also work but probably there is no reason to use that instead.
