### ISSUE TITLE
pytorch Dataloader and skorch fit()

### ISSUE THREAD

**Issue by andreapi87** [skorch-dev/skorch#844]
I understand here https://skorch.readthedocs.io/en/stable/net.html
 that to use a Pytorch Dataloader into a skorch model I can do:

`model.set_params(iterator_train=train_loader)`

However, in sklearn models, the fit call requires a parameter (e.g. `grisearchcv_obj.fit(X)`).
What have I to pass to fit if I already set the dataloader in the `iterator_train` parameter?

**Comment by BenjaminBossan** [comment]
The idea is that if you need your own, custom `DataLoader` class, you can pass it as `net = NeuralNet(..., iterator_train=MyDataLoader)` (no need to use `set_params`). Note that we pass the _class_, not an actual instance with data attached. The data itself should still come from `X`.

Most likely, you should not need to pass your own `DataLoader` class, the default one is already quite flexible as is. Maybe if you can explain your use case in more detail, we can see if there is not an easier way.

**Comment by envytails** [comment]
> The idea is that if you need your own, custom `DataLoader` class, you can pass it as `net = NeuralNet(..., iterator_train=MyDataLoader)` (no need to use `set_params`). Note that we pass the _class_, not an actual instance with data attached. The data itself should still come from `X`.
> 
> Most likely, you should not need to pass your own `DataLoader` class, the default one is already quite flexible as is. Maybe if you can explain your use case in more detail, we can see if there is not an easier way.

ah! Thanks for the clarification! However, it seems that I don't need a dataloader, and the dataset object  is enough
`gridsearchcv_obj.fit(dataset_obj)`

**Comment by BenjaminBossan** [comment]
@andreapi87 I think the issue is resolved, right? If not, feel free to re-open.
