### ISSUE TITLE
something strange with crossvalidation and fit on Dataset object

### ISSUE THREAD

**Issue by andreapi87** [skorch-dev/skorch#845]
the following code, taken from https://skorch.readthedocs.io/en/stable/user/FAQ.html#faq-how-do-i-use-a-pytorch-dataset-with-skorch, works as expected:

```
import torch.utils.data

class RandomDataset(torch.utils.data.Dataset):
    def __init__(self):
        self.X = torch.zeros(128, 5)
        self.Y = torch.ones(128, 5)

    def __getitem__(self, idx):
        print(self.X[idx].shape)
        return self.X[idx], self.Y[idx]

    def __len__(self):
        return 128
    
from skorch import NeuralNet
import torch.nn as nn

train_ds = RandomDataset()

  class MyModule(nn.Module):
      def __init__(self):
          super().__init__()
          self.layer = torch.nn.Linear(5, 5)
  
      def forward(self, X):
          return self.layer(X)
  
  net = NeuralNet(MyModule, 
                  optimizer=torch.optim.Adam,
                  criterion=torch.nn.MSELoss,
                  batch_size=3,
                 )
```

however, if I made the same with GridSearchCV, something strange happens:
```
from sklearn.model_selection import GridSearchCV
gs = GridSearchCV(net, dict(lr=[0.1,], max_epochs=[10,]), 
                  refit   = True,
                  cv      = 3,
                  n_jobs  = 1,
                 )
gs.fit(train_ds)
```
This code produce me several errors.

The last one was: 
```  File "/home/andrea/PYTHON_ENVIRONMENTS/ML/lib/python3.8/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
TypeError: linear(): argument 'input' (position 1) must be Tensor, not list

  warnings.warn(some_fits_failed_message, FitFailedWarning)
```
I think there is something strange in batch construction. 
This is evident adding a print in the forward method of the model:
```
    def forward(self, X):
        print(X)
        return self.layer(X)
```
 the data shapes are different for net.fit() and gs.fit().

**Comment by BenjaminBossan** [comment]
Could you please try if [this](https://skorch.readthedocs.io/en/stable/user/FAQ.html#how-do-i-use-sklearn-gridseachcv-when-my-data-is-in-a-dataset) solves your problem?

> the data shapes are different for net.fit() and gs.fit().

In general, that's expected, because for grid search, sklearn splits the data into multiple folds (depending on your parameters), leading to a smaller number of samples per fit call during grid search.

**Comment by BenjaminBossan** [comment]
@andreapi87 Did it work?

**Comment by andreapi87** [comment]
it seems to work...However, I'm using gridsearchCV with other data using dataset object (without passing for sliceDataset) and it seems also to work...I don't undestand why with random data I need sliceDtaset

**Comment by BenjaminBossan** [comment]
> I'm using gridsearchCV with other data using dataset object (without passing for sliceDataset) and it seems also to work

Hmm, this is strange. If it's possible, could you please provide code to reproduce this? In general, datasets don't work with sklearn out of the box because sklearn doesn't recognize them and because they don't support the full range of slicing operations that arrays support.

**Comment by BenjaminBossan** [comment]
@andreapi87 Any updates?

**Comment by andreapi87** [comment]
you are right, I can't replicate what I remember. Maybe I remember wrong. I close the topic. I will reopen it if I have any news. Thank you for your help!
