### ISSUE TITLE
Curious how `skorch` compares to `FastAI`

### ISSUE THREAD

**Issue by sgbaird** [skorch-dev/skorch#849]
https://docs.fast.ai/

https://docs.fast.ai/migrating_pytorch

**Comment by BenjaminBossan** [comment]
I only have little experience with fastai, so I cannot answer your question too well. The main focus of skorch, though, is to provide sklearn compatibility.

For an overview of high level PyTorch frameworks, including fastai and skorch, take a look at [this blogpost](https://neptune.ai/blog/model-training-libraries-pytorch-ecosystem). For my personal take on what advantages skorch provides, take a look [here](https://github.com/NewYorkerData/public-presentations/blob/master/20191010-pycon-pydata/presentation.org) (but the article is 2 years old).

**Comment by sgbaird** [comment]
@BenjaminBossan the blogpost you linked is really nice. Thank you! Will be sharing that with others. I like the visually pleasing pycon presentation you linked to as well. Thanks for the treasure trove 🙂
