### ISSUE TITLE
where is uses_placeholder_y in 0.11.0?

### ISSUE THREAD

**Issue by chch2010523** [skorch-dev/skorch#857]
when i run this code:

```
from skorch.dataset import uses_placeholder_y
...
y_valid_is_ph = uses_placeholder_y(dataset)
....
yi_res = yi  if not y_valid_is_ph else none
```

it cannot found this function in 0.11.0.
so how to solve this problem in new stable version

**Comment by BenjaminBossan** [comment]
We removed this from the code in #699. Let me cite myself:

> Another "victim" of this change is the checking for whether y is a
> placeholder and then replacing it with None. Tbh. I found this to be
> an ugly solution anyway. Now it can happen that when a user uses the
> skorch Dataset, they will receive a 0s tensor for y when they set y to
> None. I think this is an acceptable loss overall.

I'm not sure why you need this but I assume that you have a custom training loop, e.g. you overrode `run_single_epoch`. Most likely, the solution for you would be to just ignore this check completely. Take a look at how `run_single_epoch` is implemented now and then add your changes on top of the current implementation:

https://github.com/skorch-dev/skorch/blob/fe71e3d55a4ae5f5f94ef7bdfc00fca3b3fd267f/skorch/net.py#L1115-L1150

If you specifically need this check, things become more difficult. In that case, maybe you can share more details about your use case and we can try to figure something out.

**Comment by BenjaminBossan** [comment]
@chch2010523 does this solve your issue?

**Comment by chch2010523** [comment]
Thank you for your reply! I have ignored this check completely and this problem disappeared. Many thanks again！

**Comment by BenjaminBossan** [comment]
Great, thanks for coming back at us.
