### ISSUE TITLE
AxisError: axis 1 is out of bounds for array of dimension 1

### ISSUE THREAD

**Issue by BinchaoPeng** [skorch-dev/skorch#865]
**Python code**:
```python
# %load_ext autoreload
# %autoreload 2
lr = 0.0005
model = CNNNet() # out:(batch,) ==changed,in my model I use `x.view(-1)` to flatten output==

optimizer = torch.optim.Adam
criterion = nn.BCELoss()
net = NeuralNetClassifier(module=model, criterion=criterion, optimizer=optimizer, lr=lr, device=device,
                          # Shuffle training data on each epoch
                          iterator_train__shuffle=True, batch_size=64, verbose=30, max_epochs=500)
# X_one_hot: (5720, 81, 4)
# y1: (5720,)
net.fit(X_one_hot.astype('float32'), y1.astype('float32'))
```

**Exception**:
```bash
AxisError: axis 1 is out of bounds for array of dimension 1

AxisError                                 Traceback (most recent call last)
<ipython-input-14-8b698bee6407> in <module>
     10                           iterator_train__shuffle=True, batch_size=64, verbose=30, max_epochs=500)
     11 
---> 12 net.fit(X_one_hot.astype('float32'), y1.astype('float32'))

~/anaconda3/envs/torch/lib/python3.6/site-packages/skorch/classifier.py in fit(self, X, y, **fit_params)
    139         # this is actually a pylint bug:
    140         # https://github.com/PyCQA/pylint/issues/1085
--> 141         return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
    142 
    143     def predict_proba(self, X):

~/anaconda3/envs/torch/lib/python3.6/site-packages/skorch/net.py in fit(self, X, y, **fit_params)
   1213             self.initialize()
   1214 
-> 1215         self.partial_fit(X, y, **fit_params)
   1216         return self
   1217 

~/anaconda3/envs/torch/lib/python3.6/site-packages/skorch/net.py in partial_fit(self, X, y, classes, **fit_params)
   1172         self.notify('on_train_begin', X=X, y=y)
   1173         try:
-> 1174             self.fit_loop(X, y, **fit_params)
   1175         except KeyboardInterrupt:
   1176             pass

~/anaconda3/envs/torch/lib/python3.6/site-packages/skorch/net.py in fit_loop(self, X, y, epochs, **fit_params)
   1091                                   step_fn=self.validation_step, **fit_params)
   1092 
-> 1093             self.notify("on_epoch_end", **on_epoch_kwargs)
   1094         return self
   1095 

~/anaconda3/envs/torch/lib/python3.6/site-packages/skorch/net.py in notify(self, method_name, **cb_kwargs)
    357         getattr(self, method_name)(self, **cb_kwargs)
    358         for _, cb in self.callbacks_:
--> 359             getattr(cb, method_name)(self, **cb_kwargs)
    360 
    361     # pylint: disable=unused-argument

~/anaconda3/envs/torch/lib/python3.6/site-packages/skorch/callbacks/scoring.py in on_epoch_end(self, net, dataset_train, dataset_valid, **kwargs)
    470 
    471         with _cache_net_forward_iter(net, self.use_caching, y_pred) as cached_net:
--> 472             current_score = self._scoring(cached_net, X_test, y_test)
    473 
    474         self._record_score(net.history, current_score)

~/anaconda3/envs/torch/lib/python3.6/site-packages/skorch/callbacks/scoring.py in _scoring(self, net, X_test, y_test)
    178         instead of running inference again, if available."""
    179         scorer = check_scoring(net, self.scoring_)
--> 180         return scorer(net, X_test, y_test)
    181 
    182     def _is_best_score(self, current_score):

~/anaconda3/envs/torch/lib/python3.6/site-packages/sklearn/metrics/_scorer.py in __call__(self, estimator, X, y_true, sample_weight)
    198         """
    199         return self._score(partial(_cached_call, None), estimator, X, y_true,
--> 200                            sample_weight=sample_weight)
    201 
    202     def _factory_args(self):

~/anaconda3/envs/torch/lib/python3.6/site-packages/sklearn/metrics/_scorer.py in _score(self, method_caller, estimator, X, y_true, sample_weight)
    234         """
    235 
--> 236         y_pred = method_caller(estimator, "predict", X)
    237         if sample_weight is not None:
    238             return self._sign * self._score_func(y_true, y_pred,

~/anaconda3/envs/torch/lib/python3.6/site-packages/sklearn/metrics/_scorer.py in _cached_call(cache, estimator, method, *args, **kwargs)
     51     """Call estimator with method and args and kwargs."""
     52     if cache is None:
---> 53         return getattr(estimator, method)(*args, **kwargs)
     54 
     55     try:

~/anaconda3/envs/torch/lib/python3.6/site-packages/skorch/classifier.py in predict(self, X)
    206 
    207         """
--> 208         return self.predict_proba(X).argmax(axis=1)
    209 
    210 
```

**Describtions**:
When I use `train_split=None`, `net.fit()` can work but printLog does not show any acc info.
When I use the default value of `train_split`, the exception is showed above.
I read the Doc of skorch, but I am confused about the describtion of param `train_split`.

Secondly, when I use `GridSearchCV`, all metrics is nan. I don't konw what the promblem is.

```python
from sklearn.model_selection import GridSearchCV
# from sklearn.metrics import matthews_corrcoef, confusion_matrix, auc, roc_auc_score, average_precision_score,
#     precision_score, recall_score, f1_score

# deactivate skorch-internal train-valid split and verbose logging
net.set_params(train_split=False, verbose=0)
params = {
    'lr': [0.01],
}
gs = GridSearchCV(net, params, refit='accuracy', cv=5,
                  scoring=['accuracy', 'roc_auc', 'average_precision', 'precision', 'recall',
                           'f1'],
                  verbose=3)

gs.fit(X_one_hot.astype('float32'), y1.astype('float32'))
print("best score: {:.3f}, best params: {}".format(gs.best_score_, gs.best_params_))
```

**Comment by BinchaoPeng** [comment]
`return self.predict_proba(X).argmax(axis=1)`
When I changed my `CNNNet` using `softmax` and `cross_entronpy_loss` instead of `sigmoid` and `BCE`, then the `fit`  worked.
So, in the case of using `sigmoid` and `BCE` to solve a binary classification problem, is it suitable for skorch?

**Comment by BinchaoPeng** [comment]
@BenjaminBossan 
> Sigmoid should be used when you use `NeuralNetBinaryClassifier`
Does it means that using `sigmoid` and `BCE` in `NeuralNetClassifier` is a wrong way?  

> The problem was probably that `y1` is represented as a float, but if you want to solve a classification problem, it should be an int64.
```python
from skorch.callbacks import EpochScoring

auc = EpochScoring(scoring='roc_auc', lower_is_better=False)
acc = EpochScoring(scoring='accuracy', lower_is_better=False)

lr = 0.001
model = CNNNet()

optimizer = torch.optim.Adam
criterion = nn.BCELoss()
net = NeuralNetClassifier(module=model, optimizer=optimizer, lr=lr, device=device, criterion=criterion,
                          # Shuffle training data on each epoch
                          iterator_train__shuffle=True, batch_size=64, verbose=30, max_epochs=10, callbacks=[auc, acc])
# X_one_hot: (5720, 81, 4)
# y1: (5720,)
# net.fit(X_train, y_train.astype('long'))
net.fit(X_train, y_train)
```
Firstly, I tried int64 for `y1` when using `sigmoid` and `BCE` in `NeuralNetClassifier`, but Exception showed that `RuntimeError: Found dtype Long but expected Float`.
And then I set `y_train.astype('long')` , Exception showed that `AxisError: axis 1 is out of bounds for array of dimension 1`.

**Comment by BinchaoPeng** [comment]
```python
from skorch.callbacks import EpochScoring

auc = EpochScoring(scoring='roc_auc', lower_is_better=False)
acc = EpochScoring(scoring='accuracy', lower_is_better=False)

lr = 0.001
model = CNNNet() 

optimizer = torch.optim.Adam
criterion = nn.BCELoss()
net = NeuralNetBinaryClassifier(module=model, optimizer=optimizer, lr=lr, device=device, criterion=criterion,
                          # Shuffle training data on each epoch
                          iterator_train__shuffle=True, batch_size=64, verbose=30, max_epochs=10, callbacks=[auc, acc])
# X_one_hot: (5720, 81, 4)
# y1: (5720,)
# net.fit(X_train, y_train.astype('long'))
net.fit(X_train, y_train)
```
**Exception**:
```bash
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```
There is an exception, too. It may be so difficult for me to use skorch correctly.....

**Comment by BenjaminBossan** [comment]
> There is an exception, too. It may be so difficult for me to use skorch correctly.....

I'm sorry to hear that, but I'm sure we can figure out the problem together :) Here are a few things I would like to know so I can better help you.

1. For your example using `NeuralNetClassifier`, could you please paste the complete stack trace? It's very difficult for me to debug with only the last line.
2. You show the shape of `X_one_hot` but you use `X_train`, what is its shape?
3. You write that `model = CNNNet() # out:(batch,1)`, could you try squeezing the output to have a shape of `(batch,)` only?

**Comment by BinchaoPeng** [comment]
Thanks a lot! 
> For your example using `NeuralNetClassifier`, could you please paste the complete stack trace? It's very difficult for me to debug with only the last line.

The complete stacktrace is mentioned in the top block. I have pasted the whole stack because it was all showed in my jupyter console.

> You show the shape of `X_one_hot` but you use `X_train`, what is its shape?

`X_train` was splited from `X_one_hot` becasue of a dataset split operation using sklearn, and the rate is 8:2, so the shape of  `X_train` is also `(5720*0.8, 81, 4)`

> You write that model = CNNNet() # out:(batch,1), could you try squeezing the output to have a shape of (batch,) only?

I used `x.view(-1)` to flatten my output vector in my model, so the real shape of output is `(batch,)`, just like [0.54,0.23,0.46] when batch = 3.

**Comment by BenjaminBossan** [comment]
> The complete stacktrace is mentioned in the top block. I have pasted the whole stack because it was all showed in my jupyter console.

Sorry, I meant the stack trace for the error after you changed the dtype of `y` to long (at the bottom of [that comment](https://github.com/skorch-dev/skorch/issues/865#issuecomment-1173245227)). Or is it still the exact same stack trace?

> `X_train` was splited from `X_one_hot` becasue of a dataset split operation using sklearn, and the rate is 8:2, so the shape of `X_train` is also `(5720*0.8, 81, 4)`

> I used `x.view(-1)` to flatten my output vector in my model, so the real shape of output is `(batch,)`, just like [0.54,0.23,0.46] when batch = 3.

Okay, got it.

In your example above, could you please try these changes?

> ```python
> from skorch.callbacks import EpochScoring
> 
> auc = EpochScoring(scoring='roc_auc', lower_is_better=False)
> acc = EpochScoring(scoring='accuracy', lower_is_better=False)
> 
> lr = 0.001
> model = CNNNet() 
> 
> optimizer = torch.optim.Adam
> criterion = nn.CrossEntropyLoss                              # <= changed
> net = NeuralNetClassifier(                                   # <= changed
>     module=model, optimizer=optimizer, lr=lr, device=device, criterion=criterion,
>      # Shuffle training data on each epoch
>     iterator_train__shuffle=True, batch_size=64, verbose=30, max_epochs=10, callbacks=[auc, acc])
> net.fit(X_train, y_train)
> ```

The dtype of `y_train` should be int64 if a numpy array or long if a torch tensor.

**Comment by BinchaoPeng** [comment]
> > The complete stacktrace is mentioned in the top block. I have pasted the whole stack because it was all showed in my jupyter console.
> 
> Sorry, I meant the stack trace for the error after you changed the dtype of `y` to long (at the bottom of [that comment](https://github.com/skorch-dev/skorch/issues/865#issuecomment-1173245227)). Or is it still the exact same stack trace?
> 
> > `X_train` was splited from `X_one_hot` becasue of a dataset split operation using sklearn, and the rate is 8:2, so the shape of `X_train` is also `(5720*0.8, 81, 4)`
> 
> > I used `x.view(-1)` to flatten my output vector in my model, so the real shape of output is `(batch,)`, just like [0.54,0.23,0.46] when batch = 3.
> 
> Okay, got it.
> 
> In your example above, could you please try these changes?
> 
> > ```python
> > from skorch.callbacks import EpochScoring
> > 
> > auc = EpochScoring(scoring='roc_auc', lower_is_better=False)
> > acc = EpochScoring(scoring='accuracy', lower_is_better=False)
> > 
> > lr = 0.001
> > model = CNNNet() 
> > 
> > optimizer = torch.optim.Adam
> > criterion = nn.CrossEntropyLoss                              # <= changed
> > net = NeuralNetClassifier(                                   # <= changed
> >     module=model, optimizer=optimizer, lr=lr, device=device, criterion=criterion,
> >      # Shuffle training data on each epoch
> >     iterator_train__shuffle=True, batch_size=64, verbose=30, max_epochs=10, callbacks=[auc, acc])
> > net.fit(X_train, y_train)
> > ```
> 
> The dtype of `y_train` should be int64 if a numpy array or long if a torch tensor.

yeah, I know it, it means using multi-classification model for my binary classification. I tried it and it can worked.

**Comment by BinchaoPeng** [comment]
> `return self.predict_proba(X).argmax(axis=1)` When I changed my `CNNNet` using `softmax` and `cross_entronpy_loss` instead of `sigmoid` and `BCE`, then the `fit` worked. So, in the case of using `sigmoid` and `BCE` to solve a binary classification problem, is it suitable for skorch?

Just look here @BenjaminBossan

**Comment by BenjaminBossan** [comment]
Okay, so to get it straight:

1. You managed to get the net to train correctly using `NeuralNetClassifier`.
2. But you want to use `NeuralNetBinaryClassifier` instead.

I think you should be fine with `NeuralNetClassifier`, as it can perfectly deal with binary classification problems as well. So as long as there is no very specific need for `NeuralNetBinaryClassifier`, I would not use it.

If you have to use `NeuralNetBinaryClassifier`, could you please try `criterion = nn.BCEWithLogitsLoss` and see if that works?

**Comment by BinchaoPeng** [comment]
Thanks for your useful advice, I will try it !
