### ISSUE TITLE
forward() missing 1 required positional argument: 'X'

### ISSUE THREAD

**Issue by DreamCookie** [skorch-dev/skorch#885]
Hey there! Awesome repository! 

Learning from your code in Google Colab and dropped in "TypeError: forward() missing 1 required positional argument: 'X'" when I net.fit(X_train, y_train); (20 input line in your code).

Checked, everything looking fine, what am I missing?

Thanks!

**Comment by githubnemo** [comment]
Hey @DreamCookie, thanks! :)

Can you tell us what notebook you were executing in Google Colab?

**Comment by DreamCookie** [comment]
@githubnemo hey!

MNIST.ipynb (from https://github.com/skorch-dev/skorch/blob/master/notebooks/MNIST.ipynb)

**Comment by BenjaminBossan** [comment]
I think the trouble is that sklearn changed the default data type for `fetch_openml` from numpy array to pandas dataframe. If you change the 3rd cell to:

```python
mnist = fetch_openml('mnist_784', as_frame=False, cache=False)
```

the rest should work.

If you want to, also feel free to create a PR to fix this error :)

**Comment by DreamCookie** [comment]
@BenjaminBossan it worked! Big thanks to you! When I studied the documentation for loading the dataset, I did not pay due attention to these parameters, since the dataset was loaded immediately without additional parameters, but it backfired on me later ..
Thanks for the suggestion, maybe later if I find some more opportunities for editing and I can solve them - I will create a PR
Have a good day!

**Comment by BenjaminBossan** [comment]
> it worked! Big thanks to you! 

Great to hear that.

> Thanks for the suggestion, maybe later if I find some more opportunities for editing and I can solve them - I will create a PR
> Have a good day!

I created a PR (#886), it was just a few lines of code anyway :)
