### ISSUE TITLE
Distutils Version classes (including LooseVersion) are deprecated

### ISSUE THREAD

**Issue by timokau** [skorch-dev/skorch#887]
The `LooseVersion` class (see #579) is now deprecated ([distutils commit](https://github.com/pypa/distutils/commit/92082ee42c), [setuptools changelog](https://setuptools.pypa.io/en/latest/history.html#v59-6-0)), which results in warnings of the form:

```
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(sklearn.__version__) >= '0.22.0':
```

We should probably follow the suggestion and move to `packaging.version`.

**Comment by BenjaminBossan** [comment]
I didn't know that, thanks for bringing it up.

Is `packaging` part of the standard Python distribution or an extra dependency for all our supported Python versions? It seems not to exist for < 3.8, could it be? If so, I guess we would need to write the code in a way to still use `LooseVersion` for old Python versions.

**Comment by timokau** [comment]
I'm not sure, but as far as I know it's an extra dependency but it should be available for python >= 3.6 according to [pypi](https://pypi.org/project/packaging/#description).

**Comment by thomasjpfan** [comment]
Using `packaging.version` is known to be slow: https://github.com/pypa/setuptools/issues/926

For Python >= 3.8, the best way to get versions is: [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html). Since we still support 3.7, there is a [shim on pypi](https://pypi.org/project/importlib-metadata/#description).

If we do not want to add another dependency, we can vendor the code for `packaging.version`. For example, this is how SciPy vendors it: https://github.com/scipy/scipy/blob/main/scip

**Comment by BenjaminBossan** [comment]
Why is something that is seemingly simple so complex? :(

> For Python >= 3.8, the best way to get versions is: [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html).

One difference would be that this would compare strings, whereas with `LooseVersion`, we get a bit of a more sophisticated logic. E.g.:

`LooseVersion(sklearn.__version__).version  # => [1, 2, 'dev', 0]`

Maybe it makes no difference for what we use, but I would much prefer a solution that uses the existing logic to compare versions.

> For example, this is how SciPy vendors it: https://github.com/scipy/scipy/blob/main/scip

The link is broken but in general, if we're just dealing with a few lines of code, I'd prefer vendoring to adding a new dependency.

**Comment by thomasjpfan** [comment]
My link got cut out. Here is the full link: https://github.com/scipy/scipy/blob/main/scipy/_lib/_pep440.py

**Comment by BenjaminBossan** [comment]
The scipy code looks good and should be battle tested. I'm not to happy that there seems to be no better option, but vendoring that code gets a +1 from me.

**Comment by BenjaminBossan** [comment]
With the [module](https://github.com/skorch-dev/skorch/blob/master/skorch/_version.py) copied from scipy, we should be good, so let's close for now.

**Comment by timokau** [comment]
Thank you!
