### ISSUE TITLE
when skorch  will has cpp version for libtorch cpp env?

### ISSUE THREAD

**Issue by mullerhai** [skorch-dev/skorch#891]
HI Dear skorch Team:
when I first use cpp libtorch to process the text data feel difficult ,I don't know any nlp framework in cpp writen and suitable with libtorch cpp, I know the opencv cpp is suitable with libtorch in visual domain. but nlp cpp framework I don't know ,also for the recommend system cpp, so  do we have some sklearn framework like skorch in cpp version ?https://github.com/skorch-dev/skorch

thanks

**Comment by BenjaminBossan** [comment]
If I understand you correctly, you're asking if there is an sklearn framework for (lib)torch in C++. As far as I know, there is not.

I don't know the problem you're trying to solve, but you can use Python (with sklearn, skorch, etc.) to train your torch model and then export it to use it without a Python runtime, so just with C++. Maybe that can be a solution.

**Comment by mullerhai** [comment]
> If I understand you correctly, you're asking if there is an sklearn framework for (lib)torch in C++. As far as I know, there is not.
> 
> I don't know the problem you're trying to solve, but you can use Python (with sklearn, skorch, etc.) to train your torch model and then export it to use it without a Python runtime, so just with C++. Maybe that can be a solution.

thanks, I know your meaning, It's also good  solution ,but for cpp env ,we want to build  full stack model etl train deploy pipeline like python pytorch.

**Comment by BenjaminBossan** [comment]
With this setup, I'm afraid it won't be possible to use sklearn/skorch, you would have to work with the tools provided by libtorch.

**Comment by BenjaminBossan** [comment]
If you have any further questions, feel free to reopen.
