### ISSUE TITLE
Redirection from notebook example to Open in Colab doesn't work

### ISSUE THREAD

**Issue by merveenoyan** [skorch-dev/skorch#893]
You need to authorize GitHub from Colab and save a copy in GitHub of a Colab notebook if you want to add a redirection from GitHub to Colab. 
<img width="1182" alt="Ekran Resmi 2022-09-26 14 29 01" src="https://user-images.githubusercontent.com/53175384/192276437-2bcaf3d2-7173-4e60-8f95-8e92cbd61e22.png">
<img width="1142" alt="Ekran Resmi 2022-09-26 14 29 10" src="https://user-images.githubusercontent.com/53175384/192276446-382ba4fe-1152-42a8-abdf-7f5a19a8e322.png">

**Comment by BenjaminBossan** [comment]
Fix is on the way [here](https://github.com/skorch-dev/skorch/pull/881/files#diff-e4b3e3d658c5d0c4606bd4619921657721c92bc5f27bea3d828fc6ff12c07d7c), so the issue will be resolved by #881

**Comment by BenjaminBossan** [comment]
The PR has been merged, the link now works correctly.
