### ISSUE TITLE
ImportError: cannot import name 'Sequence' from 'collections'

### ISSUE THREAD

**Issue by weissmanuel** [skorch-dev/skorch#895]
Got the following error when using `skorch.helper.predefined_split` with Python 3.10

`ImportError: cannot import name 'Sequence' from 'collections'`

Using Python 3.9 worked as workaround but would nice if skorch would also work for Python 3.10.

**Comment by BenjaminBossan** [comment]
Hmm, this works for me:

```
python3.10 -c "from collections.abc import Sequence"
```

Same for 

```
python3.9 -c "from collections.abc import Sequence"
```

Any idea what the issue could be?

Officially, we don't have 3.10 support yet because for a long time, there was an issue with underlying libraries, but now everything should work. We'll add 3.10 to our CI soon and then check if this issue or similar issues appear.

**Comment by BenjaminBossan** [comment]
@weissmanuel any updates?

**Comment by dliu-fn** [comment]
I'm encountering the exact same issue as @weissmanuel, but I checked:

* Python == 3.10
* skorch == 0.11.0
* pytorch == 1.12.1+cu102

And I'm confused, because I _see_ that it's correct in the repo: https://github.com/skorch-dev/skorch/blob/master/skorch/helper.py#L6

**Comment by dliu-fn** [comment]
Ohhhh this was only [merged into a release](https://github.com/skorch-dev/skorch/pull/850) recently on the `0.12.0` release, so `0.11.0`was insufficient.

**Comment by BenjaminBossan** [comment]
Thanks for @dliu-fn for figuring this out, sorry that I forgot about it. I think we can close the issue now :)
