### ISSUE TITLE
pytorch-lightning

### ISSUE THREAD

**Issue by stephanecollot** [skorch-dev/skorch#920]
Hi,

Is there a way to use skorch with [pytorch-lightning](https://github.com/Lightning-AI/lightning)?

Thank you in advance

**Comment by BenjaminBossan** [comment]
Hey, I'm not sure why you would want to use both simultaneously, as part of their functionality overlaps. Could you give an example of a possible use case?

**Comment by stephanecollot** [comment]
I'm using a package called LOFO for feature importance model agnostic: https://github.com/aerdem4/lofo-importance
It takes as a parameter a scikit learn transformer, trains the model with CV with one feature out, for all features.

**Comment by stephanecollot** [comment]
So basically, I'm looking for a sklearn wrapper for pytorch-lightning.

**Comment by BenjaminBossan** [comment]
Okay, so from my understanding, LOFO itself has nothing to do with pytorch lightning, your just want to use LOFO together with a lightning model.

I'm not an expert on pytorch lightning, but IIRC, a `pl.LightningModule` can just work like a normal `nn.Module`. In that case, code like this *might work*:

```python

class MyLightningModule(pl.LightningModule):
    ...

from skorch import NeuralNet  # or NeuralNetClassifier or whatever you need

net = NeuralNet(module=MyLightningModule, ...)
net.fit(X, y)
```

Note that this would completely sidestep the whole lightning training machinery and use skorch instead. As I said, I don't think the two work well together.

**Comment by BenjaminBossan** [comment]
@stephanecollot Does this answer your question?

**Comment by stephanecollot** [comment]
Yes. I'm sorry I didn't have the time to try your suggestion, so I cannot
confirm if it works.

**Comment by BenjaminBossan** [comment]
Feel free to re-open the issue if you managed to test it and ran into problems.
