### ISSUE TITLE
Enable GitHub Discussions for the Project

### ISSUE THREAD

**Issue by RoyiAvital** [skorch-dev/skorch#939]
Would you consider enabling the GitHub Discussions feature for this forum?

**Comment by BenjaminBossan** [comment]
I haven't used GH discussions a lot yet. What would be the advantage over creating issues? Would it lead to fracturing information, thus making it harder to find for users? If it has some nice features and users can easily search issues + discussions at the same time, I'm happy to enable them.

**Comment by RoyiAvital** [comment]
Are issues, in your policy, the right place to ask questions of users / developers using Skorch?
Since the Slack of PyTorch is not open where one should ask questions about using Skorch in projects?

Regarding what you asked, it is easy to convert a discussion into issue and vice versa. 
The general search in the repository can search for an issue or discussion in a single search.

I think it is worth trying.
If it works, great. If not, you can mass convert all discussions into issues and disable it.

**Comment by BenjaminBossan** [comment]
Okay, thanks for the info. Discussions should be enabled now: https://github.com/skorch-dev/skorch/discussions

> Are issues, in your policy, the right place to ask questions of users / developers using Skorch?

Yes, this is how it was done so far. Let's see if Discussions will used from now on.

> Since the Slack of PyTorch is not open

No worries, Slack is very inactive.

**Comment by BenjaminBossan** [comment]
Discussions are open.

**Comment by RoyiAvital** [comment]
@BenjaminBossan , I think it should be added to the communication section on the `README.md`:

![image](https://user-images.githubusercontent.com/7347975/228228162-60dcefd6-37cf-4f22-9757-f2f8c735f477.png)
