### ISSUE TITLE
API documentation pages are empty 

### ISSUE THREAD

**Issue by t170815518** [skorch-dev/skorch#967]
All links in https://skorch.readthedocs.io/en/latest/skorch.html are empty.

![image](https://github.com/skorch-dev/skorch/assets/42442406/ab83ed4c-a0d3-44ed-a0a6-8347ceec60ff)

**Comment by BenjaminBossan** [comment]
Thanks a lot for reporting, it is probably related to #964. It seems that the old docs from v0.12.1 are still working:

https://skorch.readthedocs.io/en/v0.12.1/net.html

So unfortunately, you need to use those, or build the docs locally, until we find a fix.

**Comment by t170815518** [comment]
> Thanks a lot for reporting, it is probably related to #964. It seems that the old docs from v0.12.1 are still working:
> 
> https://skorch.readthedocs.io/en/v0.12.1/net.html
> 
> So unfortunately, you need to use those, or build the docs locally, until we find a fix.

Yes I can access the old docs. Thank you for the suggestion! :)

**Comment by BenjaminBossan** [comment]
@t170815518 The issue has been resolve. On the `latest` doc build, the API docs work as expected, see e.g. https://skorch.readthedocs.io/en/latest/callbacks.html. For the `stable` build, they'll remain broken until the next release :-/
