### ISSUE TITLE
Skorch API Documents Pages are blank

### ISSUE THREAD

**Issue by jvolante** [skorch-dev/skorch#977]
For some reason, it looks like the API reference pages on the Skorch documentation website are now blank, I'm not sure if this info has been moved elsewhere, but I haven't been able to find it.

Example https://skorch.readthedocs.io/en/stable/callbacks.html

**Comment by BenjaminBossan** [comment]
Yes, very sorry about that, a recent change in the readthedocs config caused that. Only the stable branch of docs is affected, the [latest branch](https://skorch.readthedocs.io/en/latest/net.html) and [earlier versions](https://skorch.readthedocs.io/en/v0.12.1/net.html) are there.

See #967.

**Comment by jvolante** [comment]
Thanks, thought I was going crazy lol
