### ISSUE TITLE
Enable using validation dataset from gridSearchCv in Callbacks.

### ISSUE THREAD

**Issue by mingYi-ch** [skorch-dev/skorch#978]

**Comment by BenjaminBossan** [comment]
Yes, I understand your intent. What you describe is not possible with callbacks. It is also not recommended. By using the validation data from grid search for early stopping, you actually leak information from the validation data into the training process. This could lead to overfitting. Therefore, it is best to use the `train_split` from skorch: it is based on the training data and therefore there is no leakage.

**Comment by mingYi-ch** [comment]
I see. Thanks for pointing it out!  I will close it then.
