### ISSUE TITLE
Remove deprecated pkg_resources import

### ISSUE THREAD

**Issue by adrinjalali** [skorch-dev/skorch#981]
`pkg_resources` is deprecated as an API. I think the alternative is to use `packaging.version`.

The import occurs here: 

https://github.com/skorch-dev/skorch/blob/5b222a5897071c35a3ab0e0663796be366fdc954/skorch/__init__.py#L6-L7

And it makes CIs fail if they raise on deprecation warnings. Eg: https://github.com/fairlearn/fairlearn/actions/runs/5242050040/jobs/9464954323?pr=1241

In `scikit-learn` we vendor `packaging` instead of having it as a dependency, but it's a very lightweight dependency.

**Comment by ottonemo** [comment]
Thanks for reporting. I just made a PR to address this issue.
