### ISSUE TITLE
Make dependency on torch explicit

### ISSUE THREAD

**Issue by lorentzenchr** [skorch-dev/skorch#998]
The dependency on `torch` is not made explicit. While the code base `import torch` several times, `torch` is not listed in the requirements.

**Comment by BenjaminBossan** [comment]
Indeed, when we created the project, we made the deliberate decision to not have `torch` as a dependency, a fact that we have documented ([1](https://github.com/skorch-dev/skorch#pytorch) [2](https://skorch.readthedocs.io/en/stable/user/installation.html#pytorch)).

The reason for that was that there were quite a few different ways to install PyTorch, depending on your OS, what CUDA version you use (if any), and whether you use conda or pypi. If we had added PyTorch as a dependency and a user runs `pip install skorch`, we would basically make a decision for the user which torch to install for them, which we didn't want.

It seems that now the situation has improved from the PyTorch side and a normal `pip install torch` should work. By adding the dependency, we could also explicitly set the supported PyTorch versions (although skorch probably works fine with older, non-supported versions too).

But to be sure that `pip install torch` just works, we would have to test that on bunch of different configurations, thus I'm on fence for this. Maybe we should just leave it as is.

**Comment by lorentzenchr** [comment]
Thanks, I just did not read the readme deep enough.
IIUC, it means that users always have to specify both skorch and torch as a requirement.

I guess it would not hurt to set torch in the requirements just without version specification: If it is installed, it won't be installed again. If it is not installed, it will be and a simple `pip install skorch` (maybe also `conda install skorch`?) is enough.

Those are my 2 cents:smirk:

**Comment by BenjaminBossan** [comment]
Thinking more about this, I believe it's safer to leave the situation as is. As an example of a potential issue, say someone has a CI pipeline that first installs skorch and in a second step PyTorch, which would be perfectly valid. If we add PyTorch as a dependency, suddenly PyTorch would already be installed when the second step comes, possible with a different version, which may or may not disrupt the CI pipeline.

Sure, we could argue that they should pin versions or something, but still, I feel the benefit of making the change is too small compared to the potential cost. So far, I haven't seen any complaints that PyTorch is not a dependency of skorch.

**Comment by lorentzenchr** [comment]
Ok. Let‘s close.
